// Insight-Performance-Hub/artifacts/perf-app/src/features/individual/IndividualAssessment.tsx
import { useState } from "react";
import {
  useListIndividualAssessments, useCreateIndividualAssessment,
  useListIndividualModerations, useCreateIndividualModeration,
  useListAgreements, useListCycles,
} from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/core/hooks/use-toast";
import { Plus, ClipboardCheck, Scale } from "lucide-react";

function getErrorMessage(e: unknown): string {
  if (e && typeof e === "object") {
    const obj = e as Record<string, unknown>;
    if (obj.response && typeof obj.response === "object") {
      const resp = obj.response as Record<string, unknown>;
      if (resp.data && typeof resp.data === "object") {
        const data = resp.data as Record<string, unknown>;
        if (typeof data.error === "string") return data.error;
      }
    }
    if (obj.message && typeof obj.message === "string") return obj.message;
  }
  return "An error occurred";
}

const TYPE_LABELS: Record<string, string> = {
  quarterly: "Quarterly Review",
  "mid-year": "Mid-Year Assessment",
  annual: "Annual Assessment",
};

export default function IndividualAssessment() {
  const { toast } = useToast();
  const { data: cycles } = useListCycles();
  const [selectedCycleId, setSelectedCycleId] = useState<number | undefined>();
  const [selectedAgreementId, setSelectedAgreementId] = useState<number | undefined>();
  const [showCreate, setShowCreate] = useState(false);
  const [showModerate, setShowModerate] = useState(false);

  const [form, setForm] = useState({ assessmentType: "quarterly" as "quarterly" | "mid-year" | "annual", quarter: 1, kpiScore: 0, competencyScore: 0, comments: "", developmentNeeds: "" });
  const [modForm, setModForm] = useState({ assessmentId: 0, outcome: "accepted" as "accepted" | "adjusted" | "referred", originalScore: 0, adjustedScore: 0, adjustmentReason: "", notes: "" });

  const { data: agreements } = useListAgreements({ cycleId: selectedCycleId });
  const { data: assessments, refetch } = useListIndividualAssessments({ agreementId: selectedAgreementId });
  const { data: moderations, refetch: refetchMods } = useListIndividualModerations({ agreementId: selectedAgreementId });
  const createAssessment = useCreateIndividualAssessment();
  const createModeration = useCreateIndividualModeration();

  const handleCreate = async () => {
    if (!selectedAgreementId) return;
    try {
      await createAssessment.mutateAsync({
        data: {
          agreementId: selectedAgreementId,
          assessmentType: form.assessmentType,
          quarter: form.assessmentType === "quarterly" ? form.quarter : undefined,
          kpiScore: form.kpiScore,
          competencyScore: form.competencyScore,
          comments: form.comments || undefined,
          developmentNeeds: form.developmentNeeds || undefined,
        },
      });
      toast({ title: "Assessment created" });
      setShowCreate(false);
      refetch();
    } catch (e: unknown) {
      toast({ title: "Error", description: getErrorMessage(e), variant: "destructive" });
    }
  };

  const handleModerate = async () => {
    if (!selectedAgreementId || !modForm.assessmentId) return;
    try {
      await createModeration.mutateAsync({
        data: {
          assessmentId: modForm.assessmentId,
          agreementId: selectedAgreementId,
          outcome: modForm.outcome,
          originalScore: modForm.originalScore,
          adjustedScore: modForm.outcome === "adjusted" ? modForm.adjustedScore : undefined,
          adjustmentReason: modForm.adjustmentReason || undefined,
          notes: modForm.notes || undefined,
        },
      });
      toast({ title: "Moderation recorded" });
      setShowModerate(false);
      refetchMods();
    } catch (e: unknown) {
      toast({ title: "Error", description: getErrorMessage(e), variant: "destructive" });
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Individual Assessments</h1>
          <p className="text-slate-500 mt-1">Quarterly, mid-year, and annual performance assessments</p>
        </div>
        <div className="flex gap-3">
          <Select value={selectedCycleId ? String(selectedCycleId) : "all"} onValueChange={v => setSelectedCycleId(v === "all" ? undefined : Number(v))}>
            <SelectTrigger className="w-[200px]"><SelectValue placeholder="All cycles" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Cycles</SelectItem>
              {cycles?.map(c => <SelectItem key={c.id} value={String(c.id)}>{c.financialYearLabel}</SelectItem>)}
            </SelectContent>
          </Select>
          <Select value={selectedAgreementId ? String(selectedAgreementId) : "all"} onValueChange={v => setSelectedAgreementId(v === "all" ? undefined : Number(v))}>
            <SelectTrigger className="w-[250px]"><SelectValue placeholder="Select agreement" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Agreements</SelectItem>
              {agreements?.map(a => <SelectItem key={a.id} value={String(a.id)}>{a.employeeName} — {a.postTitle}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="flex gap-3">
        {selectedAgreementId && (
          <>
            <Button onClick={() => setShowCreate(true)}><Plus className="w-4 h-4 mr-1" /> New Assessment</Button>
            <Button variant="outline" onClick={() => setShowModerate(true)}><Scale className="w-4 h-4 mr-1" /> Moderate</Button>
          </>
        )}
      </div>

      <Card>
        <CardHeader><CardTitle className="text-lg flex items-center gap-2"><ClipboardCheck className="w-5 h-5" /> Assessment Records</CardTitle></CardHeader>
        <CardContent>
          {!assessments?.length ? (
            <p className="text-sm text-slate-400 text-center py-6">
              {selectedAgreementId ? "No assessments for this agreement" : "Select an agreement to view assessments"}
            </p>
          ) : (
            <table className="w-full text-sm">
              <thead><tr className="border-b text-slate-500"><th className="text-left py-2 px-2">Type</th><th className="text-left py-2 px-2">Quarter</th><th className="text-right py-2 px-2">KPI Score</th><th className="text-right py-2 px-2">Competency</th><th className="text-right py-2 px-2">Overall</th><th className="text-left py-2 px-2">Status</th></tr></thead>
              <tbody>
                {assessments.map(a => (
                  <tr key={a.id} className="border-b last:border-0 hover:bg-slate-50">
                    <td className="py-2 px-2">{TYPE_LABELS[a.assessmentType] || a.assessmentType}</td>
                    <td className="py-2 px-2">{a.quarter ? `Q${a.quarter}` : "—"}</td>
                    <td className="py-2 px-2 text-right font-medium">{a.kpiScore?.toFixed(1) ?? "—"}</td>
                    <td className="py-2 px-2 text-right font-medium">{a.competencyScore?.toFixed(1) ?? "—"}</td>
                    <td className="py-2 px-2 text-right font-bold">{a.overallScore?.toFixed(1) ?? "—"}</td>
                    <td className="py-2 px-2"><Badge variant="outline">{a.status}</Badge></td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </CardContent>
      </Card>

      {selectedAgreementId && moderations && moderations.length > 0 && (
        <Card>
          <CardHeader><CardTitle className="text-lg flex items-center gap-2"><Scale className="w-5 h-5" /> Moderation Records</CardTitle></CardHeader>
          <CardContent>
            <table className="w-full text-sm">
              <thead><tr className="border-b text-slate-500"><th className="text-left py-2 px-2">Assessment</th><th className="text-left py-2 px-2">Outcome</th><th className="text-right py-2 px-2">Original</th><th className="text-right py-2 px-2">Adjusted</th><th className="text-left py-2 px-2">Reason</th></tr></thead>
              <tbody>
                {moderations.map(m => (
                  <tr key={m.id} className="border-b last:border-0 hover:bg-slate-50">
                    <td className="py-2 px-2">Assessment #{m.assessmentId}</td>
                    <td className="py-2 px-2"><Badge className={m.outcome === "accepted" ? "bg-green-100 text-green-700" : m.outcome === "adjusted" ? "bg-yellow-100 text-yellow-700" : "bg-red-100 text-red-700"}>{m.outcome}</Badge></td>
                    <td className="py-2 px-2 text-right">{m.originalScore?.toFixed(1) ?? "—"}</td>
                    <td className="py-2 px-2 text-right font-medium">{m.adjustedScore?.toFixed(1) ?? "—"}</td>
                    <td className="py-2 px-2 text-sm text-slate-500">{m.adjustmentReason || "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </CardContent>
        </Card>
      )}

      <Dialog open={showCreate} onOpenChange={setShowCreate}>
        <DialogContent>
          <DialogHeader><DialogTitle>New Assessment</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Type</Label>
              <Select value={form.assessmentType} onValueChange={v => setForm(p => ({ ...p, assessmentType: v as "quarterly" | "mid-year" | "annual" }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="quarterly">Quarterly Review</SelectItem>
                  <SelectItem value="mid-year">Mid-Year Assessment</SelectItem>
                  <SelectItem value="annual">Annual Assessment</SelectItem>
                </SelectContent>
              </Select>
            </div>
            {form.assessmentType === "quarterly" && (
              <div><Label>Quarter</Label><Select value={String(form.quarter)} onValueChange={v => setForm(p => ({ ...p, quarter: Number(v) }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{[1,2,3,4].map(q => <SelectItem key={q} value={String(q)}>Q{q}</SelectItem>)}</SelectContent></Select></div>
            )}
            <div><Label>KPI Score (0-5)</Label><Input type="number" step="0.1" min="0" max="5" value={form.kpiScore} onChange={e => setForm(p => ({ ...p, kpiScore: Number(e.target.value) }))} /></div>
            <div><Label>Competency Score (0-5)</Label><Input type="number" step="0.1" min="0" max="5" value={form.competencyScore} onChange={e => setForm(p => ({ ...p, competencyScore: Number(e.target.value) }))} /></div>
            <div><Label>Comments</Label><Textarea value={form.comments} onChange={e => setForm(p => ({ ...p, comments: e.target.value }))} /></div>
            <div><Label>Development Needs</Label><Textarea value={form.developmentNeeds} onChange={e => setForm(p => ({ ...p, developmentNeeds: e.target.value }))} /></div>
          </div>
          <DialogFooter><Button onClick={handleCreate}>Create Assessment</Button></DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={showModerate} onOpenChange={setShowModerate}>
        <DialogContent>
          <DialogHeader><DialogTitle>Moderate Assessment</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Assessment</Label>
              <Select value={modForm.assessmentId ? String(modForm.assessmentId) : "none"} onValueChange={v => setModForm(p => ({ ...p, assessmentId: Number(v) }))}>
                <SelectTrigger><SelectValue placeholder="Select assessment" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">Select</SelectItem>
                  {assessments?.map(a => <SelectItem key={a.id} value={String(a.id)}>{TYPE_LABELS[a.assessmentType] || a.assessmentType} — Score: {a.overallScore?.toFixed(1)}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Outcome</Label>
              <Select value={modForm.outcome} onValueChange={v => setModForm(p => ({ ...p, outcome: v as "accepted" | "adjusted" | "referred" }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="accepted">Accepted</SelectItem>
                  <SelectItem value="adjusted">Adjusted</SelectItem>
                  <SelectItem value="referred">Referred</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div><Label>Original Score</Label><Input type="number" step="0.1" value={modForm.originalScore} onChange={e => setModForm(p => ({ ...p, originalScore: Number(e.target.value) }))} /></div>
            {modForm.outcome === "adjusted" && (
              <div><Label>Adjusted Score</Label><Input type="number" step="0.1" value={modForm.adjustedScore} onChange={e => setModForm(p => ({ ...p, adjustedScore: Number(e.target.value) }))} /></div>
            )}
            <div><Label>Reason</Label><Textarea value={modForm.adjustmentReason} onChange={e => setModForm(p => ({ ...p, adjustmentReason: e.target.value }))} /></div>
          </div>
          <DialogFooter><Button onClick={handleModerate}>Submit</Button></DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/individual/individual-assessment.component.ts
import { ChangeDetectionStrategy, Component, Inject, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { catchError, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { Cycle } from '@core/models/domain.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';

interface Agreement {
  id: number;
  employeeName: string;
  postTitle: string;
}

type AssessmentType = 'quarterly' | 'mid-year' | 'annual';

interface AssessmentRecord {
  id: number;
  agreementId: number;
  assessmentType: string;
  quarter: number | null;
  kpiScore: number | null;
  competencyScore: number | null;
  overallScore: number | null;
  status: string;
}

type ModerationOutcome = 'accepted' | 'adjusted' | 'referred';

interface ModerationRecord {
  id: number;
  assessmentId: number;
  agreementId: number;
  outcome: string;
  originalScore: number | null;
  adjustedScore: number | null;
  adjustmentReason: string | null;
}

interface AssessmentForm {
  assessmentType: AssessmentType;
  quarter: number;
  kpiScore: number;
  competencyScore: number;
  comments: string;
  developmentNeeds: string;
}

interface ModerationForm {
  assessmentId: number;
  outcome: ModerationOutcome;
  originalScore: number;
  adjustedScore: number;
  adjustmentReason: string;
}

const TYPE_LABELS: Record<string, string> = {
  quarterly: 'Quarterly Review',
  'mid-year': 'Mid-Year Assessment',
  annual: 'Annual Assessment',
};

// ─── New Assessment Dialog ──────────────────────────────────────────────────
@Component({
  selector: 'app-new-assessment-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  template: `
    <h2 mat-dialog-title>New Assessment</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline">
        <mat-label>Type</mat-label>
        <mat-select [(ngModel)]="form.assessmentType" name="type">
          <mat-option value="quarterly">Quarterly Review</mat-option>
          <mat-option value="mid-year">Mid-Year Assessment</mat-option>
          <mat-option value="annual">Annual Assessment</mat-option>
        </mat-select>
      </mat-form-field>
      <mat-form-field appearance="outline" *ngIf="form.assessmentType === 'quarterly'">
        <mat-label>Quarter</mat-label>
        <mat-select [(ngModel)]="form.quarter" name="q">
          <mat-option *ngFor="let q of [1,2,3,4]" [value]="q">Q{{ q }}</mat-option>
        </mat-select>
      </mat-form-field>
      <mat-form-field appearance="outline"><mat-label>KPI Score (0-5)</mat-label><input matInput type="number" step="0.1" min="0" max="5" [(ngModel)]="form.kpiScore" name="kpi" /></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Competency Score (0-5)</mat-label><input matInput type="number" step="0.1" min="0" max="5" [(ngModel)]="form.competencyScore" name="comp" /></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Comments</mat-label><textarea matInput rows="3" [(ngModel)]="form.comments" name="c"></textarea></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Development Needs</mat-label><textarea matInput rows="3" [(ngModel)]="form.developmentNeeds" name="d"></textarea></mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="primary" type="button" (click)="ref.close(form)">Create Assessment</button>
    </mat-dialog-actions>
  `,
  styles: [`.content { display:flex; flex-direction: column; gap: 4px; padding-top: 12px !important; min-width: 480px; } mat-form-field { width: 100%; }`],
})
export class NewAssessmentDialogComponent {
  form: AssessmentForm = { assessmentType: 'quarterly', quarter: 1, kpiScore: 0, competencyScore: 0, comments: '', developmentNeeds: '' };
  constructor(public ref: MatDialogRef<NewAssessmentDialogComponent, AssessmentForm | null>) {}
}

// ─── Moderate Dialog ────────────────────────────────────────────────────────
@Component({
  selector: 'app-moderate-assessment-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  template: `
    <h2 mat-dialog-title>Moderate Assessment</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline">
        <mat-label>Assessment</mat-label>
        <mat-select [(ngModel)]="form.assessmentId" name="a">
          <mat-option *ngFor="let a of data.assessments" [value]="a.id">{{ label(a.assessmentType) }} — Score: {{ a.overallScore?.toFixed(1) }}</mat-option>
        </mat-select>
      </mat-form-field>
      <mat-form-field appearance="outline">
        <mat-label>Outcome</mat-label>
        <mat-select [(ngModel)]="form.outcome" name="o">
          <mat-option value="accepted">Accepted</mat-option>
          <mat-option value="adjusted">Adjusted</mat-option>
          <mat-option value="referred">Referred</mat-option>
        </mat-select>
      </mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Original Score</mat-label><input matInput type="number" step="0.1" [(ngModel)]="form.originalScore" name="orig" /></mat-form-field>
      <mat-form-field appearance="outline" *ngIf="form.outcome === 'adjusted'"><mat-label>Adjusted Score</mat-label><input matInput type="number" step="0.1" [(ngModel)]="form.adjustedScore" name="adj" /></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Reason</mat-label><textarea matInput rows="3" [(ngModel)]="form.adjustmentReason" name="r"></textarea></mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="primary" type="button" [disabled]="!form.assessmentId" (click)="ref.close(form)">Submit</button>
    </mat-dialog-actions>
  `,
  styles: [`.content { display:flex; flex-direction: column; gap: 4px; padding-top: 12px !important; min-width: 480px; } mat-form-field { width: 100%; }`],
})
export class ModerateAssessmentDialogComponent {
  form: ModerationForm = { assessmentId: 0, outcome: 'accepted', originalScore: 0, adjustedScore: 0, adjustmentReason: '' };
  constructor(
    public ref: MatDialogRef<ModerateAssessmentDialogComponent, ModerationForm | null>,
    @Inject(MAT_DIALOG_DATA) public data: { assessments: AssessmentRecord[] },
  ) {}
  label(type: string): string { return TYPE_LABELS[type] ?? type; }
}

// ─── Main Page ──────────────────────────────────────────────────────────────
@Component({
  selector: 'app-individual-assessment',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatSelectModule,
    PageHeaderComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="plat-page">
      <app-page-header title="Individual Assessments" subtitle="Quarterly, mid-year, and annual performance assessments" icon="fact_check" tone="indigo">
        <mat-form-field appearance="outline" class="pick">
          <mat-label>Cycle</mat-label>
          <mat-select [ngModel]="cycleId()" (ngModelChange)="onCycle($event)">
            <mat-option [value]="null">All Cycles</mat-option>
            <mat-option *ngFor="let c of cycles()" [value]="c.id">{{ c.financialYearLabel }}</mat-option>
          </mat-select>
        </mat-form-field>
        <mat-form-field appearance="outline" class="pick wide">
          <mat-label>Agreement</mat-label>
          <mat-select [ngModel]="agreementId()" (ngModelChange)="onAgreement($event)">
            <mat-option [value]="null">All Agreements</mat-option>
            <mat-option *ngFor="let a of agreements()" [value]="a.id">{{ a.employeeName }} — {{ a.postTitle }}</mat-option>
          </mat-select>
        </mat-form-field>
      </app-page-header>

      <div class="toolbar" *ngIf="agreementId()">
        <button mat-flat-button color="primary" (click)="openCreate()"><mat-icon>add</mat-icon> New Assessment</button>
        <button mat-stroked-button (click)="openModerate()"><mat-icon>balance</mat-icon> Moderate</button>
      </div>

      <div class="plat-card">
        <h3 class="title"><mat-icon>fact_check</mat-icon> Assessment Records</h3>
        <p *ngIf="!assessments().length" class="empty">
          {{ agreementId() ? 'No assessments for this agreement' : 'Select an agreement to view assessments' }}
        </p>
        <table class="plat-table" *ngIf="assessments().length">
          <thead><tr><th>Type</th><th>Quarter</th><th class="num">KPI Score</th><th class="num">Competency</th><th class="num">Overall</th><th>Status</th></tr></thead>
          <tbody>
            <tr *ngFor="let a of assessments()">
              <td>{{ label(a.assessmentType) }}</td>
              <td>{{ a.quarter ? 'Q' + a.quarter : '—' }}</td>
              <td class="num bold">{{ a.kpiScore !== null ? a.kpiScore.toFixed(1) : '—' }}</td>
              <td class="num bold">{{ a.competencyScore !== null ? a.competencyScore.toFixed(1) : '—' }}</td>
              <td class="num strong">{{ a.overallScore !== null ? a.overallScore.toFixed(1) : '—' }}</td>
              <td><span class="chip outline">{{ a.status }}</span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="plat-card" *ngIf="agreementId() && moderations().length">
        <h3 class="title"><mat-icon>balance</mat-icon> Moderation Records</h3>
        <table class="plat-table">
          <thead><tr><th>Assessment</th><th>Outcome</th><th class="num">Original</th><th class="num">Adjusted</th><th>Reason</th></tr></thead>
          <tbody>
            <tr *ngFor="let m of moderations()">
              <td>Assessment #{{ m.assessmentId }}</td>
              <td><span class="chip" [style.background]="outcomeColor(m.outcome).bg" [style.color]="outcomeColor(m.outcome).fg">{{ m.outcome }}</span></td>
              <td class="num">{{ m.originalScore !== null ? m.originalScore.toFixed(1) : '—' }}</td>
              <td class="num bold">{{ m.adjustedScore !== null ? m.adjustedScore.toFixed(1) : '—' }}</td>
              <td class="sub">{{ m.adjustmentReason || '—' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  `,
  styles: [`
    .pick { width: 200px; margin-right: 8px; }
    .pick.wide { width: 250px; }
    .toolbar { display: flex; gap: 12px; margin-bottom: 16px; }
    .plat-card { padding: 16px; margin-bottom: 16px; }
    .title { display: flex; align-items: center; gap: 8px; margin: 0 0 12px; font-size: 15px; font-weight: 600; }
    .empty { text-align: center; color: #94a3b8; padding: 24px 0; font-size: 13px; }
    .num { text-align: right; }
    .bold { font-weight: 500; }
    .strong { font-weight: 700; }
    .sub { font-size: 13px; color: #64748b; }
    .chip { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 12px; font-weight: 500; }
    .chip.outline { background: transparent; border: 1px solid var(--plat-border); color: #475569; }
  `],
})
export class IndividualAssessmentComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  private readonly dialog = inject(MatDialog);

  cycles = signal<Cycle[]>([]);
  agreements = signal<Agreement[]>([]);
  assessments = signal<AssessmentRecord[]>([]);
  moderations = signal<ModerationRecord[]>([]);
  cycleId = signal<number | null>(null);
  agreementId = signal<number | null>(null);

  label(type: string): string { return TYPE_LABELS[type] ?? type; }

  outcomeColor(outcome: string): { bg: string; fg: string } {
    if (outcome === 'accepted') return { bg: '#dcfce7', fg: '#15803d' };
    if (outcome === 'adjusted') return { bg: '#fef9c3', fg: '#a16207' };
    return { bg: '#fee2e2', fg: '#b91c1c' };
  }

  ngOnInit() {
    this.api.get<Cycle[]>('/cycles').pipe(catchError(() => of([] as Cycle[])))
      .subscribe((cs) => this.cycles.set(Array.isArray(cs) ? cs : []));
    this.loadAgreements();
  }

  onCycle(id: number | null) { this.cycleId.set(id); this.loadAgreements(); }
  onAgreement(id: number | null) { this.agreementId.set(id); this.loadAssessments(); this.loadModerations(); }

  loadAgreements() {
    this.api.get<Agreement[]>('/agreements', { cycleId: this.cycleId() ?? undefined })
      .pipe(catchError(() => of([] as Agreement[])))
      .subscribe((r) => this.agreements.set(Array.isArray(r) ? r : []));
  }

  loadAssessments() {
    const id = this.agreementId();
    if (!id) { this.assessments.set([]); return; }
    this.api.get<AssessmentRecord[]>('/individual-assessments', { agreementId: id })
      .pipe(catchError(() => of([] as AssessmentRecord[])))
      .subscribe((r) => this.assessments.set(Array.isArray(r) ? r : []));
  }

  loadModerations() {
    const id = this.agreementId();
    if (!id) { this.moderations.set([]); return; }
    this.api.get<ModerationRecord[]>('/individual-moderations', { agreementId: id })
      .pipe(catchError(() => of([] as ModerationRecord[])))
      .subscribe((r) => this.moderations.set(Array.isArray(r) ? r : []));
  }

  openCreate() {
    const agreementId = this.agreementId();
    if (!agreementId) return;
    this.dialog.open(NewAssessmentDialogComponent, { panelClass: 'plat-dialog', autoFocus: false })
      .afterClosed().subscribe((res: AssessmentForm | undefined) => {
        if (!res) return;
        this.api.post<AssessmentRecord>('/individual-assessments', {
          agreementId,
          assessmentType: res.assessmentType,
          quarter: res.assessmentType === 'quarterly' ? res.quarter : undefined,
          kpiScore: res.kpiScore,
          competencyScore: res.competencyScore,
          comments: res.comments || undefined,
          developmentNeeds: res.developmentNeeds || undefined,
        }).pipe(
          tap(() => { this.toast.success('Assessment created'); this.loadAssessments(); }),
          catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? e?.message); return of(null); }),
        ).subscribe();
      });
  }

  openModerate() {
    const agreementId = this.agreementId();
    if (!agreementId) return;
    this.dialog.open(ModerateAssessmentDialogComponent, { panelClass: 'plat-dialog', autoFocus: false, data: { assessments: this.assessments() } })
      .afterClosed().subscribe((res: ModerationForm | undefined) => {
        if (!res || !res.assessmentId) return;
        this.api.post<ModerationRecord>('/individual-moderations', {
          assessmentId: res.assessmentId,
          agreementId,
          outcome: res.outcome,
          originalScore: res.originalScore,
          adjustedScore: res.outcome === 'adjusted' ? res.adjustedScore : undefined,
          adjustmentReason: res.adjustmentReason || undefined,
        }).pipe(
          tap(() => { this.toast.success('Moderation recorded'); this.loadModerations(); }),
          catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? e?.message); return of(null); }),
        ).subscribe();
      });
  }
}
