// Insight-Performance-Hub/artifacts/perf-app/src/features/scorecards/ReviseSdbipApprove.tsx
import { useState } from "react";
import {
  useListScorecards, useTransitionScorecard,
  useListScorecardKpis, useTransitionScorecardKpi,
  useListQuarterTargets, useListCycles, useListUsers,
} from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { useToast } from "@/core/hooks/use-toast";
import {
  CheckCircle2, XCircle, ArrowLeft, FileSearch, Eye,
  Loader2, ShieldCheck, Award,
} from "lucide-react";

const STATUS_COLORS: Record<string, string> = {
  Draft: "bg-gray-100 text-gray-700",
  Submitted: "bg-blue-100 text-blue-700",
  Reviewed: "bg-amber-100 text-amber-700",
  Approved: "bg-green-100 text-green-700",
};

export default function ReviseSdbipApprove() {
  const { toast } = useToast();
  const { data: cycles } = useListCycles();
  const { data: users } = useListUsers();
  const [selectedCycleId, setSelectedCycleId] = useState<number | undefined>();
  const [selectedScorecardId, setSelectedScorecardId] = useState<number | undefined>();
  const [approvalComments, setApprovalComments] = useState("");
  const [showReturnDialog, setShowReturnDialog] = useState(false);
  const [returnReason, setReturnReason] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);

  const effectiveCycleId = selectedCycleId || cycles?.[0]?.id;
  const { data: allScorecards, refetch: refetchScorecards } = useListScorecards({ cycleId: effectiveCycleId });
  const kpisQuery = useListScorecardKpis(selectedScorecardId ?? 0);
  const kpis = selectedScorecardId ? kpisQuery.data : undefined;

  const scorecards = allScorecards?.filter(s => s.status === "Reviewed" && s.approvedAt) ?? [];
  const selectedScorecard = allScorecards?.find(s => s.id === selectedScorecardId);

  const transitionScorecard = useTransitionScorecard();
  const transitionKpi = useTransitionScorecardKpi();

  const getUserName = (id: number | null) => {
    if (!id) return "—";
    const u = users?.find(u => u.id === id);
    return u ? u.displayName : `User #${id}`;
  };

  const handleApproveKpi = async (kpiId: number) => {
    setIsProcessing(true);
    try {
      await transitionKpi.mutateAsync({ id: kpiId, data: { action: "approve", comments: "" } });
      toast({ title: "KPI Approved" });
      kpisQuery.refetch();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to approve KPI", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleApproveAllKpis = async () => {
    if (!kpis) return;
    setIsProcessing(true);
    try {
      const unapproved = kpis.filter(k => k.status === "Reviewed");
      for (const kpi of unapproved) {
        await transitionKpi.mutateAsync({ id: kpi.id, data: { action: "approve", comments: "" } });
      }
      toast({ title: `${unapproved.length} KPI(s) approved` });
      kpisQuery.refetch();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to approve KPIs", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleApproveScorecard = async () => {
    if (!selectedScorecardId) return;
    setIsProcessing(true);
    try {
      await transitionScorecard.mutateAsync({ id: selectedScorecardId, data: { action: "approve", comments: approvalComments } });
      toast({ title: "Revised SDBIP Approved", description: "The revised scorecard has been approved. New targets are now baselined." });
      setSelectedScorecardId(undefined);
      setApprovalComments("");
      refetchScorecards();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to approve", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleReturnScorecard = async () => {
    if (!selectedScorecardId) return;
    setIsProcessing(true);
    try {
      await transitionScorecard.mutateAsync({ id: selectedScorecardId, data: { action: "return", comments: returnReason } });
      toast({ title: "Revised SDBIP returned to Draft" });
      setSelectedScorecardId(undefined);
      setReturnReason("");
      setShowReturnDialog(false);
      refetchScorecards();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to return", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const approvedKpis = kpis?.filter(k => k.status === "Approved") ?? [];
  const reviewedKpis = kpis?.filter(k => k.status === "Reviewed") ?? [];
  const allKpisApproved = kpis && kpis.length > 0 && kpis.every(k => k.status === "Approved");

  if (selectedScorecardId && selectedScorecard) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => { setSelectedScorecardId(undefined); setApprovalComments(""); }}>
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Queue
          </Button>
          <div className="flex-1">
            <h1 className="text-2xl font-bold text-slate-800">Approve Revised: {selectedScorecard.name}</h1>
            <p className="text-slate-500">
              <Badge className="bg-amber-100 text-amber-700 mr-2">Mid-Year Revision</Badge>
              Status: <Badge className={STATUS_COLORS[selectedScorecard.status]}>{selectedScorecard.status}</Badge>
            </p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-4">
          <Card><CardContent className="pt-4"><div className="text-sm text-slate-500">Total KPIs</div><div className="text-2xl font-bold">{kpis?.length ?? 0}</div></CardContent></Card>
          <Card><CardContent className="pt-4"><div className="text-sm text-slate-500">Approved</div><div className="text-2xl font-bold text-green-600">{approvedKpis.length}</div></CardContent></Card>
          <Card><CardContent className="pt-4"><div className="text-sm text-slate-500">Pending Approval</div><div className="text-2xl font-bold text-amber-600">{reviewedKpis.length}</div></CardContent></Card>
        </div>

        {reviewedKpis.length > 0 && (
          <div className="flex justify-end">
            <Button onClick={handleApproveAllKpis} disabled={isProcessing} className="bg-green-600 hover:bg-green-700">
              {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <CheckCircle2 className="w-4 h-4 mr-2" />}
              Approve All Reviewed KPIs ({reviewedKpis.length})
            </Button>
          </div>
        )}

        <Card>
          <CardHeader>
            <CardTitle>Revised KPI Approval</CardTitle>
            <CardDescription>Review baseline changes and approve each revised KPI.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {kpis?.map(kpi => (
                <RevisionKpiApprovalCard
                  key={kpi.id}
                  kpi={kpi}
                  onApprove={() => handleApproveKpi(kpi.id)}
                  isProcessing={isProcessing}
                  getUserName={getUserName}
                />
              ))}
              {(!kpis || kpis.length === 0) && <p className="text-center text-slate-400 py-8">No KPIs found.</p>}
            </div>
          </CardContent>
        </Card>

        <Card className="border-green-200 bg-green-50/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-green-600" /> Final Revised SDBIP Approval</CardTitle>
            <CardDescription>
              {allKpisApproved
                ? "All revised KPIs approved. Approving the scorecard will update baselines with the new targets."
                : `${reviewedKpis.length} KPI(s) still pending approval.`}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Approval Comments (Optional)</Label>
              <Textarea value={approvalComments} onChange={e => setApprovalComments(e.target.value)} placeholder="Add approval comments..." rows={3} />
            </div>
            <div className="flex gap-3">
              <Button onClick={handleApproveScorecard} disabled={!allKpisApproved || isProcessing} className="bg-green-600 hover:bg-green-700">
                {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Award className="w-4 h-4 mr-2" />} Approve Revised SDBIP
              </Button>
              <Button variant="outline" onClick={() => setShowReturnDialog(true)} disabled={isProcessing} className="border-red-300 text-red-600 hover:bg-red-50">
                <XCircle className="w-4 h-4 mr-2" /> Return to Draft
              </Button>
            </div>
          </CardContent>
        </Card>

        <Dialog open={showReturnDialog} onOpenChange={setShowReturnDialog}>
          <DialogContent>
            <DialogHeader><DialogTitle>Return Revised Scorecard to Draft</DialogTitle></DialogHeader>
            <div className="space-y-4">
              <Label>Reason for Return *</Label>
              <Textarea value={returnReason} onChange={e => setReturnReason(e.target.value)} placeholder="Explain what needs correction..." rows={4} />
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowReturnDialog(false)}>Cancel</Button>
              <Button onClick={handleReturnScorecard} disabled={!returnReason.trim() || isProcessing} className="bg-red-600 hover:bg-red-700">
                {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <XCircle className="w-4 h-4 mr-2" />} Return to Draft
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800">Approve Revised SDBIP</h1>
        <p className="text-slate-500 mt-1">Approve revised scorecards to finalize the mid-year SDBIP revision. New targets will be baselined upon approval.</p>
      </div>
      <div className="flex items-center gap-4">
        <div className="w-64">
          <Label>Performance Cycle</Label>
          <Select value={String(effectiveCycleId ?? "")} onValueChange={v => setSelectedCycleId(Number(v))}>
            <SelectTrigger><SelectValue placeholder="Select cycle" /></SelectTrigger>
            <SelectContent>{cycles?.map(c => <SelectItem key={c.id} value={String(c.id)}>{c.financialYearLabel}</SelectItem>)}</SelectContent>
          </Select>
        </div>
      </div>
      {scorecards.length === 0 ? (
        <Card><CardContent className="py-16 text-center">
          <FileSearch className="w-12 h-12 text-slate-300 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-slate-600">No Revised Scorecards Pending Approval</h3>
          <p className="text-slate-400 mt-1">Reviewed revised scorecards will appear here.</p>
        </CardContent></Card>
      ) : (
        <div className="grid gap-4">
          {scorecards.map(sc => (
            <Card key={sc.id} className="hover:shadow-md transition-shadow cursor-pointer" onClick={() => setSelectedScorecardId(sc.id)}>
              <CardContent className="py-4 flex items-center justify-between">
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold text-slate-800">{sc.name}</h3>
                    <Badge className="bg-amber-100 text-amber-700 text-xs">Revised</Badge>
                  </div>
                  <p className="text-sm text-slate-500">Originally approved {new Date(sc.approvedAt!).toLocaleDateString()} · Created by {getUserName(sc.createdById)}</p>
                </div>
                <div className="flex items-center gap-3">
                  <Badge className={STATUS_COLORS[sc.status]}>{sc.status}</Badge>
                  <Button size="sm" variant="outline" className="border-green-300 text-green-700 hover:bg-green-50">
                    <ShieldCheck className="w-4 h-4 mr-1" /> Approve
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function RevisionKpiApprovalCard({ kpi, onApprove, isProcessing, getUserName }: {
  kpi: any; onApprove: () => void; isProcessing: boolean; getUserName: (id: number | null) => string;
}) {
  const [expanded, setExpanded] = useState(false);
  const targetsQuery = useListQuarterTargets(expanded ? kpi.id : 0);
  const targets = expanded ? targetsQuery.data : undefined;

  return (
    <div className="border rounded-lg p-4 space-y-3">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className="font-mono text-sm text-slate-500">{kpi.kpiNumber}</span>
            <Badge className={STATUS_COLORS[kpi.status]}>{kpi.status}</Badge>
          </div>
          <p className="font-medium text-slate-800 mt-1">{kpi.description}</p>
          <div className="flex gap-6 mt-2 text-sm text-slate-500">
            <span>Weight: {kpi.weighting}%</span>
            <span>Annual Target: {kpi.annualTarget}</span>
            <span>Responsible: {getUserName(kpi.responsiblePostId)}</span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {kpi.status === "Reviewed" && (
            <Button size="sm" onClick={onApprove} disabled={isProcessing} className="bg-green-600 hover:bg-green-700">
              <CheckCircle2 className="w-3 h-3 mr-1" /> Approve
            </Button>
          )}
          {kpi.status === "Approved" && <span className="flex items-center gap-1 text-sm text-green-600"><CheckCircle2 className="w-4 h-4" /> Approved</span>}
          <Button variant="ghost" size="sm" onClick={() => setExpanded(!expanded)}>{expanded ? "Collapse" : "Details"}</Button>
        </div>
      </div>

      {expanded && targets && targets.length > 0 && (
        <div className="pt-2 border-t">
          <div className="grid grid-cols-4 gap-2">
            {[1, 2, 3, 4].map(q => {
              const t = targets.find((t: any) => t.quarter === q);
              const hasRevision = t?.isApprovedBaseline && t?.baselineTargetValue && t.targetValue !== t.baselineTargetValue;
              return (
                <div key={q} className={`rounded p-2 text-sm ${hasRevision ? "bg-amber-50 border border-amber-200" : "bg-slate-50"}`}>
                  <div className="font-medium text-slate-600">Q{q}</div>
                  <div className="text-slate-800">{t?.targetValue ?? "—"}</div>
                  {hasRevision && (
                    <>
                      <div className="text-xs text-slate-400 line-through">Was: {t.baselineTargetValue}</div>
                      {t.revisionReason && <div className="text-xs text-amber-700 mt-1">Reason: {t.revisionReason}</div>}
                    </>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/revised-sdbip/revise-sdbip-approve.component.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { catchError, finalize, forkJoin, of } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { Cycle, KpiQuarterTarget, Scorecard, ScorecardKpi } from '@core/models/domain.model';
import { User } from '@core/models/user.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';

const STATUS_TONE: Record<string, string> = {
  Draft: 'tone-slate',
  Submitted: 'tone-blue',
  Reviewed: 'tone-amber',
  Approved: 'tone-green',
};

interface QuarterTarget extends KpiQuarterTarget {
  baselineTargetValue?: string | null;
  revisionReason?: string | null;
}

// ─── Return reason dialog ──────────────────────────────────────────────────
@Component({
  selector: 'app-approve-return-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>Return Revised Scorecard to Draft</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline">
        <mat-label>Reason for Return *</mat-label>
        <textarea matInput rows="4" [(ngModel)]="reason" name="r" placeholder="Explain what needs correction..."></textarea>
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="warn" type="button" [disabled]="!reason.trim()" (click)="ref.close(reason.trim())">Return to Draft</button>
    </mat-dialog-actions>
  `,
  styles: [`.content { min-width: 480px; padding-top: 12px !important; } mat-form-field { width: 100%; }`],
})
export class ApproveReturnDialogComponent {
  reason = '';
  constructor(public ref: MatDialogRef<ApproveReturnDialogComponent, string | null>) {}
}

// ─── KPI approval card (lazy-loads quarter targets on expand) ───────────────
@Component({
  selector: 'app-revision-kpi-approval-card',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="review-card">
      <div class="rc-head">
        <div class="rc-main">
          <div class="rc-tags">
            <span class="rc-num">{{ kpi().kpiNumber }}</span>
            <span class="badge" [ngClass]="statusTone[kpi().status] || 'tone-slate'">{{ kpi().status }}</span>
          </div>
          <p class="rc-desc">{{ kpi().description }}</p>
          <div class="rc-meta">
            <span>Weight: {{ kpi().weighting }}%</span>
            <span>Annual Target: {{ kpi().annualTarget }}</span>
            <span>Responsible: {{ responsibleName() }}</span>
          </div>
        </div>
        <div class="rc-actions">
          <button mat-flat-button color="primary" type="button" *ngIf="kpi().status === 'Reviewed'" [disabled]="processing()" (click)="approve.emit()">
            <mat-icon>check_circle</mat-icon> Approve
          </button>
          <span class="status-ok green" *ngIf="kpi().status === 'Approved'"><mat-icon>check_circle</mat-icon> Approved</span>
          <button mat-button type="button" (click)="toggle()">{{ expanded() ? 'Collapse' : 'Details' }}</button>
        </div>
      </div>

      <div class="rc-expand" *ngIf="expanded() && targets().length">
        <div class="target-grid">
          <div *ngFor="let q of [1,2,3,4]" class="tg" [class.rev]="hasRevision(q)">
            <div class="q">Q{{ q }}</div>
            <div class="val">{{ targetFor(q)?.targetValue ?? '—' }}</div>
            <ng-container *ngIf="hasRevision(q)">
              <div class="was">Was: {{ targetFor(q)?.baselineTargetValue }}</div>
              <div class="reason" *ngIf="targetFor(q)?.revisionReason">Reason: {{ targetFor(q)?.revisionReason }}</div>
            </ng-container>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./revised-sdbip.shared.scss'],
})
export class RevisionKpiApprovalCardComponent {
  private readonly api = inject(ApiService);
  readonly statusTone = STATUS_TONE;

  kpi = input.required<ScorecardKpi>();
  responsibleName = input<string>('—');
  processing = input<boolean>(false);

  expanded = signal(false);
  targets = signal<QuarterTarget[]>([]);

  approve = output<void>();

  toggle() {
    const next = !this.expanded();
    this.expanded.set(next);
    if (next && !this.targets().length) {
      this.api.get<QuarterTarget[]>(`/scorecard-kpis/${this.kpi().id}/quarter-targets`).pipe(
        catchError(() => of([] as QuarterTarget[])),
      ).subscribe((r) => this.targets.set(Array.isArray(r) ? r : []));
    }
  }

  targetFor(q: number): QuarterTarget | undefined {
    return this.targets().find((t) => t.quarter === q);
  }

  hasRevision(q: number): boolean {
    const t = this.targetFor(q);
    return !!(t?.isApprovedBaseline && t?.baselineTargetValue && t.targetValue !== t.baselineTargetValue);
  }
}

// ─── Main Approve Page ─────────────────────────────────────────────────────
@Component({
  selector: 'app-revise-sdbip-approve',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule, MatSelectModule,
    PageHeaderComponent, RevisionKpiApprovalCardComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './revise-sdbip-approve.component.html',
  styleUrls: ['./revised-sdbip.shared.scss'],
})
export class ReviseSdbipApproveComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  private readonly dialog = inject(MatDialog);

  readonly statusTone = STATUS_TONE;

  cycles = signal<Cycle[]>([]);
  users = signal<User[]>([]);
  allScorecards = signal<Scorecard[]>([]);
  kpis = signal<ScorecardKpi[]>([]);

  selectedCycleId = signal<number | null>(null);
  selectedScorecardId = signal<number | null>(null);
  approvalComments = signal('');
  processing = signal(false);

  effectiveCycleId = computed<number | null>(() => this.selectedCycleId() ?? this.cycles()[0]?.id ?? null);

  scorecards = computed<Scorecard[]>(() =>
    this.allScorecards().filter((s) => s.scorecardType === 'revised' && s.status === 'Reviewed'));

  selectedScorecard = computed<Scorecard | undefined>(() =>
    this.allScorecards().find((s) => s.id === this.selectedScorecardId()));

  approvedKpis = computed<ScorecardKpi[]>(() => this.kpis().filter((k) => k.status === 'Approved'));
  reviewedKpis = computed<ScorecardKpi[]>(() => this.kpis().filter((k) => k.status === 'Reviewed'));
  allKpisApproved = computed<boolean>(() => this.kpis().length > 0 && this.kpis().every((k) => k.status === 'Approved'));

  ngOnInit() {
    forkJoin({
      cycles: this.api.get<Cycle[]>('/cycles').pipe(catchError(() => of([] as Cycle[]))),
      users: this.api.get<User[]>('/auth/users').pipe(catchError(() => of([] as User[]))),
    }).subscribe(({ cycles, users }) => {
      this.cycles.set(Array.isArray(cycles) ? cycles : []);
      this.users.set(Array.isArray(users) ? users : []);
      this.loadScorecards();
    });
  }

  onCycle(id: number) {
    this.selectedCycleId.set(id);
    this.loadScorecards();
  }

  loadScorecards() {
    const cycleId = this.effectiveCycleId();
    if (!cycleId) { this.allScorecards.set([]); return; }
    this.api.get<Scorecard[]>('/scorecards', { cycleId }).pipe(
      catchError(() => of([] as Scorecard[])),
    ).subscribe((r) => this.allScorecards.set(Array.isArray(r) ? r : []));
  }

  loadKpis(scorecardId: number) {
    this.api.get<ScorecardKpi[]>(`/scorecards/${scorecardId}/kpis`).pipe(
      catchError(() => of([] as ScorecardKpi[])),
    ).subscribe((r) => this.kpis.set(Array.isArray(r) ? r : []));
  }

  getUserName(id: number | null | undefined): string {
    if (!id) return '—';
    const u = this.users().find((x) => x.id === id);
    return u ? u.displayName : `User #${id}`;
  }

  openScorecard(sc: Scorecard) {
    this.selectedScorecardId.set(sc.id);
    this.approvalComments.set('');
    this.loadKpis(sc.id);
  }

  back() {
    this.selectedScorecardId.set(null);
    this.approvalComments.set('');
    this.loadScorecards();
  }

  approveKpi(kpiId: number) {
    this.processing.set(true);
    this.api.post(`/scorecard-kpis/${kpiId}/transition`, { action: 'approve', comments: '' }).pipe(
      catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? 'Failed to approve KPI'); return of(null); }),
      finalize(() => this.processing.set(false)),
    ).subscribe((res) => {
      if (res !== null) {
        this.toast.success('KPI Approved');
        const id = this.selectedScorecardId();
        if (id) this.loadKpis(id);
      }
    });
  }

  approveAllKpis() {
    const unapproved = this.reviewedKpis();
    if (!unapproved.length) return;
    this.processing.set(true);
    forkJoin(unapproved.map((k) => this.api.post(`/scorecard-kpis/${k.id}/transition`, { action: 'approve', comments: '' }))).pipe(
      catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? 'Failed to approve KPIs'); return of(null); }),
      finalize(() => this.processing.set(false)),
    ).subscribe((res) => {
      if (res !== null) {
        this.toast.success(`${unapproved.length} KPI(s) approved`);
        const id = this.selectedScorecardId();
        if (id) this.loadKpis(id);
      }
    });
  }

  approveScorecard() {
    const id = this.selectedScorecardId();
    if (!id) return;
    this.processing.set(true);
    this.api.post(`/scorecards/${id}/transition`, { action: 'approve', comments: this.approvalComments() }).pipe(
      catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? 'Failed to approve'); return of(null); }),
      finalize(() => this.processing.set(false)),
    ).subscribe((res) => {
      if (res !== null) {
        this.toast.success('Revised SDBIP Approved', 'The revised scorecard has been approved. New targets are now baselined.');
        this.back();
      }
    });
  }

  openReturnDialog() {
    this.dialog.open(ApproveReturnDialogComponent, { panelClass: 'plat-dialog', autoFocus: true })
      .afterClosed().subscribe((reason) => { if (reason) this.returnScorecard(reason); });
  }

  private returnScorecard(reason: string) {
    const id = this.selectedScorecardId();
    if (!id) return;
    this.processing.set(true);
    this.api.post(`/scorecards/${id}/transition`, { action: 'return', comments: reason }).pipe(
      catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? 'Failed to return'); return of(null); }),
      finalize(() => this.processing.set(false)),
    ).subscribe((res) => {
      if (res !== null) { this.toast.success('Revised SDBIP returned to Draft'); this.back(); }
    });
  }

  trackById(_: number, x: { id: number }): number { return x.id; }
}

<!-- ── Approve Detail View ───────────────────────────────────────────────── -->
<section class="plat-page" *ngIf="selectedScorecardId() && selectedScorecard() as sc; else listView">
  <div class="detail-head">
    <div class="left">
      <button mat-button type="button" (click)="back()"><mat-icon>arrow_back</mat-icon> Back to Queue</button>
      <div>
        <h2 class="title">Approve Revised: {{ sc.name }}</h2>
        <p class="sub">
          <span class="badge tone-amber">Mid-Year Revision</span>
          Status: <span class="badge" [ngClass]="statusTone[sc.status] || 'tone-slate'">{{ sc.status }}</span>
        </p>
      </div>
    </div>
  </div>

  <div class="summary-grid">
    <div class="plat-card stat"><div class="lbl">Total KPIs</div><div class="val">{{ kpis().length }}</div></div>
    <div class="plat-card stat"><div class="lbl">Approved</div><div class="val green">{{ approvedKpis().length }}</div></div>
    <div class="plat-card stat"><div class="lbl">Pending Approval</div><div class="val amber">{{ reviewedKpis().length }}</div></div>
  </div>

  <div class="bulk-row" *ngIf="reviewedKpis().length">
    <button mat-flat-button color="primary" type="button" [disabled]="processing()" (click)="approveAllKpis()">
      <mat-icon>check_circle</mat-icon> Approve All Reviewed KPIs ({{ reviewedKpis().length }})
    </button>
  </div>

  <div class="plat-card">
    <h3 class="card-title">Revised KPI Approval</h3>
    <p class="card-desc">Review baseline changes and approve each revised KPI.</p>
    <div class="kpi-list">
      <app-revision-kpi-approval-card
        *ngFor="let kpi of kpis(); trackBy: trackById"
        [kpi]="kpi"
        [responsibleName]="getUserName(kpi.responsiblePostId)"
        [processing]="processing()"
        (approve)="approveKpi(kpi.id)">
      </app-revision-kpi-approval-card>
      <p class="empty-msg" *ngIf="!kpis().length">No KPIs found.</p>
    </div>
  </div>

  <div class="plat-card decision-card approve">
    <h3 class="card-title"><mat-icon class="inline-icon">verified_user</mat-icon> Final Revised SDBIP Approval</h3>
    <p class="card-desc">
      {{ allKpisApproved()
        ? 'All revised KPIs approved. Approving the scorecard will update baselines with the new targets.'
        : reviewedKpis().length + ' KPI(s) still pending approval.' }}
    </p>
    <mat-form-field appearance="outline">
      <mat-label>Approval Comments (Optional)</mat-label>
      <textarea matInput rows="3" [ngModel]="approvalComments()" (ngModelChange)="approvalComments.set($event)" placeholder="Add approval comments..."></textarea>
    </mat-form-field>
    <div class="dc-actions">
      <button mat-flat-button color="primary" type="button" [disabled]="!allKpisApproved() || processing()" (click)="approveScorecard()">
        <mat-icon>workspace_premium</mat-icon> Approve Revised SDBIP
      </button>
      <button mat-stroked-button color="warn" type="button" [disabled]="processing()" (click)="openReturnDialog()">
        <mat-icon>cancel</mat-icon> Return to Draft
      </button>
    </div>
  </div>
</section>

<!-- ── Queue List View ───────────────────────────────────────────────────── -->
<ng-template #listView>
  <section class="plat-page">
    <app-page-header title="Approve Revised SDBIP" subtitle="Approve revised scorecards to finalize the mid-year SDBIP revision. New targets will be baselined upon approval." icon="verified" tone="green">
      <mat-form-field appearance="outline" class="cycle-pick">
        <mat-label>Performance Cycle</mat-label>
        <mat-select [ngModel]="effectiveCycleId()" (ngModelChange)="onCycle($event)">
          <mat-option *ngFor="let c of cycles()" [value]="c.id">{{ c.financialYearLabel }}</mat-option>
        </mat-select>
      </mat-form-field>
    </app-page-header>

    <div class="plat-card empty-card" *ngIf="!scorecards().length">
      <mat-icon>find_in_page</mat-icon>
      <h3>No Revised Scorecards Pending Approval</h3>
      <p>Reviewed revised scorecards will appear here.</p>
    </div>

    <div class="list-cards" *ngIf="scorecards().length">
      <div *ngFor="let sc of scorecards(); trackBy: trackById" class="plat-card list-row" (click)="openScorecard(sc)">
        <div>
          <div class="lr-name">
            <h3>{{ sc.name }}</h3>
            <span class="badge tone-amber">Revised</span>
          </div>
          <p class="lr-meta">Revision of an approved SDBIP · Created {{ sc.createdAt | date:'mediumDate' }} by {{ getUserName(sc.createdById) }}</p>
        </div>
        <div class="lr-actions">
          <span class="badge" [ngClass]="statusTone[sc.status] || 'tone-slate'">{{ sc.status }}</span>
          <button mat-stroked-button type="button"><mat-icon>verified_user</mat-icon> Approve</button>
        </div>
      </div>
    </div>
  </section>
</ng-template>
