// Insight-Performance-Hub/artifacts/perf-app/src/pages/config/PerformanceCycles.tsx
import { useState } from "react";
import { useListCycles, useCreateCycle, useUpdateCycle, useDeleteCycle, type CreateCycleInput } from "@workspace/api-client-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/status-badge";
import { Plus, Pencil, Trash2, Loader2, Calendar as CalendarIcon } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { getListCyclesQueryKey } from "@workspace/api-client-react";
import { format } from "date-fns";
import { useToast } from "@/hooks/use-toast";

export default function PerformanceCycles() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const { data: cycles, isLoading } = useListCycles();
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [deletingCycle, setDeletingCycle] = useState<{ id: number; label: string } | null>(null);

  const deleteMut = useDeleteCycle({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListCyclesQueryKey() });
        toast({ title: "Cycle deleted successfully" });
        setDeletingCycle(null);
      },
      onError: (err: Error) => {
        toast({ title: "Error", description: err.message, variant: "destructive" });
      },
    },
  });

  if (isLoading) return <div className="flex p-8 justify-center"><Loader2 className="w-8 h-8 animate-spin text-platinum-primary" /></div>;

  return (
    <div className="space-y-6 animate-in fade-in">
      <div className="flex justify-between items-center bg-white p-6 rounded-2xl shadow-sm border border-border">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-3">
            <div className="p-2 bg-blue-50 text-blue-600 rounded-lg"><CalendarIcon className="w-6 h-6" /></div>
            Performance Cycles
          </h1>
          <p className="text-slate-500 mt-1">Manage financial years and performance periods.</p>
        </div>
        <CycleDialog open={isDialogOpen} onOpenChange={setIsDialogOpen} editingId={editingId} setEditingId={setEditingId} cycles={cycles} />
      </div>

      <Card className="platinum-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 uppercase bg-slate-50 border-b border-border font-semibold">
              <tr>
                <th className="px-6 py-4">Financial Year</th>
                <th className="px-6 py-4">Start Date</th>
                <th className="px-6 py-4">End Date</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {cycles?.length === 0 && (
                <tr><td colSpan={5} className="px-6 py-8 text-center text-slate-500">No cycles configured yet.</td></tr>
              )}
              {cycles?.map((cycle) => (
                <tr key={cycle.id} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-6 py-4 font-semibold text-slate-900">{cycle.financialYearLabel}</td>
                  <td className="px-6 py-4 text-slate-600">{format(new Date(cycle.startDate), 'dd MMM yyyy')}</td>
                  <td className="px-6 py-4 text-slate-600">{format(new Date(cycle.endDate), 'dd MMM yyyy')}</td>
                  <td className="px-6 py-4"><StatusBadge status={cycle.status} /></td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <Button 
                        variant="ghost" 
                        size="sm"
                        className="text-blue-600 hover:text-blue-800 hover:bg-blue-50"
                        onClick={() => {
                          setEditingId(cycle.id);
                          setIsDialogOpen(true);
                        }}
                      >
                        <Pencil className="w-4 h-4 mr-2" /> Edit
                      </Button>
                      {cycle.status === "Draft" && (
                        <Button 
                          variant="ghost" 
                          size="sm"
                          className="text-red-500 hover:text-red-700 hover:bg-red-50"
                          onClick={() => setDeletingCycle({ id: cycle.id, label: cycle.financialYearLabel })}
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <AlertDialog open={!!deletingCycle} onOpenChange={(v) => { if (!v) setDeletingCycle(null); }}>
        <AlertDialogContent className="rounded-2xl">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Performance Cycle</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete the cycle <strong>{deletingCycle?.label}</strong>? All linked scorecards, KPIs, actuals, and related records will also be permanently removed. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="rounded-xl">Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="rounded-xl bg-red-600 hover:bg-red-700 text-white"
              onClick={() => deletingCycle && deleteMut.mutate({ id: deletingCycle.id })}
              disabled={deleteMut.isPending}
            >
              {deleteMut.isPending && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

interface CycleDialogProps {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  editingId: number | null;
  setEditingId: (id: number | null) => void;
  cycles: { id: number; financialYearLabel: string; startDate: string; endDate: string; status: string }[] | undefined;
}

function CycleDialog({ open, onOpenChange, editingId, setEditingId, cycles }: CycleDialogProps) {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const createMut = useCreateCycle();
  const updateMut = useUpdateCycle();
  
  const cycle = editingId ? cycles?.find((c) => c.id === editingId) : null;
  const isPending = createMut.isPending || updateMut.isPending;

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const data = {
      financialYearLabel: fd.get("label") as string,
      startDate: fd.get("start") as string,
      endDate: fd.get("end") as string,
      status: fd.get("status") as string as CreateCycleInput["status"]
    };

    const onSuccess = () => {
      queryClient.invalidateQueries({ queryKey: getListCyclesQueryKey() });
      onOpenChange(false);
      setEditingId(null);
      toast({ title: `Cycle ${editingId ? 'updated' : 'created'} successfully` });
    };

    if (editingId) {
      updateMut.mutate({ id: editingId, data }, { onSuccess });
    } else {
      createMut.mutate({ data }, { onSuccess });
    }
  };

  return (
    <Dialog open={open} onOpenChange={(v) => { onOpenChange(v); if (!v) setEditingId(null); }}>
      <DialogTrigger asChild>
        <Button className="bg-platinum-primary hover:bg-platinum-primary-light shadow-md shadow-platinum-primary/20 transition-all rounded-xl px-6">
          <Plus className="w-4 h-4 mr-2" /> Add Cycle
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px] rounded-2xl">
        <DialogHeader>
          <DialogTitle className="text-xl text-platinum-primary">{editingId ? 'Edit Cycle' : 'Create Performance Cycle'}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Financial Year Label</label>
            <Input name="label" required defaultValue={cycle?.financialYearLabel} placeholder="e.g. 2024/2025" className="h-11 rounded-xl" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Start Date</label>
              <Input type="date" name="start" required defaultValue={cycle?.startDate?.split('T')[0]} className="h-11 rounded-xl" />
            </div>
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">End Date</label>
              <Input type="date" name="end" required defaultValue={cycle?.endDate?.split('T')[0]} className="h-11 rounded-xl" />
            </div>
          </div>
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Status</label>
            <Select name="status" defaultValue={cycle?.status || "Draft"}>
              <SelectTrigger className="h-11 rounded-xl">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Draft">Draft</SelectItem>
                <SelectItem value="Open">Open</SelectItem>
                <SelectItem value="Closed">Closed</SelectItem>
                <SelectItem value="Archived">Archived</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <DialogFooter className="pt-4">
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)} className="rounded-xl">Cancel</Button>
            <Button type="submit" disabled={isPending} className="rounded-xl bg-platinum-primary hover:bg-platinum-primary-light">
              {isPending && <Loader2 className="w-4 h-4 mr-2 animate-spin" />} Save Changes
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/config/performance-cycles.component.ts
import { ChangeDetectionStrategy, Component, Inject, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { catchError, finalize, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { ConfirmService } from '@core/services/confirm.service';
import { Cycle, CycleStatus } from '@core/models/domain.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';
import { StatusBadgeComponent } from '@shared/components/status-badge/status-badge.component';
import { LoadingSpinnerComponent } from '@shared/components/loading-spinner/loading-spinner.component';

interface CycleForm { financialYearLabel: string; startDate: string; endDate: string; status: CycleStatus; }

@Component({
  selector: 'app-cycle-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  template: `
    <h2 mat-dialog-title>{{ data.cycle ? 'Edit Cycle' : 'Create Performance Cycle' }}</h2>
    <form (ngSubmit)="save()" class="plat-form" #f="ngForm">
      <mat-dialog-content class="content">
        <mat-form-field appearance="outline">
          <mat-label>Financial Year Label</mat-label>
          <input matInput [(ngModel)]="model.financialYearLabel" name="label" required placeholder="e.g. 2025/2026" />
        </mat-form-field>
        <div class="grid">
          <mat-form-field appearance="outline">
            <mat-label>Start Date</mat-label>
            <input matInput type="date" [(ngModel)]="model.startDate" name="start" required />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>End Date</mat-label>
            <input matInput type="date" [(ngModel)]="model.endDate" name="end" required />
          </mat-form-field>
        </div>
        <mat-form-field appearance="outline">
          <mat-label>Status</mat-label>
          <mat-select [(ngModel)]="model.status" name="status">
            <mat-option value="Open">Open</mat-option>
            <mat-option value="Closed">Closed</mat-option>
            <mat-option value="Archived">Archived</mat-option>
          </mat-select>
        </mat-form-field>
      </mat-dialog-content>
      <mat-dialog-actions align="end">
        <button mat-button type="button" mat-dialog-close>Cancel</button>
        <button mat-flat-button color="primary" type="submit" [disabled]="saving() || f.invalid">{{ saving() ? 'Saving…' : 'Save Changes' }}</button>
      </mat-dialog-actions>
    </form>
  `,
  styles: [`.content { display: flex; flex-direction: column; gap: 4px; padding-top: 12px !important; min-width: 380px; } .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; } mat-form-field { width: 100%; }`],
})
export class CycleDialogComponent {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  saving = signal(false);
  model: CycleForm;
  constructor(
    public ref: MatDialogRef<CycleDialogComponent, Cycle | null>,
    @Inject(MAT_DIALOG_DATA) public data: { cycle: Cycle | null },
  ) {
    const c = data.cycle;
    this.model = {
      financialYearLabel: c?.financialYearLabel ?? '',
      startDate: c?.startDate?.split('T')[0] ?? '',
      endDate: c?.endDate?.split('T')[0] ?? '',
      status: c?.status && c.status !== 'Draft' ? c.status : 'Open',
    };
  }
  save() {
    this.saving.set(true);
    const id = this.data.cycle?.id;
    const obs = id
      ? this.api.patch<Cycle>(`/cycles/${id}`, this.model)
      : this.api.post<Cycle>(`/cycles`, this.model);
    obs.pipe(
      tap((res) => { this.toast.success(`Cycle ${id ? 'updated' : 'created'} successfully`); this.ref.close(res); }),
      catchError((e) => { this.toast.error('Save failed', e?.error?.message ?? e?.message ?? 'Unknown error'); return of(null); }),
      finalize(() => this.saving.set(false)),
    ).subscribe();
  }
}

@Component({
  selector: 'app-performance-cycles',
  standalone: true,
  imports: [CommonModule, DatePipe, MatButtonModule, MatIconModule, PageHeaderComponent, StatusBadgeComponent, LoadingSpinnerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="plat-page">
      <app-page-header title="Performance Cycles" subtitle="Manage financial years and performance periods." icon="event" tone="blue">
        <button mat-flat-button color="primary" (click)="openDialog(null)">
          <mat-icon>add</mat-icon> Add Cycle
        </button>
      </app-page-header>

      <div class="plat-card">
        <app-loading-spinner *ngIf="loading()"></app-loading-spinner>
        <table *ngIf="!loading()" class="plat-table">
          <thead><tr><th>Financial Year</th><th>Start Date</th><th>End Date</th><th>Status</th><th class="actions">Actions</th></tr></thead>
          <tbody>
            <tr *ngIf="cycles().length === 0"><td colspan="5" class="empty">No cycles configured yet.</td></tr>
            <tr *ngFor="let c of cycles()">
              <td><strong>{{ c.financialYearLabel }}</strong></td>
              <td>{{ c.startDate | date:'dd MMM yyyy' }}</td>
              <td>{{ c.endDate | date:'dd MMM yyyy' }}</td>
              <td><app-status-badge [status]="c.status"></app-status-badge></td>
              <td class="actions">
                <button mat-button color="primary" (click)="openDialog(c)"><mat-icon>edit</mat-icon> Edit</button>
                <button *ngIf="c.status === 'Draft'" mat-icon-button color="warn" (click)="confirmDelete(c)" aria-label="Delete">
                  <mat-icon>delete</mat-icon>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  `,
})
export class PerformanceCyclesComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly dialog = inject(MatDialog);
  private readonly toast = inject(ToastService);
  private readonly confirm = inject(ConfirmService);

  loading = signal(true);
  cycles = signal<Cycle[]>([]);

  ngOnInit() { this.load(); }
  load() {
    this.loading.set(true);
    this.api.get<Cycle[]>('/cycles').pipe(
      tap((rows) => this.cycles.set(Array.isArray(rows) ? rows : [])),
      catchError(() => { this.cycles.set([]); return of(null); }),
      finalize(() => this.loading.set(false)),
    ).subscribe();
  }
  openDialog(cycle: Cycle | null) {
    const ref = this.dialog.open(CycleDialogComponent, { data: { cycle }, panelClass: 'plat-dialog', autoFocus: false });
    ref.afterClosed().subscribe((res) => { if (res) this.load(); });
  }
  async confirmDelete(c: Cycle) {
    const ok = await this.confirm.confirm({
      title: 'Delete Performance Cycle',
      message: `Are you sure you want to delete "${c.financialYearLabel}"? All linked scorecards, KPIs, actuals, and related records will be permanently removed.`,
      destructive: true, confirmLabel: 'Delete',
    });
    if (!ok) return;
    this.api.delete(`/cycles/${c.id}`).pipe(
      tap(() => { this.toast.success('Cycle deleted successfully'); this.load(); }),
      catchError((e) => { this.toast.error('Delete failed', e?.error?.message ?? e?.message); return of(null); }),
    ).subscribe();
  }
}
