// libs/ins/src/lib/shared/components/status-badge/status-badge.component.ts
import { ChangeDetectionStrategy, Component, Input, computed, signal } from '@angular/core';

@Component({
  selector: 'app-status-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span class="badge" [class]="'badge--' + tone()">{{ label() || status }}</span>`,
  styles: [`
    .badge {
      display: inline-flex; align-items: center; padding: 2px 10px;
      border-radius: 999px; font-size: 11px; font-weight: 700; letter-spacing: .03em;
      text-transform: uppercase;
    }
    .badge--green   { background: #dcfce7; color: #166534; }
    .badge--blue    { background: #dbeafe; color: #1e40af; }
    .badge--amber   { background: #fef3c7; color: #92400e; }
    .badge--red     { background: #fee2e2; color: #991b1b; }
    .badge--slate   { background: #f1f5f9; color: #475569; }
    .badge--purple  { background: #f3e8ff; color: #6b21a8; }
  `],
})
export class StatusBadgeComponent {
  @Input() status: string = '';
  @Input() override?: 'green' | 'blue' | 'amber' | 'red' | 'slate' | 'purple';

  private readonly _status = signal<string>('');
  label = computed(() => this.status);
  tone = computed<'green'|'blue'|'amber'|'red'|'slate'|'purple'>(() => {
    if (this.override) return this.override;
    const s = (this.status || '').toLowerCase();
    if (['active', 'open', 'approved', 'achieved', 'verified', 'completed', 'success', 'on track', 'green'].some(k => s.includes(k))) return 'green';
    if (['draft', 'pending', 'submitted', 'in progress', 'review'].some(k => s.includes(k))) return 'blue';
    if (['at risk', 'warning', 'returned', 'overdue', 'amber', 'partial'].some(k => s.includes(k))) return 'amber';
    if (['rejected', 'failed', 'closed', 'inactive', 'archived', 'missed', 'red', 'destructive', 'error'].some(k => s.includes(k))) return s.includes('closed') || s.includes('archived') || s.includes('inactive') ? 'slate' : 'red';
    return 'slate';
  });
}

// Insight-Performance-Hub/artifacts/perf-app/src/components/ui/status-badge.tsx
import { cn } from "@/core/lib/utils";

type StatusBadgeProps = {
  status: string;
  className?: string;
};

export function StatusBadge({ status, className }: StatusBadgeProps) {
  const normalized = status.toLowerCase();
  
  let colors = "bg-slate-100 text-slate-600"; // default Draft
  
  if (["approved", "completed", "open", "active"].includes(normalized)) {
    colors = "bg-green-50 text-green-700 border-green-200/50";
  } else if (["submitted", "in progress"].includes(normalized)) {
    colors = "bg-blue-50 text-blue-700 border-blue-200/50";
  } else if (["pending", "review"].includes(normalized)) {
    colors = "bg-orange-50 text-orange-700 border-orange-200/50";
  } else if (["rejected", "cancelled", "closed", "archived"].includes(normalized)) {
    colors = "bg-red-50 text-red-700 border-red-200/50";
  } else if (["returned"].includes(normalized)) {
    colors = "bg-amber-50 text-amber-700 border-amber-200/50";
  }

  return (
    <span className={cn(
      "inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase tracking-wide border",
      colors,
      className
    )}>
      {status}
    </span>
  );
}
