// Insight-Performance-Hub/artifacts/perf-app/src/pages/actuals/CorrectiveActions.tsx
import { useState } from "react";
import {
  useListRemedialActions, useCreateRemedialAction, useUpdateRemedialAction
} from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { Plus, AlertTriangle, CheckCircle2, Clock, Pencil } from "lucide-react";

const STATUS_COLORS: Record<string, string> = {
  Open: "bg-red-100 text-red-700",
  "In Progress": "bg-amber-100 text-amber-700",
  Completed: "bg-green-100 text-green-700",
  Overdue: "bg-red-200 text-red-800",
};

export default function CorrectiveActions() {
  const { toast } = useToast();
  const [showNew, setShowNew] = useState(false);
  const [showEdit, setShowEdit] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [newForm, setNewForm] = useState({
    kpiId: 0, quarter: 1, actionDescription: "", dueDate: "", actionOwnerIds: "",
  });
  const [editForm, setEditForm] = useState({ actionDescription: "", dueDate: "", actionOwnerIds: "" });

  const { data: actions, refetch } = useListRemedialActions(
    statusFilter !== "all" ? { status: statusFilter } : {}
  );
  const createAction = useCreateRemedialAction();
  const updateAction = useUpdateRemedialAction();

  async function handleCreate() {
    if (!newForm.kpiId || !newForm.actionDescription || !newForm.dueDate) return;
    try {
      await createAction.mutateAsync({
        data: {
          kpiId: newForm.kpiId,
          quarter: newForm.quarter,
          actionDescription: newForm.actionDescription,
          dueDate: newForm.dueDate,
          actionOwnerIds: newForm.actionOwnerIds || undefined,
        }
      });
      setShowNew(false);
      setNewForm({ kpiId: 0, quarter: 1, actionDescription: "", dueDate: "", actionOwnerIds: "" });
      refetch();
      toast({ title: "Corrective action created" });
    } catch { toast({ title: "Error", variant: "destructive" }); }
  }

  async function handleUpdateStatus(id: number, status: string) {
    try {
      await updateAction.mutateAsync({ id, data: { status } });
      refetch();
      toast({ title: `Status updated to ${status}` });
    } catch { toast({ title: "Error", variant: "destructive" }); }
  }

  function openEdit(action: NonNullable<typeof actions>[number]) {
    setEditForm({
      actionDescription: action.actionDescription ?? "",
      dueDate: action.dueDate ?? "",
      actionOwnerIds: action.actionOwnerIds ?? "",
    });
    setEditingId(action.id);
    setShowEdit(true);
  }

  async function handleEdit() {
    if (!editingId || !editForm.actionDescription || !editForm.dueDate) return;
    try {
      await updateAction.mutateAsync({
        id: editingId,
        data: {
          actionDescription: editForm.actionDescription,
          dueDate: editForm.dueDate,
          actionOwnerIds: editForm.actionOwnerIds || undefined,
        }
      });
      setShowEdit(false);
      setEditingId(null);
      refetch();
      toast({ title: "Corrective action updated" });
    } catch { toast({ title: "Error", variant: "destructive" }); }
  }

  const overdueActions = actions?.filter(a => a.status !== "Completed" && new Date(a.dueDate) < new Date()) || [];

  return (
    <div className="space-y-6 animate-in fade-in-50 duration-300">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Corrective & Remedial Actions</h2>
          <p className="text-slate-500">Track corrective actions for underperforming KPIs</p>
        </div>
        <Button onClick={() => setShowNew(true)}><Plus className="w-4 h-4 mr-1" /> New Action</Button>
      </div>

      {overdueActions.length > 0 && (
        <Card className="bg-red-50 border-red-200">
          <CardContent className="p-4 flex items-center gap-3">
            <AlertTriangle className="w-6 h-6 text-red-600" />
            <div>
              <p className="font-semibold text-red-700">{overdueActions.length} Overdue Action{overdueActions.length > 1 ? 's' : ''}</p>
              <p className="text-sm text-red-600">Actions past their due date requiring attention</p>
            </div>
          </CardContent>
        </Card>
      )}

      <div className="flex gap-3">
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-48"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Statuses</SelectItem>
            <SelectItem value="Open">Open</SelectItem>
            <SelectItem value="In Progress">In Progress</SelectItem>
            <SelectItem value="Completed">Completed</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="space-y-3">
        {actions?.map(action => {
          const isOverdue = action.status !== "Completed" && new Date(action.dueDate) < new Date();
          return (
            <Card key={action.id} className={isOverdue ? "border-red-300" : ""}>
              <CardContent className="p-4">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <Badge className={isOverdue ? STATUS_COLORS.Overdue : STATUS_COLORS[action.status]}>
                        {isOverdue ? "Overdue" : action.status}
                      </Badge>
                      <Badge variant="outline">KPI #{action.kpiId}</Badge>
                      <Badge variant="outline">Q{action.quarter}</Badge>
                    </div>
                    <p className="font-medium text-slate-800">{action.actionDescription}</p>
                    <div className="flex gap-4 mt-2 text-xs text-slate-500">
                      <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> Due: {action.dueDate}</span>
                    </div>
                  </div>
                  <div className="flex gap-1">
                    {action.status !== "Completed" && (
                      <Button variant="ghost" size="sm" onClick={() => openEdit(action)}>
                        <Pencil className="w-4 h-4 mr-1" /> Edit
                      </Button>
                    )}
                    {action.status === "Open" && (
                      <Button variant="ghost" size="sm" onClick={() => handleUpdateStatus(action.id, "In Progress")}>Start</Button>
                    )}
                    {action.status === "In Progress" && (
                      <Button variant="ghost" size="sm" className="text-green-600" onClick={() => handleUpdateStatus(action.id, "Completed")}>
                        <CheckCircle2 className="w-4 h-4 mr-1" /> Complete
                      </Button>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
        {(!actions || actions.length === 0) && (
          <Card className="border-dashed">
            <CardContent className="p-8 text-center text-slate-500">
              <CheckCircle2 className="w-12 h-12 mx-auto mb-3 text-slate-300" />
              <p className="font-medium">No corrective actions</p>
            </CardContent>
          </Card>
        )}
      </div>

      <Dialog open={showNew} onOpenChange={setShowNew}>
        <DialogContent>
          <DialogHeader><DialogTitle>New Corrective Action</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div><Label>KPI ID *</Label><Input type="number" value={newForm.kpiId || ""} onChange={e => setNewForm(p => ({ ...p, kpiId: Number(e.target.value) }))} /></div>
            <div>
              <Label>Quarter</Label>
              <Select value={String(newForm.quarter)} onValueChange={v => setNewForm(p => ({ ...p, quarter: Number(v) }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {[1, 2, 3, 4].map(q => <SelectItem key={q} value={String(q)}>Q{q}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div><Label>Action Description *</Label><Textarea value={newForm.actionDescription} onChange={e => setNewForm(p => ({ ...p, actionDescription: e.target.value }))} /></div>
            <div><Label>Due Date *</Label><Input type="date" value={newForm.dueDate} onChange={e => setNewForm(p => ({ ...p, dueDate: e.target.value }))} /></div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNew(false)}>Cancel</Button>
            <Button onClick={handleCreate} disabled={!newForm.kpiId || !newForm.actionDescription || !newForm.dueDate}>Create</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={showEdit} onOpenChange={v => { setShowEdit(v); if (!v) setEditingId(null); }}>
        <DialogContent>
          <DialogHeader><DialogTitle>Edit Corrective Action</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div><Label>Action Description *</Label><Textarea value={editForm.actionDescription} onChange={e => setEditForm(p => ({ ...p, actionDescription: e.target.value }))} /></div>
            <div><Label>Due Date *</Label><Input type="date" value={editForm.dueDate} onChange={e => setEditForm(p => ({ ...p, dueDate: e.target.value }))} /></div>
            <div><Label>Action Owner IDs</Label><Input value={editForm.actionOwnerIds} onChange={e => setEditForm(p => ({ ...p, actionOwnerIds: e.target.value }))} placeholder="Comma-separated IDs" /></div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => { setShowEdit(false); setEditingId(null); }}>Cancel</Button>
            <Button onClick={handleEdit} disabled={!editForm.actionDescription || !editForm.dueDate}>Save Changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/actuals/corrective-actions.component.ts
import { ChangeDetectionStrategy, Component, Inject, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { catchError, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';

interface RemedialAction {
  id: number;
  kpiId: number;
  quarter: number;
  actionDescription: string;
  dueDate: string;
  actionOwnerIds?: string | null;
  status: string;
}

interface NewActionForm {
  kpiId: number;
  quarter: number;
  actionDescription: string;
  dueDate: string;
}

interface EditActionForm {
  actionDescription: string;
  dueDate: string;
  actionOwnerIds: string;
}

// ─── New Action Dialog ─────────────────────────────────────────────────────
@Component({
  selector: 'app-new-corrective-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  template: `
    <h2 mat-dialog-title>New Corrective Action</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline" class="full">
        <mat-label>KPI ID *</mat-label>
        <input matInput type="number" [(ngModel)]="form.kpiId" name="k" required />
      </mat-form-field>
      <mat-form-field appearance="outline" class="full">
        <mat-label>Quarter</mat-label>
        <mat-select [(ngModel)]="form.quarter" name="q">
          <mat-option *ngFor="let q of [1,2,3,4]" [value]="q">Q{{ q }}</mat-option>
        </mat-select>
      </mat-form-field>
      <mat-form-field appearance="outline" class="full">
        <mat-label>Action Description *</mat-label>
        <textarea matInput rows="3" [(ngModel)]="form.actionDescription" name="d" required></textarea>
      </mat-form-field>
      <mat-form-field appearance="outline" class="full">
        <mat-label>Due Date *</mat-label>
        <input matInput type="date" [(ngModel)]="form.dueDate" name="dd" required />
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="primary" type="button"
              [disabled]="!form.kpiId || !form.actionDescription.trim() || !form.dueDate"
              (click)="ref.close(form)">Create</button>
    </mat-dialog-actions>
  `,
  styles: [`.content { min-width: 460px; padding-top: 12px !important; display: flex; flex-direction: column; gap: 4px; } .full { width: 100%; }`],
})
export class NewCorrectiveDialogComponent {
  form: NewActionForm = { kpiId: 0, quarter: 1, actionDescription: '', dueDate: '' };
  constructor(public ref: MatDialogRef<NewCorrectiveDialogComponent, NewActionForm | null>) {}
}

// ─── Edit Action Dialog ────────────────────────────────────────────────────
@Component({
  selector: 'app-edit-corrective-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>Edit Corrective Action</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline" class="full">
        <mat-label>Action Description *</mat-label>
        <textarea matInput rows="3" [(ngModel)]="form.actionDescription" name="d" required></textarea>
      </mat-form-field>
      <mat-form-field appearance="outline" class="full">
        <mat-label>Due Date *</mat-label>
        <input matInput type="date" [(ngModel)]="form.dueDate" name="dd" required />
      </mat-form-field>
      <mat-form-field appearance="outline" class="full">
        <mat-label>Action Owner IDs</mat-label>
        <input matInput [(ngModel)]="form.actionOwnerIds" name="o" placeholder="Comma-separated IDs" />
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="primary" type="button"
              [disabled]="!form.actionDescription.trim() || !form.dueDate"
              (click)="ref.close(form)">Save Changes</button>
    </mat-dialog-actions>
  `,
  styles: [`.content { min-width: 460px; padding-top: 12px !important; display: flex; flex-direction: column; gap: 4px; } .full { width: 100%; }`],
})
export class EditCorrectiveDialogComponent {
  form: EditActionForm;
  constructor(
    public ref: MatDialogRef<EditCorrectiveDialogComponent, EditActionForm | null>,
    @Inject(MAT_DIALOG_DATA) data: EditActionForm,
  ) { this.form = { ...data }; }
}

// ─── Main Page ─────────────────────────────────────────────────────────────
@Component({
  selector: 'app-corrective-actions',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatSelectModule,
    PageHeaderComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="plat-page">
      <app-page-header title="Corrective & Remedial Actions"
                       subtitle="Track corrective actions for underperforming KPIs"
                       icon="build" tone="orange">
        <button mat-flat-button color="primary" (click)="openNew()"><mat-icon>add</mat-icon> New Action</button>
      </app-page-header>

      <div class="plat-card alert" *ngIf="overdueActions().length">
        <mat-icon>warning</mat-icon>
        <div>
          <p class="bold">{{ overdueActions().length }} Overdue Action{{ overdueActions().length > 1 ? 's' : '' }}</p>
          <p class="small">Actions past their due date requiring attention</p>
        </div>
      </div>

      <div class="filters">
        <mat-form-field appearance="outline">
          <mat-label>Status</mat-label>
          <mat-select [ngModel]="statusFilter()" (ngModelChange)="onStatusFilter($event)">
            <mat-option value="all">All Statuses</mat-option>
            <mat-option value="Open">Open</mat-option>
            <mat-option value="In Progress">In Progress</mat-option>
            <mat-option value="Completed">Completed</mat-option>
          </mat-select>
        </mat-form-field>
      </div>

      <div class="list">
        <div class="plat-card action" *ngFor="let a of actions(); trackBy: trackById"
             [class.overdue-card]="isOverdue(a)">
          <div class="action-info">
            <div class="badges">
              <span class="badge" [class]="isOverdue(a) ? 'red-dark' : statusClass(a.status)">
                {{ isOverdue(a) ? 'Overdue' : a.status }}
              </span>
              <span class="badge outline">KPI #{{ a.kpiId }}</span>
              <span class="badge outline">Q{{ a.quarter }}</span>
            </div>
            <p class="desc">{{ a.actionDescription }}</p>
            <p class="muted xs"><mat-icon>schedule</mat-icon> Due: {{ a.dueDate }}</p>
          </div>
          <div class="action-buttons">
            <button mat-button *ngIf="a.status !== 'Completed'" (click)="openEdit(a)"><mat-icon>edit</mat-icon> Edit</button>
            <button mat-button *ngIf="a.status === 'Open'" (click)="updateStatus(a, 'In Progress')">Start</button>
            <button mat-button class="green" *ngIf="a.status === 'In Progress'" (click)="updateStatus(a, 'Completed')">
              <mat-icon>check_circle</mat-icon> Complete
            </button>
          </div>
        </div>

        <div class="plat-card empty" *ngIf="!actions().length">
          <mat-icon>check_circle</mat-icon>
          <p class="bold">No corrective actions</p>
        </div>
      </div>
    </section>
  `,
  styles: [`
    .alert { display: flex; align-items: center; gap: 12px; padding: 16px; background: #fef2f2; border: 1px solid #fecaca; margin-bottom: 16px; }
    .alert mat-icon { color: #dc2626; font-size: 26px; width: 26px; height: 26px; }
    .alert .bold { color: #b91c1c; margin: 0; } .alert .small { color: #dc2626; margin: 0; font-size: 13px; }
    .filters { margin-bottom: 16px; }
    .filters mat-form-field { width: 220px; }
    .list { display: flex; flex-direction: column; gap: 12px; }
    .action { padding: 16px; display: flex; justify-content: space-between; align-items: flex-start; gap: 12px; }
    .overdue-card { border: 1px solid #fca5a5; }
    .badges { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; margin-bottom: 6px; }
    .desc { font-weight: 500; color: #1e293b; margin: 0; }
    .action-buttons { display: flex; gap: 4px; flex-shrink: 0; }
    .badge { display: inline-flex; align-items: center; gap: 2px; padding: 2px 10px; border-radius: 999px; font-size: 11px; font-weight: 600; }
    .badge.outline { background: #fff; border: 1px solid #cbd5e1; color: #475569; }
    .badge.red { background: #fee2e2; color: #b91c1c; }
    .badge.red-dark { background: #fecaca; color: #991b1b; }
    .badge.amber { background: #fef3c7; color: #b45309; }
    .badge.green { background: #dcfce7; color: #15803d; }
    .badge.gray { background: #f1f5f9; color: #475569; }
    .green { color: #16a34a; }
    .muted { color: #64748b; } .xs { font-size: 11px; display: inline-flex; align-items: center; gap: 4px; margin: 6px 0 0; }
    .xs mat-icon { font-size: 13px; width: 13px; height: 13px; }
    .bold { font-weight: 600; }
    .empty { padding: 40px; text-align: center; color: #64748b; }
    .empty mat-icon { font-size: 40px; width: 40px; height: 40px; color: #cbd5e1; }
  `],
})
export class CorrectiveActionsComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  private readonly dialog = inject(MatDialog);

  actions = signal<RemedialAction[]>([]);
  statusFilter = signal<string>('all');

  overdueActions = computed<RemedialAction[]>(() =>
    this.actions().filter((a) => a.status !== 'Completed' && new Date(a.dueDate) < new Date()),
  );

  ngOnInit() { this.load(); }

  onStatusFilter(status: string) {
    this.statusFilter.set(status);
    this.load();
  }

  load() {
    const filter = this.statusFilter();
    const params = filter !== 'all' ? { status: filter } : undefined;
    this.api.get<RemedialAction[]>('/remedial-actions', params).pipe(
      catchError(() => of([] as RemedialAction[])),
    ).subscribe((rows) => this.actions.set(Array.isArray(rows) ? rows : []));
  }

  isOverdue(a: RemedialAction): boolean {
    return a.status !== 'Completed' && new Date(a.dueDate) < new Date();
  }

  statusClass(status: string): string {
    switch (status) {
      case 'Open': return 'red';
      case 'In Progress': return 'amber';
      case 'Completed': return 'green';
      default: return 'gray';
    }
  }

  openNew() {
    this.dialog.open(NewCorrectiveDialogComponent, { panelClass: 'plat-dialog', autoFocus: true })
      .afterClosed().subscribe((res: NewActionForm | undefined) => {
        if (!res || !res.kpiId || !res.actionDescription.trim() || !res.dueDate) return;
        this.api.post('/remedial-actions', {
          kpiId: res.kpiId,
          quarter: res.quarter,
          actionDescription: res.actionDescription,
          dueDate: res.dueDate,
        }).pipe(
          tap(() => { this.toast.success('Corrective action created'); this.load(); }),
          catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? e?.message); return of(null); }),
        ).subscribe();
      });
  }

  openEdit(action: RemedialAction) {
    const data: EditActionForm = {
      actionDescription: action.actionDescription ?? '',
      dueDate: action.dueDate ?? '',
      actionOwnerIds: action.actionOwnerIds ?? '',
    };
    this.dialog.open(EditCorrectiveDialogComponent, { panelClass: 'plat-dialog', autoFocus: true, data })
      .afterClosed().subscribe((res: EditActionForm | undefined) => {
        if (!res || !res.actionDescription.trim() || !res.dueDate) return;
        this.api.patch(`/remedial-actions/${action.id}`, {
          actionDescription: res.actionDescription,
          dueDate: res.dueDate,
          actionOwnerIds: res.actionOwnerIds || undefined,
        }).pipe(
          tap(() => { this.toast.success('Corrective action updated'); this.load(); }),
          catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? e?.message); return of(null); }),
        ).subscribe();
      });
  }

  updateStatus(action: RemedialAction, status: string) {
    this.api.patch(`/remedial-actions/${action.id}`, { status }).pipe(
      tap(() => { this.toast.success(`Status updated to ${status}`); this.load(); }),
      catchError((e) => { this.toast.error('Error', e?.error?.error ?? e?.error?.message ?? e?.message); return of(null); }),
    ).subscribe();
  }

  trackById(_: number, x: { id: number }): number { return x.id; }
}
