// Insight-Performance-Hub/artifacts/perf-app/src/app/features/weightings/competency-requirements.component.ts
import { ChangeDetectionStrategy, Component, Inject, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { catchError, finalize, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { CompetencyRequirement, Cycle } from '@core/models/domain.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';
import { StatusBadgeComponent } from '@shared/components/status-badge/status-badge.component';
import { LoadingSpinnerComponent } from '@shared/components/loading-spinner/loading-spinner.component';

@Component({
  selector: 'app-competency-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  template: `
    <h2 mat-dialog-title>{{ data.entity ? 'Edit' : 'Create' }} Competency</h2>
    <form (ngSubmit)="save()" #f="ngForm">
      <mat-dialog-content class="content">
        <div class="grid">
          <mat-form-field appearance="outline"><mat-label>Name</mat-label><input matInput [(ngModel)]="model.name" name="n" required /></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Weight (%)</mat-label><input matInput type="number" step="0.1" [(ngModel)]="model.weight" name="w" required /></mat-form-field>
        </div>
        <mat-form-field appearance="outline"><mat-label>Description</mat-label><textarea matInput rows="3" [(ngModel)]="model.description" name="d"></textarea></mat-form-field>
        <div class="grid">
          <mat-form-field appearance="outline">
            <mat-label>Status</mat-label>
            <mat-select [(ngModel)]="model.isActive" name="a">
              <mat-option [value]="true">Active</mat-option>
              <mat-option [value]="false">Inactive</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Sort Order</mat-label><input matInput type="number" [(ngModel)]="model.sortOrder" name="s" /></mat-form-field>
        </div>
      </mat-dialog-content>
      <mat-dialog-actions align="end">
        <button mat-button type="button" mat-dialog-close>Cancel</button>
        <button mat-flat-button color="primary" type="submit" [disabled]="saving() || f.invalid">{{ saving() ? 'Saving…' : 'Save' }}</button>
      </mat-dialog-actions>
    </form>
  `,
  styles: [`.content { display:flex; flex-direction: column; gap: 4px; padding-top: 12px !important; min-width: 480px; } .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; } mat-form-field { width: 100%; }`],
})
export class CompetencyDialogComponent {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  saving = signal(false);
  model: { name: string; description: string; weight: number; isActive: boolean; sortOrder: number };
  constructor(
    public ref: MatDialogRef<CompetencyDialogComponent, CompetencyRequirement | null>,
    @Inject(MAT_DIALOG_DATA) public data: { entity: CompetencyRequirement | null; cycleId: number },
  ) {
    const e = data.entity;
    this.model = { name: e?.name ?? '', description: e?.description ?? '', weight: e?.weight ?? 0, isActive: e?.isActive ?? true, sortOrder: e?.sortOrder ?? 0 };
  }
  save() {
    this.saving.set(true);
    const payload = { ...this.model, weight: Number(this.model.weight), sortOrder: Number(this.model.sortOrder) || 0, cycleId: this.data.cycleId };
    const id = this.data.entity?.id;
    const obs = id ? this.api.patch<CompetencyRequirement>(`/competency-requirements/${id}`, payload) : this.api.post<CompetencyRequirement>('/competency-requirements', payload);
    obs.pipe(
      tap((r) => { this.toast.success('Saved'); this.ref.close(r); }),
      catchError((e) => { this.toast.error('Save failed', e?.error?.message ?? e?.message); return of(null); }),
      finalize(() => this.saving.set(false)),
    ).subscribe();
  }
}

@Component({
  selector: 'app-competency-requirements',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, PageHeaderComponent, StatusBadgeComponent, LoadingSpinnerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="plat-page">
      <app-page-header title="Competency Requirements" subtitle="Core competencies and their weighting for performance assessments." icon="psychology" tone="purple">
        <button mat-flat-button color="primary" (click)="open(null)" [disabled]="!activeCycle()"><mat-icon>add</mat-icon> Add Competency</button>
      </app-page-header>
      <app-loading-spinner *ngIf="loading()"></app-loading-spinner>
      <ng-container *ngIf="!loading()">
        <div class="weight-summary">
          <span [class.bad]="!isHundred(total())">Total Weight: {{ total().toFixed(1) }}%</span>
          <mat-icon *ngIf="!isHundred(total())" color="warn" inline>warning</mat-icon>
        </div>
        <div class="plat-card">
          <table class="plat-table">
            <thead><tr><th>Competency</th><th>Description</th><th>Weight</th><th>Status</th><th class="actions">Actions</th></tr></thead>
            <tbody>
              <tr *ngIf="rows().length === 0"><td colspan="5" class="empty">No competencies defined.</td></tr>
              <tr *ngFor="let r of rows()">
                <td><strong>{{ r.name }}</strong></td>
                <td class="muted truncate">{{ r.description || '—' }}</td>
                <td><div class="bar"><div class="bar__fill" [style.width.%]="clamp(r.weight)"></div></div><span class="pct">{{ r.weight }}%</span></td>
                <td><app-status-badge [status]="r.isActive ? 'Active' : 'Inactive'"></app-status-badge></td>
                <td class="actions"><button mat-button color="primary" (click)="open(r)"><mat-icon>edit</mat-icon> Edit</button></td>
              </tr>
            </tbody>
          </table>
        </div>
      </ng-container>
    </section>
  `,
  styles: [`
    .weight-summary { margin: 8px 0 16px; font-size: 13px; font-weight: 700; color: #16a34a; display:flex; align-items:center; gap:6px; }
    .weight-summary .bad, .weight-summary span.bad { color: #ef4444; }
    .bar { display: inline-block; width: 84px; height: 8px; background: #e2e8f0; border-radius: 4px; overflow: hidden; vertical-align: middle; margin-right: 10px; }
    .bar__fill { height: 100%; background: #8b5cf6; }
    .pct { font-weight: 600; color: #475569; vertical-align: middle; }
    .truncate { max-width: 280px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  `],
})
export class CompetencyRequirementsComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly dialog = inject(MatDialog);
  cycles = signal<Cycle[]>([]);
  rows = signal<CompetencyRequirement[]>([]);
  loading = signal(true);
  activeCycle = computed<Cycle | null>(() => this.cycles().find((c) => c.status === 'Open') ?? this.cycles()[0] ?? null);
  total = computed(() => this.rows().reduce((s, r) => s + Number(r.weight), 0));

  ngOnInit() { this.load(); }
  isHundred(t: number) { return Math.abs(t - 100) < 0.01; }
  clamp(v: number) { return Math.max(0, Math.min(100, Number(v) || 0)); }

  load() {
    this.loading.set(true);
    this.api.get<Cycle[]>('/cycles').pipe(
      catchError(() => of([] as Cycle[])),
      tap((cs) => this.cycles.set(Array.isArray(cs) ? cs : [])),
    ).subscribe(() => {
      const cycle = this.activeCycle();
      if (!cycle) { this.rows.set([]); this.loading.set(false); return; }
      this.api.get<CompetencyRequirement[]>('/competency-requirements', { cycleId: cycle.id }).pipe(
        catchError(() => of([] as CompetencyRequirement[])),
        tap((r) => this.rows.set(Array.isArray(r) ? r : [])),
        finalize(() => this.loading.set(false)),
      ).subscribe();
    });
  }
  open(entity: CompetencyRequirement | null) {
    const cycle = this.activeCycle();
    if (!cycle) return;
    this.dialog.open(CompetencyDialogComponent, { data: { entity, cycleId: cycle.id }, panelClass: 'plat-dialog', autoFocus: false })
      .afterClosed().subscribe((r) => { if (r) this.load(); });
  }
}

// Insight-Performance-Hub/artifacts/perf-app/src/pages/weightings/CompetencyRequirements.tsx
import { useState } from "react";
import { useListCompetencyRequirements, useCreateCompetencyRequirement, useUpdateCompetencyRequirement, useListCycles, getListCompetencyRequirementsQueryKey } from "@workspace/api-client-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/status-badge";
import { Plus, Pencil, Loader2, Users, AlertTriangle } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";

export default function CompetencyRequirements() {
  const { data: cycles } = useListCycles();
  const activeCycle = cycles?.find(c => c.status === "Open") || cycles?.[0];
  const { data: requirements, isLoading } = useListCompetencyRequirements({ cycleId: activeCycle?.id });
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);

  const totalWeight = requirements?.reduce((s, r) => s + r.weight, 0) || 0;

  if (isLoading) return <div className="flex p-8 justify-center"><Loader2 className="w-8 h-8 animate-spin text-platinum-primary" /></div>;

  return (
    <div className="space-y-6 animate-in fade-in">
      <div className="flex justify-between items-center bg-white p-6 rounded-2xl shadow-sm border border-border">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-3">
            <div className="p-2 bg-violet-50 text-violet-600 rounded-lg"><Users className="w-6 h-6" /></div>
            Competency Requirements
          </h1>
          <p className="text-slate-500 mt-1">Core competencies and their weighting for performance assessments.</p>
        </div>
        {activeCycle && <CompDialog open={isDialogOpen} onOpenChange={setIsDialogOpen} editingId={editingId} setEditingId={setEditingId} requirements={requirements} cycleId={activeCycle.id} />}
      </div>
      <div className="flex items-center gap-2 text-sm">
        <span className={`font-bold ${Math.abs(totalWeight - 100) < 0.01 ? "text-green-600" : "text-red-500"}`}>Total Weight: {totalWeight.toFixed(1)}%</span>
        {Math.abs(totalWeight - 100) >= 0.01 && <AlertTriangle className="w-4 h-4 text-red-500" />}
      </div>
      <Card className="platinum-card overflow-hidden">
        <table className="w-full text-sm text-left">
          <thead className="text-xs text-slate-500 uppercase bg-slate-50 border-b border-border font-semibold">
            <tr>
              <th className="px-6 py-4">Competency</th>
              <th className="px-6 py-4">Description</th>
              <th className="px-6 py-4">Weight</th>
              <th className="px-6 py-4">Status</th>
              <th className="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {requirements?.length === 0 && <tr><td colSpan={5} className="px-6 py-8 text-center text-slate-500">No competencies defined.</td></tr>}
            {requirements?.map((r) => (
              <tr key={r.id} className="hover:bg-slate-50/50 transition-colors">
                <td className="px-6 py-4 font-medium text-slate-900">{r.name}</td>
                <td className="px-6 py-4 text-slate-500 truncate max-w-xs">{r.description || "-"}</td>
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <div className="w-20 bg-slate-200 rounded-full h-2"><div className="bg-violet-500 h-2 rounded-full" style={{ width: `${Math.min(r.weight, 100)}%` }} /></div>
                    <span className="font-semibold text-slate-700">{r.weight}%</span>
                  </div>
                </td>
                <td className="px-6 py-4"><StatusBadge status={r.isActive ? "Active" : "Inactive"} /></td>
                <td className="px-6 py-4 text-right">
                  <Button variant="ghost" size="sm" className="text-blue-600" onClick={() => { setEditingId(r.id); setIsDialogOpen(true); }}><Pencil className="w-4 h-4 mr-2" /> Edit</Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>
    </div>
  );
}

interface CompDialogProps {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  editingId: number | null;
  setEditingId: (id: number | null) => void;
  requirements: { id: number; name: string; description: string; weight: number; isActive: boolean; sortOrder: number }[] | undefined;
  cycleId: number;
}

function CompDialog({ open, onOpenChange, editingId, setEditingId, requirements, cycleId }: CompDialogProps) {
  const qc = useQueryClient();
  const { toast } = useToast();
  const createMut = useCreateCompetencyRequirement();
  const updateMut = useUpdateCompetencyRequirement();
  const r = editingId ? requirements?.find((x) => x.id === editingId) : null;
  const isPending = createMut.isPending || updateMut.isPending;

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const data = { name: fd.get("name") as string, description: fd.get("description") as string || "", weight: parseFloat(fd.get("weight") as string), cycleId, isActive: fd.get("status") === "active", sortOrder: parseInt(fd.get("sortOrder") as string) || 0 };
    const onSuccess = () => { qc.invalidateQueries({ queryKey: getListCompetencyRequirementsQueryKey() }); onOpenChange(false); setEditingId(null); toast({ title: "Saved" }); };
    if (editingId) updateMut.mutate({ id: editingId, data }, { onSuccess });
    else createMut.mutate({ data }, { onSuccess });
  };

  return (
    <Dialog open={open} onOpenChange={(v) => { onOpenChange(v); if (!v) setEditingId(null); }}>
      <DialogTrigger asChild><Button className="bg-platinum-primary rounded-xl"><Plus className="w-4 h-4 mr-2" /> Add Competency</Button></DialogTrigger>
      <DialogContent className="rounded-2xl">
        <DialogHeader><DialogTitle>{editingId ? "Edit" : "Create"} Competency</DialogTitle></DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2"><label className="text-xs font-bold text-slate-500 uppercase">Name</label><Input name="name" required defaultValue={r?.name} className="h-11 rounded-xl" /></div>
            <div className="space-y-2"><label className="text-xs font-bold text-slate-500 uppercase">Weight (%)</label><Input type="number" step="0.1" name="weight" required defaultValue={r?.weight} className="h-11 rounded-xl" /></div>
          </div>
          <div className="space-y-2"><label className="text-xs font-bold text-slate-500 uppercase">Description</label><Textarea name="description" defaultValue={r?.description} className="rounded-xl" /></div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase">Status</label>
              <Select name="status" defaultValue={r ? (r.isActive ? "active" : "inactive") : "active"}>
                <SelectTrigger className="h-11 rounded-xl"><SelectValue /></SelectTrigger>
                <SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent>
              </Select>
            </div>
            <div className="space-y-2"><label className="text-xs font-bold text-slate-500 uppercase">Sort Order</label><Input type="number" name="sortOrder" defaultValue={r?.sortOrder || 0} className="h-11 rounded-xl" /></div>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)} className="rounded-xl">Cancel</Button>
            <Button type="submit" disabled={isPending} className="rounded-xl bg-platinum-primary">{isPending && <Loader2 className="w-4 h-4 mr-2 animate-spin" />} Save</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
