// Insight-Performance-Hub/artifacts/perf-app/src/app/features/sdbip/sdbip-overview.component.ts
import { ChangeDetectionStrategy, Component, Inject, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { catchError, finalize, forkJoin, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { Cycle, Scorecard } from '@core/models/domain.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';
import { LoadingSpinnerComponent } from '@shared/components/loading-spinner/loading-spinner.component';
import { StatusBadgeComponent } from '@shared/components/status-badge/status-badge.component';
import { EmptyStateComponent } from '@shared/components/empty-state/empty-state.component';

export interface SdbipItem {
  id: number;
  cycleId: number;
  kpiId?: number | null;
  description: string;
  status: string;
  q1Target?: string | null;
  q2Target?: string | null;
  q3Target?: string | null;
  q4Target?: string | null;
}

export interface SdbipRevision {
  id: number;
  sdbipItemId: number;
  revisionNumber: number;
  status: string;
  reason: string;
  previousQ1Target?: string | null; newQ1Target?: string | null;
  previousQ2Target?: string | null; newQ2Target?: string | null;
  previousQ3Target?: string | null; newQ3Target?: string | null;
  previousQ4Target?: string | null; newQ4Target?: string | null;
}

interface QuarterForm { q1Target: string; q2Target: string; q3Target: string; q4Target: string; }
interface EditFormData { description: string; q1Target: string; q2Target: string; q3Target: string; q4Target: string; }
interface ReviseFormData extends QuarterForm { reason: string; }

// ─── New Item Dialog ───────────────────────────────────────────────────────
@Component({
  selector: 'app-new-sdbip-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>New SDBIP Item</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline">
        <mat-label>Description</mat-label>
        <textarea matInput rows="4" [(ngModel)]="description" name="d" required></textarea>
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="primary" type="button"
              [disabled]="!description.trim()"
              (click)="ref.close(description.trim())">Create</button>
    </mat-dialog-actions>
  `,
  styles: [`.content { min-width: 460px; padding-top: 12px !important; } mat-form-field { width: 100%; }`],
})
export class NewSdbipDialogComponent {
  description = '';
  constructor(public ref: MatDialogRef<NewSdbipDialogComponent, string | null>) {}
}

// ─── Edit Item Dialog ──────────────────────────────────────────────────────
@Component({
  selector: 'app-edit-sdbip-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>Edit SDBIP Item</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline" class="full">
        <mat-label>Description *</mat-label>
        <textarea matInput rows="3" [(ngModel)]="form.description" name="desc" required></textarea>
      </mat-form-field>
      <div class="grid">
        <mat-form-field appearance="outline"><mat-label>Q1 Target</mat-label><input matInput [(ngModel)]="form.q1Target" name="q1" /></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Q2 Target</mat-label><input matInput [(ngModel)]="form.q2Target" name="q2" /></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Q3 Target</mat-label><input matInput [(ngModel)]="form.q3Target" name="q3" /></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Q4 Target</mat-label><input matInput [(ngModel)]="form.q4Target" name="q4" /></mat-form-field>
      </div>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="primary" type="button"
              [disabled]="!form.description.trim()"
              (click)="ref.close(form)">Save Changes</button>
    </mat-dialog-actions>
  `,
  styles: [`
    .content { min-width: 520px; padding-top: 12px !important; }
    .full, mat-form-field { width: 100%; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  `],
})
export class EditSdbipDialogComponent {
  form: EditFormData;
  constructor(
    public ref: MatDialogRef<EditSdbipDialogComponent, EditFormData | null>,
    @Inject(MAT_DIALOG_DATA) data: EditFormData,
  ) { this.form = { ...data }; }
}

// ─── Revise Item Dialog ────────────────────────────────────────────────────
@Component({
  selector: 'app-revise-sdbip-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>Revise SDBIP Item</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline" class="full">
        <mat-label>Reason for revision *</mat-label>
        <textarea matInput rows="3" [(ngModel)]="form.reason" name="reason" required></textarea>
      </mat-form-field>
      <div class="grid">
        <mat-form-field appearance="outline"><mat-label>Q1 Target</mat-label><input matInput [(ngModel)]="form.q1Target" name="q1" /></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Q2 Target</mat-label><input matInput [(ngModel)]="form.q2Target" name="q2" /></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Q3 Target</mat-label><input matInput [(ngModel)]="form.q3Target" name="q3" /></mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Q4 Target</mat-label><input matInput [(ngModel)]="form.q4Target" name="q4" /></mat-form-field>
      </div>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Cancel</button>
      <button mat-flat-button color="primary" type="button"
              [disabled]="!form.reason.trim()"
              (click)="ref.close(form)">Submit Revision</button>
    </mat-dialog-actions>
  `,
  styles: [`
    .content { min-width: 520px; padding-top: 12px !important; }
    .full, mat-form-field { width: 100%; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  `],
})
export class ReviseSdbipDialogComponent {
  form: ReviseFormData = { reason: '', q1Target: '', q2Target: '', q3Target: '', q4Target: '' };
  constructor(public ref: MatDialogRef<ReviseSdbipDialogComponent, ReviseFormData | null>) {}
}

// ─── Revisions History Dialog ──────────────────────────────────────────────
@Component({
  selector: 'app-sdbip-revisions-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule, MatIconModule, StatusBadgeComponent],
  template: `
    <h2 mat-dialog-title>Revision History</h2>
    <mat-dialog-content class="content">
      <ng-container *ngIf="data.revisions.length > 0; else empty">
        <div *ngFor="let rev of data.revisions" class="rev">
          <div class="rev-head">
            <span class="rev-num">Revision #{{ rev.revisionNumber }}</span>
            <app-status-badge [status]="rev.status"></app-status-badge>
          </div>
          <p class="reason">{{ rev.reason }}</p>
          <div class="grid">
            <span>Q1: {{ rev.previousQ1Target || '—' }} <mat-icon class="arr">arrow_forward</mat-icon> {{ rev.newQ1Target || '—' }}</span>
            <span>Q2: {{ rev.previousQ2Target || '—' }} <mat-icon class="arr">arrow_forward</mat-icon> {{ rev.newQ2Target || '—' }}</span>
            <span>Q3: {{ rev.previousQ3Target || '—' }} <mat-icon class="arr">arrow_forward</mat-icon> {{ rev.newQ3Target || '—' }}</span>
            <span>Q4: {{ rev.previousQ4Target || '—' }} <mat-icon class="arr">arrow_forward</mat-icon> {{ rev.newQ4Target || '—' }}</span>
          </div>
        </div>
      </ng-container>
      <ng-template #empty>
        <p class="empty-msg">No revisions recorded</p>
      </ng-template>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button type="button" mat-dialog-close>Close</button>
    </mat-dialog-actions>
  `,
  styles: [`
    .content { min-width: 520px; max-height: 60vh; }
    .rev { border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; margin-bottom: 12px; }
    .rev-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
    .rev-num { font-size: 12px; font-weight: 700; color: #475569; letter-spacing: .03em; text-transform: uppercase; }
    .reason { margin: 4px 0 8px; color: #334155; font-size: 13px; }
    .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; font-size: 12px; color: #64748b; }
    .arr { font-size: 12px; width: 12px; height: 12px; vertical-align: middle; }
    .empty-msg { text-align: center; color: #64748b; padding: 24px 0; }
  `],
})
export class SdbipRevisionsDialogComponent {
  constructor(@Inject(MAT_DIALOG_DATA) public data: { revisions: SdbipRevision[] }) {}
}

// ─── Main Page ─────────────────────────────────────────────────────────────
@Component({
  selector: 'app-sdbip-overview',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatSelectModule, MatTooltipModule,
    PageHeaderComponent, LoadingSpinnerComponent, StatusBadgeComponent, EmptyStateComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './sdbip-overview.component.html',
  styleUrls: ['./sdbip-overview.component.scss'],
})
export class SdbipOverviewComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  private readonly dialog = inject(MatDialog);

  loading = signal(true);
  cycles = signal<Cycle[]>([]);
  items = signal<SdbipItem[]>([]);
  scorecards = signal<Scorecard[]>([]);
  selectedCycleId = signal<number | null>(null);

  effectiveCycleId = computed<number | null>(() => this.selectedCycleId() ?? this.cycles()[0]?.id ?? null);

  approvedScorecards = computed<Scorecard[]>(() =>
    this.scorecards().filter((s) => s.status === 'Approved'),
  );

  readonly statusCards: { key: string; label: string }[] = [
    { key: 'Draft', label: 'Draft' },
    { key: 'Approved Baseline', label: 'Approved Baseline' },
    { key: 'In-Year Monitoring', label: 'In-Year Monitoring' },
    { key: 'Final Approved Revision', label: 'Final Approved Revision' },
  ];

  countByStatus(status: string): number {
    return this.items().filter((i) => i.status === status).length;
  }

  ngOnInit() {
    this.api.get<Cycle[]>('/cycles').pipe(
      catchError(() => of([] as Cycle[])),
      tap((cs) => this.cycles.set(Array.isArray(cs) ? cs : [])),
    ).subscribe(() => this.loadForCycle());
  }

  selectCycle(id: number) {
    this.selectedCycleId.set(id);
    this.loadForCycle();
  }

  loadForCycle() {
    const cycleId = this.effectiveCycleId();
    if (!cycleId) {
      this.items.set([]); this.scorecards.set([]); this.loading.set(false);
      return;
    }
    this.loading.set(true);
    forkJoin({
      items: this.api.get<SdbipItem[]>('/sdbip-items', { cycleId }).pipe(catchError(() => of([] as SdbipItem[]))),
      scorecards: this.api.get<Scorecard[]>('/scorecards', { cycleId }).pipe(catchError(() => of([] as Scorecard[]))),
    }).pipe(
      finalize(() => this.loading.set(false)),
    ).subscribe(({ items, scorecards }) => {
      this.items.set(Array.isArray(items) ? items : []);
      this.scorecards.set(Array.isArray(scorecards) ? scorecards : []);
    });
  }

  refreshItems() {
    const cycleId = this.effectiveCycleId();
    if (!cycleId) return;
    this.api.get<SdbipItem[]>('/sdbip-items', { cycleId }).pipe(
      catchError(() => of([] as SdbipItem[])),
      tap((r) => this.items.set(Array.isArray(r) ? r : [])),
    ).subscribe();
  }

  // ── Actions ─────────────────────────────────────────────────────────────
  openNew() {
    const cycleId = this.effectiveCycleId();
    if (!cycleId) { this.toast.error('No cycle available'); return; }
    this.dialog.open(NewSdbipDialogComponent, { panelClass: 'plat-dialog', autoFocus: true })
      .afterClosed().subscribe((description) => {
        if (!description) return;
        this.api.post<SdbipItem>('/sdbip-items', { cycleId, description }).pipe(
          tap(() => { this.toast.success('SDBIP item created'); this.refreshItems(); }),
          catchError((e) => { this.toast.error('Error creating item', e?.error?.message ?? e?.message); return of(null); }),
        ).subscribe();
      });
  }

  openEdit(item: SdbipItem) {
    const data: EditFormData = {
      description: item.description ?? '',
      q1Target: item.q1Target ?? '',
      q2Target: item.q2Target ?? '',
      q3Target: item.q3Target ?? '',
      q4Target: item.q4Target ?? '',
    };
    this.dialog.open(EditSdbipDialogComponent, { panelClass: 'plat-dialog', data, autoFocus: true })
      .afterClosed().subscribe((res) => {
        if (!res || !res.description.trim()) return;
        const payload: Partial<SdbipItem> = {
          description: res.description,
          q1Target: res.q1Target || undefined,
          q2Target: res.q2Target || undefined,
          q3Target: res.q3Target || undefined,
          q4Target: res.q4Target || undefined,
        };
        this.api.patch<SdbipItem>(`/sdbip-items/${item.id}`, payload).pipe(
          tap(() => { this.toast.success('SDBIP item updated'); this.refreshItems(); }),
          catchError((e) => { this.toast.error('Error updating', e?.error?.message ?? e?.message); return of(null); }),
        ).subscribe();
      });
  }

  openRevise(item: SdbipItem) {
    this.dialog.open(ReviseSdbipDialogComponent, { panelClass: 'plat-dialog', autoFocus: true })
      .afterClosed().subscribe((res) => {
        if (!res || !res.reason.trim()) return;
        const payload = {
          reason: res.reason,
          q1Target: res.q1Target || undefined,
          q2Target: res.q2Target || undefined,
          q3Target: res.q3Target || undefined,
          q4Target: res.q4Target || undefined,
        };
        this.api.post<SdbipItem>(`/sdbip-items/${item.id}/revise`, payload).pipe(
          tap(() => { this.toast.success('SDBIP item revised'); this.refreshItems(); }),
          catchError((e) => { this.toast.error('Error', e?.error?.message ?? e?.message); return of(null); }),
        ).subscribe();
      });
  }

  openRevisions(item: SdbipItem) {
    this.api.get<SdbipRevision[]>(`/sdbip-items/${item.id}/revisions`).pipe(
      catchError(() => of([] as SdbipRevision[])),
    ).subscribe((revs) => {
      const revisions = Array.isArray(revs) ? revs : [];
      this.dialog.open(SdbipRevisionsDialogComponent, {
        panelClass: 'plat-dialog',
        data: { revisions },
      });
    });
  }

  transition(item: SdbipItem, action: string) {
    this.api.post(`/sdbip-items/${item.id}/transition`, { action }).pipe(
      tap(() => { this.toast.success(`SDBIP ${action}`); this.refreshItems(); }),
      catchError((e) => { this.toast.error('Transition failed', e?.error?.message ?? e?.message); return of(null); }),
    ).subscribe();
  }

  generateFromScorecard(scorecardId: number) {
    this.api.post<SdbipItem[]>('/sdbip/generate', { scorecardId }).pipe(
      tap((result) => {
        const count = Array.isArray(result) ? result.length : 0;
        this.toast.success(`${count} SDBIP items generated`);
        this.refreshItems();
      }),
      catchError((e) => { this.toast.error('Generate failed', e?.error?.message ?? e?.message); return of(null); }),
    ).subscribe();
  }

  trackById(_: number, x: { id: number }): number { return x.id; }
}

// Insight-Performance-Hub/artifacts/perf-app/src/features/sdbip/SdbipOverview.tsx
import { useState } from "react";
import {
  useListSdbipItems, useCreateSdbipItem, useUpdateSdbipItem,
  useTransitionSdbipItem, useReviseSdbipItem, useListSdbipRevisions,
  useGenerateSdbipFromKpis
} from "@workspace/api-client-react";
import { useListCycles, useListScorecards } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/core/hooks/use-toast";
import { Plus, Zap, History, ArrowRight } from "lucide-react";

const STATUS_COLORS: Record<string, string> = {
  Draft: "bg-gray-100 text-gray-700",
  Submitted: "bg-blue-100 text-blue-700",
  "Internal Review": "bg-purple-100 text-purple-700",
  "Approved Baseline": "bg-green-100 text-green-700",
  "In-Year Monitoring": "bg-teal-100 text-teal-700",
  Adjustment: "bg-amber-100 text-amber-700",
  "Final Approved Revision": "bg-emerald-100 text-emerald-700",
};

export default function SdbipOverview() {
  const { toast } = useToast();
  const { data: cycles } = useListCycles();
  const [selectedCycleId, setSelectedCycleId] = useState<number | undefined>();
  const [showNew, setShowNew] = useState(false);
  const [showEdit, setShowEdit] = useState<number | null>(null);
  const [showRevise, setShowRevise] = useState<number | null>(null);
  const [showRevisions, setShowRevisions] = useState<number | null>(null);
  const [newDesc, setNewDesc] = useState("");
  const [editForm, setEditForm] = useState({ description: "", q1Target: "", q2Target: "", q3Target: "", q4Target: "" });
  const [reviseForm, setReviseForm] = useState({ reason: "", q1Target: "", q2Target: "", q3Target: "", q4Target: "" });

  const effectiveCycleId = selectedCycleId || cycles?.[0]?.id;
  const { data: items, refetch } = useListSdbipItems({ cycleId: effectiveCycleId });
  const { data: scorecards } = useListScorecards({ cycleId: effectiveCycleId });
  const revisionsQuery = useListSdbipRevisions(showRevisions ?? 0);
  const revisions = showRevisions ? revisionsQuery.data : undefined;

  const createItem = useCreateSdbipItem();
  const updateItem = useUpdateSdbipItem();
  const transitionItem = useTransitionSdbipItem();
  const reviseItem = useReviseSdbipItem();
  const generateFromKpis = useGenerateSdbipFromKpis();

  async function handleCreate() {
    if (!effectiveCycleId || !newDesc.trim()) return;
    try {
      await createItem.mutateAsync({ data: { cycleId: effectiveCycleId, description: newDesc } });
      setNewDesc("");
      setShowNew(false);
      refetch();
      toast({ title: "SDBIP item created" });
    } catch { toast({ title: "Error", variant: "destructive" }); }
  }

  function openEdit(item: { id: number; description: string; q1Target?: string | null; q2Target?: string | null; q3Target?: string | null; q4Target?: string | null }) {
    setEditForm({
      description: item.description,
      q1Target: item.q1Target || "",
      q2Target: item.q2Target || "",
      q3Target: item.q3Target || "",
      q4Target: item.q4Target || "",
    });
    setShowEdit(item.id);
  }

  async function handleUpdate() {
    if (!showEdit || !editForm.description.trim()) return;
    try {
      await updateItem.mutateAsync({
        id: showEdit,
        data: {
          description: editForm.description,
          q1Target: editForm.q1Target || undefined,
          q2Target: editForm.q2Target || undefined,
          q3Target: editForm.q3Target || undefined,
          q4Target: editForm.q4Target || undefined,
        }
      });
      setShowEdit(null);
      refetch();
      toast({ title: "SDBIP item updated" });
    } catch { toast({ title: "Error updating", variant: "destructive" }); }
  }

  async function handleTransition(id: number, action: string) {
    try {
      await transitionItem.mutateAsync({ id, data: { action } });
      refetch();
      toast({ title: `SDBIP ${action}` });
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : "Error";
      toast({ title: msg, variant: "destructive" });
    }
  }

  async function handleRevise() {
    if (!showRevise || !reviseForm.reason.trim()) return;
    try {
      await reviseItem.mutateAsync({
        id: showRevise,
        data: {
          reason: reviseForm.reason,
          q1Target: reviseForm.q1Target || undefined,
          q2Target: reviseForm.q2Target || undefined,
          q3Target: reviseForm.q3Target || undefined,
          q4Target: reviseForm.q4Target || undefined,
        }
      });
      setShowRevise(null);
      setReviseForm({ reason: "", q1Target: "", q2Target: "", q3Target: "", q4Target: "" });
      refetch();
      toast({ title: "SDBIP item revised" });
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : "Error";
      toast({ title: msg, variant: "destructive" });
    }
  }

  async function handleGenerate(scorecardId: number) {
    try {
      const result = await generateFromKpis.mutateAsync({ data: { scorecardId } });
      refetch();
      toast({ title: `${(result as unknown[]).length} SDBIP items generated` });
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : "Error";
      toast({ title: msg, variant: "destructive" });
    }
  }

  return (
    <div className="space-y-6 animate-in fade-in-50 duration-300">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">SDBIP Management</h2>
          <p className="text-slate-500">Service Delivery and Budget Implementation Plan</p>
        </div>
        <div className="flex gap-3 items-center">
          {cycles && cycles.length > 0 && (
            <Select value={String(effectiveCycleId)} onValueChange={v => setSelectedCycleId(Number(v))}>
              <SelectTrigger className="w-48"><SelectValue /></SelectTrigger>
              <SelectContent>
                {cycles.map(c => <SelectItem key={c.id} value={String(c.id)}>{c.financialYearLabel}</SelectItem>)}
              </SelectContent>
            </Select>
          )}
          <Button onClick={() => setShowNew(true)}><Plus className="w-4 h-4 mr-1" /> Add Item</Button>
        </div>
      </div>

      {scorecards && scorecards.length > 0 && (
        <Card className="bg-blue-50 border-blue-200">
          <CardContent className="p-4">
            <p className="text-sm font-medium text-blue-700 mb-2">Generate SDBIP from approved scorecards:</p>
            <div className="flex gap-2 flex-wrap">
              {scorecards.filter(s => s.status === "Approved").map(sc => (
                <Button key={sc.id} variant="outline" size="sm" onClick={() => handleGenerate(sc.id)}>
                  <Zap className="w-4 h-4 mr-1" /> {sc.name}
                </Button>
              ))}
              {scorecards.filter(s => s.status === "Approved").length === 0 && (
                <p className="text-xs text-blue-500">No approved scorecards yet</p>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-4 gap-3 text-center">
        {["Draft", "Approved Baseline", "In-Year Monitoring", "Final Approved Revision"].map(s => (
          <Card key={s} className="p-3">
            <p className="text-2xl font-bold text-slate-800">{items?.filter(i => i.status === s).length ?? 0}</p>
            <p className="text-xs text-slate-500">{s}</p>
          </Card>
        ))}
      </div>

      <div className="space-y-3">
        {items?.map(item => (
          <Card key={item.id} className="hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <Badge className={STATUS_COLORS[item.status] || "bg-gray-100"}>{item.status}</Badge>
                    {item.kpiId && <Badge variant="outline">KPI #{item.kpiId}</Badge>}
                  </div>
                  <p className="font-semibold text-slate-800">{item.description}</p>
                  <div className="grid grid-cols-4 gap-2 mt-2 text-xs text-slate-500">
                    <span>Q1: {item.q1Target || "-"}</span>
                    <span>Q2: {item.q2Target || "-"}</span>
                    <span>Q3: {item.q3Target || "-"}</span>
                    <span>Q4: {item.q4Target || "-"}</span>
                  </div>
                </div>
                <div className="flex gap-1">
                  {item.status === "Draft" && (
                    <>
                      <Button variant="ghost" size="sm" onClick={() => openEdit(item)}>Edit</Button>
                      <Button variant="ghost" size="sm" onClick={() => handleTransition(item.id, "submit")}>Submit</Button>
                    </>
                  )}
                  {item.status === "Submitted" && (
                    <Button variant="ghost" size="sm" onClick={() => handleTransition(item.id, "review")}>Review</Button>
                  )}
                  {item.status === "Internal Review" && (
                    <Button variant="ghost" size="sm" onClick={() => handleTransition(item.id, "approve_baseline")}>Approve</Button>
                  )}
                  {item.status === "Approved Baseline" && (
                    <>
                      <Button variant="ghost" size="sm" onClick={() => handleTransition(item.id, "monitor")}>Monitor</Button>
                      <Button variant="ghost" size="sm" onClick={() => setShowRevise(item.id)}>Revise</Button>
                    </>
                  )}
                  {item.status === "In-Year Monitoring" && (
                    <Button variant="ghost" size="sm" onClick={() => setShowRevise(item.id)}>Revise</Button>
                  )}
                  {item.status === "Adjustment" && (
                    <Button variant="ghost" size="sm" onClick={() => handleTransition(item.id, "approve_revision")}>Approve Revision</Button>
                  )}
                  <Button variant="ghost" size="sm" onClick={() => setShowRevisions(item.id)}>
                    <History className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
        {(!items || items.length === 0) && (
          <Card className="border-dashed">
            <CardContent className="p-8 text-center text-slate-500">
              <p className="font-medium">No SDBIP items yet</p>
              <p className="text-sm">Create items manually or generate from approved scorecards</p>
            </CardContent>
          </Card>
        )}
      </div>

      <Dialog open={showNew} onOpenChange={setShowNew}>
        <DialogContent>
          <DialogHeader><DialogTitle>New SDBIP Item</DialogTitle></DialogHeader>
          <div><Label>Description</Label><Textarea value={newDesc} onChange={e => setNewDesc(e.target.value)} /></div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNew(false)}>Cancel</Button>
            <Button onClick={handleCreate} disabled={!newDesc.trim()}>Create</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!showRevise} onOpenChange={() => setShowRevise(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Revise SDBIP Item</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div><Label>Reason for revision *</Label><Textarea value={reviseForm.reason} onChange={e => setReviseForm(p => ({ ...p, reason: e.target.value }))} /></div>
            <div className="grid grid-cols-2 gap-3">
              <div><Label>Q1 Target</Label><Input value={reviseForm.q1Target} onChange={e => setReviseForm(p => ({ ...p, q1Target: e.target.value }))} /></div>
              <div><Label>Q2 Target</Label><Input value={reviseForm.q2Target} onChange={e => setReviseForm(p => ({ ...p, q2Target: e.target.value }))} /></div>
              <div><Label>Q3 Target</Label><Input value={reviseForm.q3Target} onChange={e => setReviseForm(p => ({ ...p, q3Target: e.target.value }))} /></div>
              <div><Label>Q4 Target</Label><Input value={reviseForm.q4Target} onChange={e => setReviseForm(p => ({ ...p, q4Target: e.target.value }))} /></div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowRevise(null)}>Cancel</Button>
            <Button onClick={handleRevise} disabled={!reviseForm.reason.trim()}>Submit Revision</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!showRevisions} onOpenChange={() => setShowRevisions(null)}>
        <DialogContent className="max-w-lg">
          <DialogHeader><DialogTitle>Revision History</DialogTitle></DialogHeader>
          {revisions && revisions.length > 0 ? (
            <div className="space-y-3 max-h-96 overflow-y-auto">
              {revisions.map(rev => (
                <Card key={rev.id}>
                  <CardContent className="p-3 text-sm">
                    <div className="flex justify-between mb-1">
                      <Badge variant="outline">Revision #{rev.revisionNumber}</Badge>
                      <Badge className={STATUS_COLORS[rev.status] || "bg-gray-100"}>{rev.status}</Badge>
                    </div>
                    <p className="text-slate-700 mb-1">{rev.reason}</p>
                    <div className="grid grid-cols-4 gap-1 text-xs text-slate-500 mt-2">
                      <span>Q1: {rev.previousQ1Target} <ArrowRight className="w-3 h-3 inline" /> {rev.newQ1Target}</span>
                      <span>Q2: {rev.previousQ2Target} <ArrowRight className="w-3 h-3 inline" /> {rev.newQ2Target}</span>
                      <span>Q3: {rev.previousQ3Target} <ArrowRight className="w-3 h-3 inline" /> {rev.newQ3Target}</span>
                      <span>Q4: {rev.previousQ4Target} <ArrowRight className="w-3 h-3 inline" /> {rev.newQ4Target}</span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          ) : (
            <p className="text-sm text-slate-500 text-center py-4">No revisions recorded</p>
          )}
        </DialogContent>
      </Dialog>

      <Dialog open={!!showEdit} onOpenChange={() => setShowEdit(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Edit SDBIP Item</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div><Label>Description *</Label><Textarea value={editForm.description} onChange={e => setEditForm(p => ({ ...p, description: e.target.value }))} /></div>
            <div className="grid grid-cols-2 gap-3">
              <div><Label>Q1 Target</Label><Input value={editForm.q1Target} onChange={e => setEditForm(p => ({ ...p, q1Target: e.target.value }))} /></div>
              <div><Label>Q2 Target</Label><Input value={editForm.q2Target} onChange={e => setEditForm(p => ({ ...p, q2Target: e.target.value }))} /></div>
              <div><Label>Q3 Target</Label><Input value={editForm.q3Target} onChange={e => setEditForm(p => ({ ...p, q3Target: e.target.value }))} /></div>
              <div><Label>Q4 Target</Label><Input value={editForm.q4Target} onChange={e => setEditForm(p => ({ ...p, q4Target: e.target.value }))} /></div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowEdit(null)}>Cancel</Button>
            <Button onClick={handleUpdate} disabled={!editForm.description.trim()}>Save Changes</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
