// libs/ins/src/lib/features/org-planning/approve-sdbip.component.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { catchError, concatMap, finalize, from, of, tap, toArray } from 'rxjs';
import { ApiService } from '@ins-core/services/api.service';
import { ToastService } from '@ins-core/services/toast.service';
import { Cycle, Scorecard, ScorecardKpi, KpiQuarterTarget } from '@ins-core/models/domain.model';
import { User } from '@ins-core/models/user.model';
import { PageHeaderComponent } from '@ins-shared/components/page-header/page-header.component';
import { LoadingSpinnerComponent } from '@ins-shared/components/loading-spinner/loading-spinner.component';
import { StatusBadgeComponent } from '@ins-shared/components/status-badge/status-badge.component';
import { EmptyStateComponent } from '@ins-shared/components/empty-state/empty-state.component';
import { ReturnReasonDialogComponent } from './review-sdbip.component';

@Component({
  selector: 'app-approve-sdbip',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule, MatSelectModule, MatDialogModule,
    PageHeaderComponent, LoadingSpinnerComponent, StatusBadgeComponent, EmptyStateComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './approve-sdbip.component.html',
  styleUrls: ['./approve-sdbip.component.scss'],
})
export class ApproveSdbipComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  private readonly dialog = inject(MatDialog);

  loading = signal(true);
  cycles = signal<Cycle[]>([]);
  users = signal<User[]>([]);
  selectedCycleId = signal<number | null>(null);
  effectiveCycleId = computed<number | null>(() => this.selectedCycleId() ?? this.cycles()[0]?.id ?? null);

  allScorecards = signal<Scorecard[]>([]);
  scorecards = computed(() => this.allScorecards().filter((s) => s.status === 'Reviewed'));
  selectedScorecardId = signal<number | null>(null);
  selectedScorecard = computed(() => this.allScorecards().find((s) => s.id === this.selectedScorecardId()) ?? null);

  kpis = signal<ScorecardKpi[]>([]);
  expanded = signal<Record<number, boolean>>({});
  kpiTargets = signal<Record<number, KpiQuarterTarget[]>>({});
  approvalComments = '';
  isProcessing = signal(false);

  approvedKpis = computed(() => this.kpis().filter((k) => k.status === 'Approved'));
  reviewedKpis = computed(() => this.kpis().filter((k) => k.status === 'Reviewed'));
  allKpisApproved = computed(() => {
    const list = this.kpis();
    return list.length > 0 && list.every((k) => k.status === 'Approved');
  });

  ngOnInit() {
    this.api.get<Cycle[]>('/cycles').pipe(
      catchError(() => of([] as Cycle[])),
      tap((c) => this.cycles.set(Array.isArray(c) ? c : [])),
    ).subscribe(() => this.loadScorecards());
    this.api.get<User[]>('/auth/users').pipe(
      catchError(() => of([] as User[])),
      tap((u) => this.users.set(Array.isArray(u) ? u : [])),
    ).subscribe();
  }

  loadScorecards() {
    const cycleId = this.effectiveCycleId();
    if (!cycleId) { this.allScorecards.set([]); this.loading.set(false); return; }
    this.loading.set(true);
    this.api.get<Scorecard[]>('/scorecards', { cycleId }).pipe(
      catchError(() => of([] as Scorecard[])),
      tap((r) => this.allScorecards.set(Array.isArray(r) ? r : [])),
      finalize(() => this.loading.set(false)),
    ).subscribe();
  }

  selectCycle(id: number) { this.selectedCycleId.set(id); this.loadScorecards(); }

  openScorecard(sc: Scorecard) {
    this.selectedScorecardId.set(sc.id);
    this.expanded.set({});
    this.kpiTargets.set({});
    this.approvalComments = '';
    this.kpis.set([]);
    this.reloadKpis();
  }

  back() {
    this.selectedScorecardId.set(null);
    this.kpis.set([]);
    this.approvalComments = '';
  }

  private reloadKpis() {
    const sc = this.selectedScorecardId();
    if (!sc) return;
    this.api.get<ScorecardKpi[]>(`/scorecards/${sc}/kpis`).pipe(
      catchError(() => of([] as ScorecardKpi[])),
      tap((r) => this.kpis.set(Array.isArray(r) ? r : [])),
    ).subscribe();
  }

  toggleExpand(kpi: ScorecardKpi) {
    const cur = this.expanded();
    const next = { ...cur, [kpi.id]: !cur[kpi.id] };
    this.expanded.set(next);
    if (next[kpi.id] && !this.kpiTargets()[kpi.id]) {
      this.api.get<KpiQuarterTarget[]>(`/scorecard-kpis/${kpi.id}/quarter-targets`).pipe(
        catchError(() => of([] as KpiQuarterTarget[])),
        tap((r) => this.kpiTargets.set({ ...this.kpiTargets(), [kpi.id]: Array.isArray(r) ? r : [] })),
      ).subscribe();
    }
  }

  approveKpi(kpiId: number) {
    this.isProcessing.set(true);
    this.api.post(`/scorecard-kpis/${kpiId}/transition`, { action: 'approve', comments: '' }).pipe(
      tap(() => { this.toast.success('KPI Approved'); this.reloadKpis(); }),
      catchError((e) => { this.toast.error('Error', e?.error?.message ?? 'Failed to approve KPI'); return of(null); }),
      finalize(() => this.isProcessing.set(false)),
    ).subscribe();
  }

  approveAll() {
    const pending = this.reviewedKpis();
    if (pending.length === 0) return;
    this.isProcessing.set(true);
    from(pending).pipe(
      concatMap((k) => this.api.post(`/scorecard-kpis/${k.id}/transition`, { action: 'approve', comments: '' }).pipe(
        catchError(() => of({ __error: true } as const)),
      )),
      toArray(),
      tap((results) => {
        const failed = results.filter((r): r is { __error: true } => !!r && (r as { __error?: boolean }).__error === true).length;
        const ok = results.length - failed;
        if (failed === 0) this.toast.success(`${ok} KPI(s) approved`);
        else if (ok === 0) this.toast.error('Approval failed', `Could not approve ${failed} KPI(s).`);
        else this.toast.error('Partial success', `${ok} approved, ${failed} failed.`);
        this.reloadKpis();
      }),
      finalize(() => this.isProcessing.set(false)),
    ).subscribe();
  }

  approveScorecard() {
    const id = this.selectedScorecardId();
    if (!id || !this.allKpisApproved()) return;
    this.isProcessing.set(true);
    this.api.post(`/scorecards/${id}/transition`, { action: 'approve', comments: this.approvalComments }).pipe(
      tap(() => {
        this.toast.success('SDBIP Approved', 'Quarter targets are now baselined.');
        this.back();
        this.loadScorecards();
      }),
      catchError((e) => { this.toast.error('Error', e?.error?.message ?? 'Failed to approve scorecard'); return of(null); }),
      finalize(() => this.isProcessing.set(false)),
    ).subscribe();
  }

  returnScorecard() {
    const id = this.selectedScorecardId(); if (!id) return;
    this.dialog.open(ReturnReasonDialogComponent, { panelClass: 'plat-dialog' })
      .afterClosed().subscribe((reason) => {
        if (!reason) return;
        this.isProcessing.set(true);
        this.api.post(`/scorecards/${id}/transition`, { action: 'return', comments: reason }).pipe(
          tap(() => {
            this.toast.success('SDBIP returned', 'Returned to Draft for corrections.');
            this.back();
            this.loadScorecards();
          }),
          catchError((e) => { this.toast.error('Error', e?.error?.message ?? 'Failed to return scorecard'); return of(null); }),
          finalize(() => this.isProcessing.set(false)),
        ).subscribe();
      });
  }

  userName(id: number | null | undefined): string {
    if (!id) return '—';
    const u = this.users().find((x) => x.id === id);
    return u ? u.displayName : `User #${id}`;
  }

  formatDate(s: string | null | undefined): string {
    if (!s) return '';
    try { return new Date(s).toLocaleDateString(); } catch { return s; }
  }

  targetForQuarter(kpiId: number, q: number): KpiQuarterTarget | undefined {
    return this.kpiTargets()[kpiId]?.find((t) => t.quarter === q);
  }

  trackById(_: number, x: { id: number }): number { return x.id; }
}

<section class="plat-page">
  <ng-container *ngIf="selectedScorecardId() && selectedScorecard(); else queue">
    <div class="detail-head">
      <div class="left">
        <button mat-button (click)="back()"><mat-icon>arrow_back</mat-icon> Back to Queue</button>
        <div class="title-block">
          <h2>Approve: {{ selectedScorecard()!.name }}</h2>
          <p>
            Created by {{ userName(selectedScorecard()!.createdById) }}
            · <app-status-badge [status]="selectedScorecard()!.status"></app-status-badge>
          </p>
        </div>
      </div>
    </div>

    <div class="stats-grid">
      <div class="plat-card stat"><div class="stat-label">Total KPIs</div><div class="stat-value">{{ kpis().length }}</div></div>
      <div class="plat-card stat"><div class="stat-label">Approved</div><div class="stat-value tone-green">{{ approvedKpis().length }}</div></div>
      <div class="plat-card stat"><div class="stat-label">Pending Approval</div><div class="stat-value tone-amber">{{ reviewedKpis().length }}</div></div>
    </div>

    <div *ngIf="reviewedKpis().length > 0" class="bulk-row">
      <button mat-flat-button color="primary" [disabled]="isProcessing()" (click)="approveAll()">
        <mat-icon>done_all</mat-icon> Approve All Reviewed KPIs ({{ reviewedKpis().length }})
      </button>
    </div>

    <div class="plat-card">
      <div class="card-head">
        <h3>KPI Approval</h3>
        <p>Approve each KPI to finalise the scorecard. All KPIs must be approved before the scorecard can be approved.</p>
      </div>
      <div class="kpi-list">
        <div *ngIf="kpis().length === 0" class="empty">No KPIs found for this scorecard.</div>
        <div *ngFor="let k of kpis(); trackBy: trackById" class="kpi-card">
          <div class="kpi-row">
            <div class="kpi-body">
              <div class="kpi-meta-top">
                <span class="kpi-num">{{ k.kpiNumber }}</span>
                <app-status-badge [status]="k.status"></app-status-badge>
              </div>
              <div class="kpi-desc">{{ k.description }}</div>
              <div class="kpi-meta">
                <span>Weight: {{ k.weighting }}%</span>
                <span>Annual Target: {{ k.annualTarget }}</span>
                <span *ngIf="k.baseline">Baseline: {{ k.baseline }}</span>
                <span>Responsible: {{ userName(k.responsiblePostId) }}</span>
              </div>
            </div>
            <div class="kpi-side">
              <button *ngIf="k.status === 'Reviewed'" mat-flat-button color="primary" [disabled]="isProcessing()" (click)="approveKpi(k.id)">
                <mat-icon>check_circle</mat-icon> Approve
              </button>
              <span *ngIf="k.status === 'Approved'" class="status-line tone-green">
                <mat-icon>check_circle</mat-icon> Approved
              </span>
              <button mat-button (click)="toggleExpand(k)">{{ expanded()[k.id] ? 'Collapse' : 'Details' }}</button>
            </div>
          </div>

          <div *ngIf="expanded()[k.id]" class="kpi-expand">
            <div class="targets-row" *ngIf="kpiTargets()[k.id]?.length">
              <div *ngFor="let q of [1,2,3,4]" class="qcell">
                <div class="qlbl">Q{{ q }}</div>
                <div class="qval">{{ targetForQuarter(k.id, q)?.targetValue || '—' }}</div>
                <div *ngIf="targetForQuarter(k.id, q)?.budgetValue != null" class="qbudget">
                  Budget: R{{ targetForQuarter(k.id, q)!.budgetValue!.toLocaleString() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="plat-card decision-card green">
      <div class="card-head">
        <h3><mat-icon>verified_user</mat-icon> Final Scorecard Approval</h3>
        <p>{{ allKpisApproved()
          ? 'All KPIs have been approved. You may now approve the entire scorecard. This will baseline all quarterly targets.'
          : (reviewedKpis().length + ' KPI(s) still pending approval. Approve all KPIs before finalising the scorecard.') }}</p>
      </div>
      <mat-form-field appearance="outline">
        <mat-label>Approval Comments (Optional)</mat-label>
        <textarea matInput rows="3" [(ngModel)]="approvalComments" placeholder="Add any approval comments or directives..."></textarea>
      </mat-form-field>
      <div class="decision-actions">
        <button mat-flat-button color="primary" [disabled]="!allKpisApproved() || isProcessing()" (click)="approveScorecard()">
          <mat-icon>workspace_premium</mat-icon> Approve SDBIP
        </button>
        <button mat-stroked-button color="warn" [disabled]="isProcessing()" (click)="returnScorecard()">
          <mat-icon>cancel</mat-icon> Return to Draft
        </button>
      </div>
    </div>
  </ng-container>

  <ng-template #queue>
    <app-page-header title="Approve SDBIP" subtitle="PMS Director — approve reviewed scorecards. Approval baselines all quarterly targets." icon="verified_user" tone="green">
      <mat-form-field *ngIf="cycles().length > 0" appearance="outline" class="cycle-pick" subscriptSizing="dynamic">
        <mat-label>Cycle</mat-label>
        <mat-select [ngModel]="effectiveCycleId()" (ngModelChange)="selectCycle($event)">
          <mat-option *ngFor="let c of cycles(); trackBy: trackById" [value]="c.id">{{ c.financialYearLabel }}</mat-option>
        </mat-select>
      </mat-form-field>
    </app-page-header>

    <app-loading-spinner *ngIf="loading()"></app-loading-spinner>

    <ng-container *ngIf="!loading()">
      <div *ngIf="scorecards().length > 0; else noPending" class="queue-list">
        <div *ngFor="let sc of scorecards(); trackBy: trackById" class="plat-card queue-card" (click)="openScorecard(sc)">
          <div class="qc-body">
            <h3>{{ sc.name }}</h3>
            <p>Created by {{ userName(sc.createdById) }} · {{ formatDate(sc.createdAt) }}</p>
          </div>
          <div class="qc-right">
            <app-status-badge [status]="sc.status"></app-status-badge>
            <button mat-stroked-button color="primary"><mat-icon>verified_user</mat-icon> Approve</button>
          </div>
        </div>
      </div>
      <ng-template #noPending>
        <div class="plat-card">
          <app-empty-state icon="verified_user" title="No Scorecards Pending Approval" message="All reviewed scorecards have been approved for this cycle."></app-empty-state>
        </div>
      </ng-template>
    </ng-container>
  </ng-template>
</section>

// Insight-Performance-Hub/artifacts/perf-app/src/features/scorecards/ApproveSdbip.tsx
import { useState } from "react";
import {
  useListScorecards, useTransitionScorecard,
  useListScorecardKpis, useTransitionScorecardKpi,
  useListQuarterTargets, useListCycles, useListUsers,
} from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { useToast } from "@/core/hooks/use-toast";
import {
  CheckCircle2, XCircle, ArrowLeft, FileSearch, Eye,
  Loader2, ShieldCheck, Award,
} from "lucide-react";

const STATUS_COLORS: Record<string, string> = {
  Draft: "bg-gray-100 text-gray-700",
  Submitted: "bg-blue-100 text-blue-700",
  Reviewed: "bg-amber-100 text-amber-700",
  Approved: "bg-green-100 text-green-700",
};

export default function ApproveSdbip() {
  const { toast } = useToast();
  const { data: cycles } = useListCycles();
  const { data: users } = useListUsers();
  const [selectedCycleId, setSelectedCycleId] = useState<number | undefined>();
  const [selectedScorecardId, setSelectedScorecardId] = useState<number | undefined>();
  const [approvalComments, setApprovalComments] = useState("");
  const [showReturnDialog, setShowReturnDialog] = useState(false);
  const [returnReason, setReturnReason] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);

  const effectiveCycleId = selectedCycleId || cycles?.[0]?.id;
  const { data: allScorecards, refetch: refetchScorecards } = useListScorecards({ cycleId: effectiveCycleId });
  const kpisQuery = useListScorecardKpis(selectedScorecardId ?? 0);
  const kpis = selectedScorecardId ? kpisQuery.data : undefined;

  const scorecards = allScorecards?.filter(s => s.status === "Reviewed") ?? [];
  const selectedScorecard = allScorecards?.find(s => s.id === selectedScorecardId);

  const transitionScorecard = useTransitionScorecard();
  const transitionKpi = useTransitionScorecardKpi();

  const getUserName = (id: number | null) => {
    if (!id) return "—";
    const u = users?.find(u => u.id === id);
    return u ? u.displayName : `User #${id}`;
  };

  const handleApproveKpi = async (kpiId: number) => {
    setIsProcessing(true);
    try {
      await transitionKpi.mutateAsync({
        id: kpiId,
        data: { action: "approve", comments: "" },
      });
      toast({ title: "KPI Approved" });
      kpisQuery.refetch();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to approve KPI", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleApproveAllKpis = async () => {
    if (!kpis) return;
    setIsProcessing(true);
    try {
      const unapproved = kpis.filter(k => k.status === "Reviewed");
      for (const kpi of unapproved) {
        await transitionKpi.mutateAsync({
          id: kpi.id,
          data: { action: "approve", comments: "" },
        });
      }
      toast({ title: `${unapproved.length} KPI(s) approved` });
      kpisQuery.refetch();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to approve KPIs", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleApproveScorecard = async () => {
    if (!selectedScorecardId) return;
    setIsProcessing(true);
    try {
      await transitionScorecard.mutateAsync({
        id: selectedScorecardId,
        data: { action: "approve", comments: approvalComments },
      });
      toast({ title: "SDBIP Approved", description: "The scorecard has been officially approved. Quarter targets are now baselined." });
      setSelectedScorecardId(undefined);
      setApprovalComments("");
      refetchScorecards();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to approve scorecard", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleReturnScorecard = async () => {
    if (!selectedScorecardId) return;
    setIsProcessing(true);
    try {
      await transitionScorecard.mutateAsync({
        id: selectedScorecardId,
        data: { action: "return", comments: returnReason },
      });
      toast({ title: "SDBIP returned", description: "The scorecard has been returned to Draft for corrections." });
      setSelectedScorecardId(undefined);
      setReturnReason("");
      setShowReturnDialog(false);
      refetchScorecards();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to return scorecard", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const approvedKpis = kpis?.filter(k => k.status === "Approved") ?? [];
  const reviewedKpis = kpis?.filter(k => k.status === "Reviewed") ?? [];
  const allKpisApproved = kpis && kpis.length > 0 && kpis.every(k => k.status === "Approved");

  if (selectedScorecardId && selectedScorecard) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => { setSelectedScorecardId(undefined); setApprovalComments(""); }}>
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Queue
          </Button>
          <div className="flex-1">
            <h1 className="text-2xl font-bold text-slate-800">Approve: {selectedScorecard.name}</h1>
            <p className="text-slate-500">
              Status: <Badge className={STATUS_COLORS[selectedScorecard.status]}>{selectedScorecard.status}</Badge>
              {" · "}Created by {getUserName(selectedScorecard.createdById)}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-4">
          <Card>
            <CardContent className="pt-4">
              <div className="text-sm text-slate-500">Total KPIs</div>
              <div className="text-2xl font-bold">{kpis?.length ?? 0}</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-4">
              <div className="text-sm text-slate-500">Approved</div>
              <div className="text-2xl font-bold text-green-600">{approvedKpis.length}</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-4">
              <div className="text-sm text-slate-500">Pending Approval</div>
              <div className="text-2xl font-bold text-amber-600">{reviewedKpis.length}</div>
            </CardContent>
          </Card>
        </div>

        {reviewedKpis.length > 0 && (
          <div className="flex justify-end">
            <Button onClick={handleApproveAllKpis} disabled={isProcessing} className="bg-green-600 hover:bg-green-700">
              {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <CheckCircle2 className="w-4 h-4 mr-2" />}
              Approve All Reviewed KPIs ({reviewedKpis.length})
            </Button>
          </div>
        )}

        <Card>
          <CardHeader>
            <CardTitle>KPI Approval</CardTitle>
            <CardDescription>Approve each KPI to finalize the scorecard. All KPIs must be approved before the scorecard can be approved.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {kpis?.map(kpi => (
                <KpiApprovalCard
                  key={kpi.id}
                  kpi={kpi}
                  onApprove={() => handleApproveKpi(kpi.id)}
                  isProcessing={isProcessing}
                  getUserName={getUserName}
                />
              ))}
              {(!kpis || kpis.length === 0) && (
                <p className="text-center text-slate-400 py-8">No KPIs found for this scorecard.</p>
              )}
            </div>
          </CardContent>
        </Card>

        <Card className="border-green-200 bg-green-50/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-green-600" />
              Final Scorecard Approval
            </CardTitle>
            <CardDescription>
              {allKpisApproved
                ? "All KPIs have been approved. You may now approve the entire scorecard. This will baseline all quarterly targets."
                : `${reviewedKpis.length} KPI(s) still pending approval. Approve all KPIs before finalizing the scorecard.`}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Approval Comments (Optional)</Label>
              <Textarea
                value={approvalComments}
                onChange={e => setApprovalComments(e.target.value)}
                placeholder="Add any approval comments or directives..."
                rows={3}
              />
            </div>
            <div className="flex gap-3">
              <Button
                onClick={handleApproveScorecard}
                disabled={!allKpisApproved || isProcessing}
                className="bg-green-600 hover:bg-green-700"
              >
                {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Award className="w-4 h-4 mr-2" />}
                Approve SDBIP
              </Button>
              <Button
                variant="outline"
                onClick={() => setShowReturnDialog(true)}
                disabled={isProcessing}
                className="border-red-300 text-red-600 hover:bg-red-50"
              >
                <XCircle className="w-4 h-4 mr-2" /> Return to Draft
              </Button>
            </div>
          </CardContent>
        </Card>

        <Dialog open={showReturnDialog} onOpenChange={setShowReturnDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Return Scorecard to Draft</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <Label>Reason for Return *</Label>
                <Textarea
                  value={returnReason}
                  onChange={e => setReturnReason(e.target.value)}
                  placeholder="Explain what needs to be corrected..."
                  rows={4}
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowReturnDialog(false)}>Cancel</Button>
              <Button
                onClick={handleReturnScorecard}
                disabled={!returnReason.trim() || isProcessing}
                className="bg-red-600 hover:bg-red-700"
              >
                {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <XCircle className="w-4 h-4 mr-2" />}
                Return to Draft
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800">Approve SDBIP — PMS Director</h1>
        <p className="text-slate-500 mt-1">Approve reviewed scorecards to finalize the SDBIP. Approval baselines all quarterly targets.</p>
      </div>

      <div className="flex items-center gap-4">
        <div className="w-64">
          <Label>Performance Cycle</Label>
          <Select value={String(effectiveCycleId ?? "")} onValueChange={v => setSelectedCycleId(Number(v))}>
            <SelectTrigger><SelectValue placeholder="Select cycle" /></SelectTrigger>
            <SelectContent>
              {cycles?.map(c => <SelectItem key={c.id} value={String(c.id)}>{c.financialYearLabel}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>

      {scorecards.length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center">
            <FileSearch className="w-12 h-12 text-slate-300 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-slate-600">No Scorecards Pending Approval</h3>
            <p className="text-slate-400 mt-1">All reviewed scorecards have been approved for this cycle.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {scorecards.map(sc => (
            <Card key={sc.id} className="hover:shadow-md transition-shadow cursor-pointer" onClick={() => setSelectedScorecardId(sc.id)}>
              <CardContent className="py-4 flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-slate-800">{sc.name}</h3>
                  <p className="text-sm text-slate-500">
                    Created by {getUserName(sc.createdById)} · {new Date(sc.createdAt).toLocaleDateString()}
                  </p>
                </div>
                <div className="flex items-center gap-3">
                  <Badge className={STATUS_COLORS[sc.status]}>{sc.status}</Badge>
                  <Button size="sm" variant="outline" className="border-green-300 text-green-700 hover:bg-green-50">
                    <ShieldCheck className="w-4 h-4 mr-1" /> Approve
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function KpiApprovalCard({
  kpi,
  onApprove,
  isProcessing,
  getUserName,
}: {
  kpi: any;
  onApprove: () => void;
  isProcessing: boolean;
  getUserName: (id: number | null) => string;
}) {
  const [expanded, setExpanded] = useState(false);
  const targetsQuery = useListQuarterTargets(expanded ? kpi.id : 0);
  const targets = expanded ? targetsQuery.data : undefined;

  return (
    <div className="border rounded-lg p-4 space-y-3">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className="font-mono text-sm text-slate-500">{kpi.kpiNumber}</span>
            <Badge className={STATUS_COLORS[kpi.status]}>{kpi.status}</Badge>
          </div>
          <p className="font-medium text-slate-800 mt-1">{kpi.description}</p>
          <div className="flex gap-6 mt-2 text-sm text-slate-500">
            <span>Weight: {kpi.weighting}%</span>
            <span>Annual Target: {kpi.annualTarget}</span>
            {kpi.baseline && <span>Baseline: {kpi.baseline}</span>}
            <span>Responsible: {getUserName(kpi.responsiblePostId)}</span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {kpi.status === "Reviewed" && (
            <Button size="sm" onClick={onApprove} disabled={isProcessing} className="bg-green-600 hover:bg-green-700">
              <CheckCircle2 className="w-3 h-3 mr-1" /> Approve
            </Button>
          )}
          {kpi.status === "Approved" && (
            <span className="flex items-center gap-1 text-sm text-green-600">
              <CheckCircle2 className="w-4 h-4" /> Approved
            </span>
          )}
          <Button variant="ghost" size="sm" onClick={() => setExpanded(!expanded)}>
            {expanded ? "Collapse" : "Details"}
          </Button>
        </div>
      </div>

      {expanded && targets && targets.length > 0 && (
        <div className="pt-2 border-t">
          <div className="grid grid-cols-4 gap-2">
            {[1, 2, 3, 4].map(q => {
              const t = targets.find((t: any) => t.quarter === q);
              return (
                <div key={q} className="bg-slate-50 rounded p-2 text-sm">
                  <div className="font-medium text-slate-600">Q{q}</div>
                  <div className="text-slate-800">{t?.targetValue ?? "—"}</div>
                  {t?.budgetValue != null && <div className="text-xs text-slate-400">Budget: R{t.budgetValue.toLocaleString()}</div>}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
