// Insight-Performance-Hub/artifacts/perf-app/src/features/ai/AiInsights.tsx
import { useState, useEffect } from "react";
import {
  useGetAiDashboard, useGetAtRiskKpis, useGetNarrativeSummary,
  useGetEvidenceGaps, useGetAlignmentCheck, useListAiInsightLog,
  useListCycles,
} from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AlertTriangle, TrendingUp, FileSearch, Link2, Brain, Activity } from "lucide-react";

const RISK_COLORS: Record<string, string> = {
  high: "bg-red-100 text-red-700",
  medium: "bg-yellow-100 text-yellow-700",
  low: "bg-green-100 text-green-700",
};

export default function AiInsights() {
  const { data: cycles } = useListCycles();
  const [selectedCycleId, setSelectedCycleId] = useState<number | undefined>();

  useEffect(() => {
    if (cycles && cycles.length > 0 && !selectedCycleId) {
      const open = cycles.find(c => c.status === "Open");
      setSelectedCycleId((open ?? cycles[0]).id);
    }
  }, [cycles]);

  const cycleId = selectedCycleId || 0;

  const { data: dashboard } = useGetAiDashboard({ cycleId: cycleId || 0 });
  const { data: atRisk } = useGetAtRiskKpis({ cycleId: cycleId || 0 });
  const { data: narrative } = useGetNarrativeSummary({ cycleId: cycleId || 0 });
  const { data: gaps } = useGetEvidenceGaps({ cycleId: cycleId || 0 });
  const { data: alignment } = useGetAlignmentCheck({ cycleId: cycleId || 0 });
  const { data: logs } = useListAiInsightLog({ cycleId: selectedCycleId });

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <Brain className="w-7 h-7 text-purple-600" /> AI Advisory Dashboard
          </h1>
          <p className="text-slate-500 mt-1">AI-powered performance analytics and advisory insights</p>
        </div>
        <Select value={selectedCycleId ? String(selectedCycleId) : "none"} onValueChange={v => setSelectedCycleId(v === "none" ? undefined : Number(v))}>
          <SelectTrigger className="w-[220px]"><SelectValue placeholder="Select cycle" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="none">Select Cycle</SelectItem>
            {cycles?.map(c => <SelectItem key={c.id} value={String(c.id)}>{c.financialYearLabel}</SelectItem>)}
          </SelectContent>
        </Select>
      </div>

      {!selectedCycleId ? (
        <Card><CardContent className="py-16 text-center text-slate-400">
          <Brain className="w-12 h-12 mx-auto mb-4 text-slate-300" />
          <p className="text-lg font-medium">Select a performance cycle to generate AI insights</p>
        </CardContent></Card>
      ) : (
        <>
          <div className="grid grid-cols-4 gap-4">
            <Card className="border-l-4 border-l-red-500">
              <CardContent className="pt-4">
                <p className="text-sm text-slate-500">High Risk KPIs</p>
                <p className="text-3xl font-bold text-red-600">{dashboard?.riskSummary?.high ?? 0}</p>
              </CardContent>
            </Card>
            <Card className="border-l-4 border-l-yellow-500">
              <CardContent className="pt-4">
                <p className="text-sm text-slate-500">Medium Risk KPIs</p>
                <p className="text-3xl font-bold text-yellow-600">{dashboard?.riskSummary?.medium ?? 0}</p>
              </CardContent>
            </Card>
            <Card className="border-l-4 border-l-green-500">
              <CardContent className="pt-4">
                <p className="text-sm text-slate-500">On Track</p>
                <p className="text-3xl font-bold text-green-600">{dashboard?.riskSummary?.low ?? 0}</p>
              </CardContent>
            </Card>
            <Card className="border-l-4 border-l-purple-500">
              <CardContent className="pt-4">
                <p className="text-sm text-slate-500">Alignment Score</p>
                <p className="text-3xl font-bold text-purple-600">{alignment?.overallScore ?? "—"}%</p>
              </CardContent>
            </Card>
          </div>

          {dashboard?.topRecommendations && dashboard.topRecommendations.length > 0 && (
            <Card className="bg-purple-50 border-purple-200">
              <CardContent className="pt-4">
                <p className="text-sm font-semibold text-purple-700 mb-2">Top Recommendations</p>
                <ul className="space-y-1">
                  {dashboard.topRecommendations.map((r, i) => (
                    <li key={i} className="text-sm text-purple-800 flex items-start gap-2">
                      <span className="text-purple-400 mt-0.5">•</span> {r}
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}

          <Tabs defaultValue="risk">
            <TabsList>
              <TabsTrigger value="risk"><AlertTriangle className="w-4 h-4 mr-1" /> At-Risk KPIs</TabsTrigger>
              <TabsTrigger value="narrative"><TrendingUp className="w-4 h-4 mr-1" /> Narrative</TabsTrigger>
              <TabsTrigger value="evidence"><FileSearch className="w-4 h-4 mr-1" /> Evidence Gaps</TabsTrigger>
              <TabsTrigger value="alignment"><Link2 className="w-4 h-4 mr-1" /> Alignment</TabsTrigger>
              <TabsTrigger value="log"><Activity className="w-4 h-4 mr-1" /> Insight Log</TabsTrigger>
            </TabsList>

            <TabsContent value="risk" className="mt-4">
              <Card>
                <CardHeader><CardTitle>At-Risk KPI Analysis</CardTitle></CardHeader>
                <CardContent>
                  {atRisk?.summary && <p className="text-sm text-slate-600 mb-4 bg-slate-50 p-3 rounded">{atRisk.summary}</p>}
                  {!atRisk?.atRiskKpis?.length ? (
                    <p className="text-slate-400 text-center py-4">No at-risk KPIs detected</p>
                  ) : (
                    <div className="space-y-3">
                      {atRisk.atRiskKpis.map((k, i) => (
                        <div key={i} className="p-4 border rounded-lg">
                          <div className="flex items-center justify-between mb-2">
                            <p className="font-medium text-slate-800">{k.kpiDescription}</p>
                            <Badge className={RISK_COLORS[k.riskLevel || "low"]}>{k.riskLevel}</Badge>
                          </div>
                          <p className="text-sm text-slate-500">{k.department} — Score: {k.currentScore ?? "N/A"}</p>
                          <p className="text-sm text-slate-600 mt-1">{k.reason}</p>
                          <p className="text-sm text-blue-600 mt-1 font-medium">{k.recommendation}</p>
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="narrative" className="mt-4">
              <Card>
                <CardHeader><CardTitle>Executive Narrative Summary</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                  {narrative?.narrative && <p className="text-slate-700 bg-slate-50 p-4 rounded-lg leading-relaxed">{narrative.narrative}</p>}
                  {narrative?.highlights && narrative.highlights.length > 0 && (
                    <div>
                      <p className="text-sm font-semibold text-green-700 mb-1">Highlights</p>
                      {narrative.highlights.map((h, i) => <p key={i} className="text-sm text-slate-600">✓ {h}</p>)}
                    </div>
                  )}
                  {narrative?.concerns && narrative.concerns.length > 0 && (
                    <div>
                      <p className="text-sm font-semibold text-red-700 mb-1">Concerns</p>
                      {narrative.concerns.map((c, i) => <p key={i} className="text-sm text-slate-600">⚠ {c}</p>)}
                    </div>
                  )}
                  {narrative?.recommendations && narrative.recommendations.length > 0 && (
                    <div>
                      <p className="text-sm font-semibold text-blue-700 mb-1">Recommendations</p>
                      {narrative.recommendations.map((r, i) => <p key={i} className="text-sm text-slate-600">→ {r}</p>)}
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="evidence" className="mt-4">
              <Card>
                <CardHeader><CardTitle>Evidence Gap Analysis</CardTitle></CardHeader>
                <CardContent>
                  {gaps?.summary && <p className="text-sm text-slate-600 mb-4 bg-slate-50 p-3 rounded">{gaps.summary}</p>}
                  {!gaps?.gaps?.length ? (
                    <p className="text-slate-400 text-center py-4">No evidence gaps detected</p>
                  ) : (
                    <table className="w-full text-sm">
                      <thead><tr className="border-b text-slate-500"><th className="text-left py-2 px-2">KPI</th><th className="text-left py-2 px-2">Department</th><th className="text-left py-2 px-2">Quarter</th><th className="text-left py-2 px-2">Gap</th><th className="text-left py-2 px-2">Severity</th><th className="text-left py-2 px-2">Suggestion</th></tr></thead>
                      <tbody>
                        {gaps.gaps.map((g, i) => (
                          <tr key={i} className="border-b last:border-0 hover:bg-slate-50">
                            <td className="py-2 px-2">{g.kpiDescription}</td>
                            <td className="py-2 px-2">{g.department}</td>
                            <td className="py-2 px-2">Q{g.quarter}</td>
                            <td className="py-2 px-2"><Badge variant="outline">{g.gapType}</Badge></td>
                            <td className="py-2 px-2"><Badge className={RISK_COLORS[g.severity || "low"]}>{g.severity}</Badge></td>
                            <td className="py-2 px-2 text-xs text-slate-500">{g.suggestion}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="alignment" className="mt-4">
              <Card>
                <CardHeader><CardTitle>Cross-Module Alignment Check</CardTitle></CardHeader>
                <CardContent>
                  {alignment?.summary && <p className="text-sm text-slate-600 mb-4 bg-slate-50 p-3 rounded">{alignment.summary}</p>}
                  {!alignment?.alignmentIssues?.length ? (
                    <p className="text-slate-400 text-center py-4">No alignment issues detected</p>
                  ) : (
                    <div className="space-y-3">
                      {alignment.alignmentIssues.map((issue, i) => (
                        <div key={i} className="p-4 border rounded-lg">
                          <div className="flex items-center justify-between mb-2">
                            <p className="font-medium text-slate-800">{issue.sourceModule} → {issue.targetModule}</p>
                            <Badge className={RISK_COLORS[issue.severity || "low"]}>{issue.severity}</Badge>
                          </div>
                          <p className="text-sm text-slate-600">{issue.issue}</p>
                          <p className="text-sm text-blue-600 mt-1">{issue.recommendation}</p>
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="log" className="mt-4">
              <Card>
                <CardHeader><CardTitle>AI Insight Log</CardTitle></CardHeader>
                <CardContent>
                  {!logs?.length ? (
                    <p className="text-slate-400 text-center py-4">No insights generated yet</p>
                  ) : (
                    <table className="w-full text-sm">
                      <thead><tr className="border-b text-slate-500"><th className="text-left py-2 px-2">Type</th><th className="text-left py-2 px-2">Summary</th><th className="text-left py-2 px-2">Risk</th><th className="text-left py-2 px-2">Generated</th></tr></thead>
                      <tbody>
                        {logs.map(l => (
                          <tr key={l.id} className="border-b last:border-0 hover:bg-slate-50">
                            <td className="py-2 px-2"><Badge variant="outline">{l.insightType}</Badge></td>
                            <td className="py-2 px-2 text-slate-600">{l.summary || "—"}</td>
                            <td className="py-2 px-2">{l.riskLevel ? <Badge className={RISK_COLORS[l.riskLevel]}>{l.riskLevel}</Badge> : "—"}</td>
                            <td className="py-2 px-2 text-xs text-slate-400">{l.createdAt}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </>
      )}
    </div>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/ai/ai-insights.component.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatTabsModule } from '@angular/material/tabs';
import { catchError, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import {
  AiDashboard, AiInsightLog, AlignmentCheckResponse, AtRiskKpisResponse, Cycle,
  EvidenceGapsResponse, NarrativeSummary,
} from '@core/models/domain.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';

@Component({
  selector: 'app-ai-insights',
  standalone: true,
  imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatFormFieldModule, MatSelectModule, MatTabsModule, PageHeaderComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="plat-page">
      <app-page-header title="AI Advisory Dashboard" subtitle="AI-powered performance analytics and advisory insights." icon="psychology" tone="purple">
        <mat-form-field appearance="outline" class="cycle-pick">
          <mat-label>Cycle</mat-label>
          <mat-select [ngModel]="cycleId()" (ngModelChange)="onCycle($event)">
            <mat-option [value]="null">Select cycle</mat-option>
            <mat-option *ngFor="let c of cycles()" [value]="c.id">{{ c.financialYearLabel }}</mat-option>
          </mat-select>
        </mat-form-field>
      </app-page-header>

      <div *ngIf="!cycleId()" class="plat-card empty-cycle">
        <mat-icon>psychology</mat-icon>
        <p>Select a performance cycle to generate AI insights.</p>
      </div>

      <ng-container *ngIf="cycleId()">
        <div class="kpi-grid">
          <div class="plat-card kpi red"><span>High Risk KPIs</span><strong>{{ dashboard()?.riskSummary?.high ?? 0 }}</strong></div>
          <div class="plat-card kpi yellow"><span>Medium Risk KPIs</span><strong>{{ dashboard()?.riskSummary?.medium ?? 0 }}</strong></div>
          <div class="plat-card kpi green"><span>On Track</span><strong>{{ dashboard()?.riskSummary?.low ?? 0 }}</strong></div>
          <div class="plat-card kpi violet"><span>Alignment Score</span><strong>{{ alignment()?.overallScore ?? '—' }}%</strong></div>
        </div>

        <div class="plat-card recs" *ngIf="(dashboard()?.topRecommendations?.length ?? 0) > 0">
          <p class="recs__head">Top Recommendations</p>
          <ul><li *ngFor="let r of dashboard()?.topRecommendations">{{ r }}</li></ul>
        </div>

        <mat-tab-group class="tabs">
          <mat-tab label="At-Risk KPIs">
            <div class="tab-body">
              <p class="muted-box" *ngIf="atRisk()?.summary">{{ atRisk()?.summary }}</p>
              <p class="empty" *ngIf="!atRisk()?.atRiskKpis?.length">No at-risk KPIs detected</p>
              <div class="card-list">
                <div class="row" *ngFor="let k of atRisk()?.atRiskKpis ?? []">
                  <div class="row__head"><strong>{{ k.kpiDescription }}</strong><span class="badge" [class]="'risk-' + (k.riskLevel || 'low')">{{ k.riskLevel }}</span></div>
                  <p class="muted">{{ k.department }} — Score: {{ k.currentScore ?? 'N/A' }}</p>
                  <p>{{ k.reason }}</p>
                  <p class="rec">{{ k.recommendation }}</p>
                </div>
              </div>
            </div>
          </mat-tab>

          <mat-tab label="Narrative">
            <div class="tab-body">
              <p class="muted-box" *ngIf="narrative()?.narrative">{{ narrative()?.narrative }}</p>
              <ng-container *ngIf="(narrative()?.highlights?.length ?? 0) > 0">
                <p class="section-head green">Highlights</p>
                <p *ngFor="let h of narrative()?.highlights">✓ {{ h }}</p>
              </ng-container>
              <ng-container *ngIf="(narrative()?.concerns?.length ?? 0) > 0">
                <p class="section-head red">Concerns</p>
                <p *ngFor="let c of narrative()?.concerns">⚠ {{ c }}</p>
              </ng-container>
              <ng-container *ngIf="(narrative()?.recommendations?.length ?? 0) > 0">
                <p class="section-head blue">Recommendations</p>
                <p *ngFor="let r of narrative()?.recommendations">→ {{ r }}</p>
              </ng-container>
            </div>
          </mat-tab>

          <mat-tab label="Evidence Gaps">
            <div class="tab-body">
              <p class="muted-box" *ngIf="gaps()?.summary">{{ gaps()?.summary }}</p>
              <p class="empty" *ngIf="!gaps()?.gaps?.length">No evidence gaps detected</p>
              <table class="plat-table" *ngIf="gaps()?.gaps?.length">
                <thead><tr><th>KPI</th><th>Department</th><th>Quarter</th><th>Gap</th><th>Severity</th><th>Suggestion</th></tr></thead>
                <tbody>
                  <tr *ngFor="let g of gaps()?.gaps">
                    <td>{{ g.kpiDescription }}</td>
                    <td>{{ g.department }}</td>
                    <td>Q{{ g.quarter }}</td>
                    <td><span class="chip">{{ g.gapType }}</span></td>
                    <td><span class="badge" [class]="'risk-' + (g.severity || 'low')">{{ g.severity }}</span></td>
                    <td class="muted">{{ g.suggestion }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </mat-tab>

          <mat-tab label="Alignment">
            <div class="tab-body">
              <p class="muted-box" *ngIf="alignment()?.summary">{{ alignment()?.summary }}</p>
              <p class="empty" *ngIf="!alignment()?.alignmentIssues?.length">No alignment issues detected</p>
              <div class="card-list">
                <div class="row" *ngFor="let i of alignment()?.alignmentIssues ?? []">
                  <div class="row__head"><strong>{{ i.sourceModule }} → {{ i.targetModule }}</strong><span class="badge" [class]="'risk-' + (i.severity || 'low')">{{ i.severity }}</span></div>
                  <p>{{ i.issue }}</p>
                  <p class="rec">{{ i.recommendation }}</p>
                </div>
              </div>
            </div>
          </mat-tab>

          <mat-tab label="Insight Log">
            <div class="tab-body">
              <p class="empty" *ngIf="!logs().length">No insights generated yet</p>
              <table class="plat-table" *ngIf="logs().length">
                <thead><tr><th>Type</th><th>Summary</th><th>Risk</th><th>Generated</th></tr></thead>
                <tbody>
                  <tr *ngFor="let l of logs()">
                    <td><span class="chip">{{ l.insightType }}</span></td>
                    <td class="muted">{{ l.summary || '—' }}</td>
                    <td><span *ngIf="l.riskLevel" class="badge" [class]="'risk-' + l.riskLevel">{{ l.riskLevel }}</span><span *ngIf="!l.riskLevel">—</span></td>
                    <td class="muted">{{ l.createdAt }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </mat-tab>
        </mat-tab-group>
      </ng-container>
    </section>
  `,
  styles: [`
    .cycle-pick { width: 220px; }
    .empty-cycle { padding: 64px; text-align: center; color: #94a3b8; }
    .empty-cycle mat-icon { font-size: 48px; width: 48px; height: 48px; margin-bottom: 12px; color: #cbd5e1; }
    .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 16px; }
    .kpi { padding: 14px 18px; border-left: 4px solid; }
    .kpi span { color: #64748b; font-size: 12px; }
    .kpi strong { display: block; font-size: 28px; margin-top: 4px; }
    .kpi.red { border-color: #ef4444; } .kpi.red strong { color: #dc2626; }
    .kpi.yellow { border-color: #eab308; } .kpi.yellow strong { color: #ca8a04; }
    .kpi.green { border-color: #22c55e; } .kpi.green strong { color: #16a34a; }
    .kpi.violet { border-color: #8b5cf6; } .kpi.violet strong { color: #7c3aed; }
    .recs { background: #faf5ff; border: 1px solid #e9d5ff; padding: 14px 18px; margin-bottom: 16px; }
    .recs__head { color: #7e22ce; font-weight: 600; margin: 0 0 6px; font-size: 13px; }
    .recs ul { margin: 0; padding-left: 18px; color: #6b21a8; font-size: 13px; }
    .tabs { background: var(--plat-surface); border-radius: 16px; box-shadow: var(--plat-shadow-sm); }
    .tab-body { padding: 18px; }
    .muted-box { background: #f8fafc; padding: 12px; border-radius: 8px; color: #475569; font-size: 13px; }
    .empty { text-align: center; color: #94a3b8; padding: 24px; }
    .card-list { display: flex; flex-direction: column; gap: 12px; }
    .row { border: 1px solid var(--plat-border); border-radius: 12px; padding: 12px 16px; }
    .row__head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
    .row p { margin: 4px 0; font-size: 13px; color: #475569; }
    .row .rec { color: #2563eb; font-weight: 500; }
    .section-head { font-weight: 600; font-size: 13px; margin: 12px 0 4px; }
    .section-head.green { color: #15803d; } .section-head.red { color: #b91c1c; } .section-head.blue { color: #1d4ed8; }
    .badge { padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; text-transform: capitalize; }
    .risk-high { background:#fee2e2; color:#b91c1c; }
    .risk-medium { background:#fef9c3; color:#a16207; }
    .risk-low { background:#dcfce7; color:#15803d; }
    .chip { display: inline-block; padding: 1px 8px; border: 1px solid var(--plat-border); border-radius: 999px; font-size: 11px; }
  `],
})
export class AiInsightsComponent implements OnInit {
  private readonly api = inject(ApiService);
  cycles = signal<Cycle[]>([]);
  cycleId = signal<number | null>(null);
  dashboard = signal<AiDashboard | null>(null);
  atRisk = signal<AtRiskKpisResponse | null>(null);
  narrative = signal<NarrativeSummary | null>(null);
  gaps = signal<EvidenceGapsResponse | null>(null);
  alignment = signal<AlignmentCheckResponse | null>(null);
  logs = signal<AiInsightLog[]>([]);
  // expose computed to keep tree-shaking honest
  readonly _dummy = computed(() => this.cycleId());

  ngOnInit() {
    this.api.get<Cycle[]>('/cycles').pipe(catchError(() => of([] as Cycle[]))).subscribe((cs) => {
      const arr = Array.isArray(cs) ? cs : [];
      this.cycles.set(arr);
      const def = arr.find((c) => c.status === 'Open') ?? arr[0];
      if (def) { this.cycleId.set(def.id); this.loadAll(); }
    });
  }
  onCycle(id: number | null) { this.cycleId.set(id); if (id) this.loadAll(); }
  loadAll() {
    const id = this.cycleId(); if (!id) return;
    const params = { cycleId: id };
    this.api.get<AiDashboard>('/ai-insights/dashboard', params).pipe(catchError(() => of(null))).subscribe((d) => this.dashboard.set(d));
    this.api.get<AtRiskKpisResponse>('/ai-insights/at-risk-kpis', params).pipe(catchError(() => of(null))).subscribe((r) => this.atRisk.set(r));
    this.api.get<NarrativeSummary>('/ai-insights/narrative-summary', params).pipe(catchError(() => of(null))).subscribe((n) => this.narrative.set(n));
    this.api.get<EvidenceGapsResponse>('/ai-insights/evidence-gaps', params).pipe(catchError(() => of(null))).subscribe((g) => this.gaps.set(g));
    this.api.get<AlignmentCheckResponse>('/ai-insights/alignment-check', params).pipe(catchError(() => of(null))).subscribe((a) => this.alignment.set(a));
    this.api.get<AiInsightLog[]>('/ai-insights/log', params).pipe(catchError(() => of([] as AiInsightLog[]))).pipe(tap((l) => this.logs.set(Array.isArray(l) ? l : []))).subscribe();
  }
}
