// Insight-Performance-Hub/artifacts/perf-app/src/features/integrations/IntegrationHub.tsx
import { useState } from "react";
import {
  useListIntegrationSyncLog, useTriggerHrSync, useTriggerBudgetPull,
  useTriggerProjectSync, useListIdpObjectives, useListCycles,
} from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/core/hooks/use-toast";
import { RefreshCw, Database, Users, Link2, Search } from "lucide-react";

function getErrorMessage(e: unknown): string {
  if (e && typeof e === "object") {
    const obj = e as Record<string, unknown>;
    if (obj.response && typeof obj.response === "object") {
      const resp = obj.response as Record<string, unknown>;
      if (resp.data && typeof resp.data === "object") {
        const data = resp.data as Record<string, unknown>;
        if (typeof data.error === "string") return data.error;
      }
    }
    if (obj.message && typeof obj.message === "string") return obj.message;
  }
  return "An error occurred";
}

const STATUS_COLORS: Record<string, string> = {
  Completed: "bg-green-100 text-green-700",
  Pending: "bg-yellow-100 text-yellow-700",
  Failed: "bg-red-100 text-red-700",
};

export default function IntegrationHub() {
  const { toast } = useToast();
  const { data: cycles } = useListCycles();
  const [syncFilter, setSyncFilter] = useState<string | undefined>();
  const [idpSearch, setIdpSearch] = useState("");
  const [budgetCycleId, setBudgetCycleId] = useState<number | undefined>();

  const { data: syncLog, refetch: refetchLog } = useListIntegrationSyncLog({ integrationType: syncFilter });
  const { data: idpObjectives } = useListIdpObjectives({ search: idpSearch });
  const hrSync = useTriggerHrSync();
  const budgetPull = useTriggerBudgetPull();
  const projectSync = useTriggerProjectSync();

  const handleHrSync = async () => {
    try {
      const result = await hrSync.mutateAsync();
      toast({ title: "HR Sync", description: (result as Record<string, string>).message || "Sync completed" });
      refetchLog();
    } catch (e: unknown) {
      toast({ title: "Error", description: getErrorMessage(e), variant: "destructive" });
    }
  };

  const handleProjectSync = async () => {
    try {
      const result = await projectSync.mutateAsync();
      toast({ title: "Project Sync", description: (result as Record<string, string>).message || "Sync completed" });
      refetchLog();
    } catch (e: unknown) {
      toast({ title: "Error", description: getErrorMessage(e), variant: "destructive" });
    }
  };

  const handleBudgetPull = async () => {
    if (!budgetCycleId) return;
    try {
      const result = await budgetPull.mutateAsync({ data: { cycleId: budgetCycleId } });
      toast({ title: "Budget Pull", description: (result as Record<string, string>).message || "Pull completed" });
      refetchLog();
    } catch (e: unknown) {
      toast({ title: "Error", description: getErrorMessage(e), variant: "destructive" });
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <Link2 className="w-7 h-7 text-blue-600" /> Integration Hub
          </h1>
          <p className="text-slate-500 mt-1">Manage external system integrations and data synchronisation</p>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardHeader><CardTitle className="text-lg flex items-center gap-2"><Users className="w-5 h-5" /> HR System</CardTitle></CardHeader>
          <CardContent>
            <p className="text-sm text-slate-500 mb-4">Sync employee data, post details, and organisational structure from your HR system.</p>
            <Button onClick={handleHrSync} disabled={hrSync.isPending}>
              <RefreshCw className={`w-4 h-4 mr-1 ${hrSync.isPending ? "animate-spin" : ""}`} /> Sync Now
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle className="text-lg flex items-center gap-2"><Database className="w-5 h-5" /> mSCOA Budget</CardTitle></CardHeader>
          <CardContent>
            <p className="text-sm text-slate-500 mb-3">Pull budget values for budget-linked KPIs from the mSCOA system.</p>
            <div className="flex gap-2">
              <Select value={budgetCycleId ? String(budgetCycleId) : "none"} onValueChange={v => setBudgetCycleId(v === "none" ? undefined : Number(v))}>
                <SelectTrigger className="w-[160px]"><SelectValue placeholder="Cycle" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">Select</SelectItem>
                  {cycles?.map(c => <SelectItem key={c.id} value={String(c.id)}>{c.financialYearLabel}</SelectItem>)}
                </SelectContent>
              </Select>
              <Button onClick={handleBudgetPull} disabled={!budgetCycleId || budgetPull.isPending}>
                <RefreshCw className={`w-4 h-4 mr-1 ${budgetPull.isPending ? "animate-spin" : ""}`} /> Pull
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle className="text-lg flex items-center gap-2"><Link2 className="w-5 h-5" /> Project Module</CardTitle></CardHeader>
          <CardContent>
            <p className="text-sm text-slate-500 mb-4">Sync project KPIs and link project milestones to performance agreements.</p>
            <Button onClick={handleProjectSync} disabled={projectSync.isPending}>
              <RefreshCw className={`w-4 h-4 mr-1 ${projectSync.isPending ? "animate-spin" : ""}`} /> Sync Projects
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle className="text-lg flex items-center gap-2"><Search className="w-5 h-5" /> IDP Objectives</CardTitle></CardHeader>
          <CardContent>
            <p className="text-sm text-slate-500 mb-3">Search IDP objectives for KPI alignment and linkage.</p>
            <Input placeholder="Search objectives..." value={idpSearch} onChange={e => setIdpSearch(e.target.value)} />
            {idpObjectives && idpObjectives.length > 0 && (
              <div className="mt-3 space-y-2 max-h-40 overflow-y-auto">
                {idpObjectives.map(o => (
                  <div key={o.id} className="text-sm p-2 bg-slate-50 rounded">
                    <span className="font-medium text-slate-700">{o.code}</span>
                    <span className="text-slate-500 ml-2">{o.description}</span>
                    {o.chapter && <Badge variant="outline" className="ml-2">{o.chapter}</Badge>}
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-lg">Sync Log</CardTitle>
          <Select value={syncFilter || "all"} onValueChange={v => setSyncFilter(v === "all" ? undefined : v)}>
            <SelectTrigger className="w-[180px]"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Types</SelectItem>
              <SelectItem value="hr">HR</SelectItem>
              <SelectItem value="budget">Budget</SelectItem>
              <SelectItem value="project">Project</SelectItem>
            </SelectContent>
          </Select>
        </CardHeader>
        <CardContent>
          {!syncLog?.length ? (
            <p className="text-sm text-slate-400 text-center py-6">No sync history</p>
          ) : (
            <table className="w-full text-sm">
              <thead><tr className="border-b text-slate-500"><th className="text-left py-2 px-2">Type</th><th className="text-left py-2 px-2">Direction</th><th className="text-left py-2 px-2">Entity</th><th className="text-right py-2 px-2">Records</th><th className="text-left py-2 px-2">Status</th><th className="text-left py-2 px-2">Time</th></tr></thead>
              <tbody>
                {syncLog.map(l => (
                  <tr key={l.id} className="border-b last:border-0 hover:bg-slate-50">
                    <td className="py-2 px-2 font-medium">{l.integrationType}</td>
                    <td className="py-2 px-2">{l.direction}</td>
                    <td className="py-2 px-2">{l.entityType}</td>
                    <td className="py-2 px-2 text-right">{l.recordCount ?? "—"}</td>
                    <td className="py-2 px-2"><Badge className={STATUS_COLORS[l.status] || ""}>{l.status}</Badge></td>
                    <td className="py-2 px-2 text-xs text-slate-400">{l.syncedAt}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/integrations/integration-hub.component.ts
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { catchError, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { Cycle, IdpObjective, IntegrationSyncLog } from '@core/models/domain.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';

@Component({
  selector: 'app-integration-hub',
  standalone: true,
  imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule, MatSelectModule, PageHeaderComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="plat-page">
      <app-page-header title="Integration Hub" subtitle="Manage external system integrations and data synchronisation." icon="sync_alt" tone="indigo"></app-page-header>

      <div class="cards">
        <div class="plat-card tile">
          <h3><mat-icon>group</mat-icon> HR System</h3>
          <p>Sync employee data, post details, and organisational structure from your HR system.</p>
          <button mat-flat-button color="primary" (click)="hrSync()" [disabled]="busy().hr">
            <mat-icon [class.spin]="busy().hr">refresh</mat-icon> Sync Now
          </button>
        </div>

        <div class="plat-card tile">
          <h3><mat-icon>storage</mat-icon> mSCOA Budget</h3>
          <p>Pull budget values for budget-linked KPIs from the mSCOA system.</p>
          <div class="row">
            <mat-form-field appearance="outline" class="cycle">
              <mat-label>Cycle</mat-label>
              <mat-select [(ngModel)]="budgetCycleId">
                <mat-option *ngFor="let c of cycles()" [value]="c.id">{{ c.financialYearLabel }}</mat-option>
              </mat-select>
            </mat-form-field>
            <button mat-flat-button color="primary" (click)="budgetPull()" [disabled]="!budgetCycleId || busy().budget">
              <mat-icon [class.spin]="busy().budget">refresh</mat-icon> Pull
            </button>
          </div>
        </div>

        <div class="plat-card tile">
          <h3><mat-icon>link</mat-icon> Project Module</h3>
          <p>Sync project KPIs and link project milestones to performance agreements.</p>
          <button mat-flat-button color="primary" (click)="projectSync()" [disabled]="busy().proj">
            <mat-icon [class.spin]="busy().proj">refresh</mat-icon> Sync Projects
          </button>
        </div>

        <div class="plat-card tile">
          <h3><mat-icon>search</mat-icon> IDP Objectives</h3>
          <p>Search IDP objectives for KPI alignment and linkage.</p>
          <mat-form-field appearance="outline"><mat-label>Search objectives</mat-label><input matInput [ngModel]="idpSearch()" (ngModelChange)="onIdpSearch($event)" /></mat-form-field>
          <div class="idp-list" *ngIf="idpResults().length">
            <div class="idp-item" *ngFor="let o of idpResults()">
              <strong>{{ o.code }}</strong> <span class="muted">{{ o.description }}</span>
              <span class="chip" *ngIf="o.chapter">{{ o.chapter }}</span>
            </div>
          </div>
        </div>
      </div>

      <div class="plat-card log-card">
        <div class="log-head">
          <h3>Sync Log</h3>
          <mat-form-field appearance="outline" class="filter">
            <mat-label>Filter type</mat-label>
            <mat-select [ngModel]="syncFilter()" (ngModelChange)="onFilter($event)">
              <mat-option [value]="null">All Types</mat-option>
              <mat-option value="hr">HR</mat-option>
              <mat-option value="budget">Budget</mat-option>
              <mat-option value="project">Project</mat-option>
            </mat-select>
          </mat-form-field>
        </div>
        <table class="plat-table">
          <thead><tr><th>Type</th><th>Direction</th><th>Entity</th><th class="num">Records</th><th>Status</th><th>Time</th></tr></thead>
          <tbody>
            <tr *ngIf="logs().length === 0"><td colspan="6" class="empty">No sync history.</td></tr>
            <tr *ngFor="let l of logs()">
              <td><strong>{{ l.integrationType }}</strong></td>
              <td>{{ l.direction }}</td>
              <td>{{ l.entityType }}</td>
              <td class="num">{{ l.recordCount ?? '—' }}</td>
              <td><span class="badge" [class]="'b-' + (l.status || '').toLowerCase()">{{ l.status }}</span></td>
              <td class="muted">{{ l.syncedAt }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  `,
  styles: [`
    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 16px; margin-bottom: 16px; }
    .tile { padding: 16px; }
    .tile h3 { margin: 0 0 8px; display:flex; align-items:center; gap:8px; font-size: 15px; }
    .tile p { margin: 0 0 12px; color: #64748b; font-size: 13px; }
    .row { display: flex; gap: 8px; align-items: center; }
    .cycle { flex: 1; }
    .filter { width: 180px; }
    .log-card { padding: 16px; }
    .log-head { display:flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
    .log-head h3 { margin: 0; }
    .num { text-align: right; }
    .idp-list { max-height: 160px; overflow-y: auto; display: flex; flex-direction: column; gap: 6px; }
    .idp-item { padding: 6px 8px; background: #f8fafc; border-radius: 6px; font-size: 13px; }
    .chip { display: inline-block; margin-left: 6px; padding: 1px 8px; border: 1px solid var(--plat-border); border-radius: 999px; font-size: 11px; }
    .badge { padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; background:#e2e8f0; color:#475569; }
    .b-completed { background:#dcfce7; color:#15803d; }
    .b-pending { background:#fef9c3; color:#a16207; }
    .b-failed { background:#fee2e2; color:#b91c1c; }
    .spin { animation: spin 1s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }
    mat-form-field { width: 100%; }
  `],
})
export class IntegrationHubComponent implements OnInit, OnDestroy {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  cycles = signal<Cycle[]>([]);
  logs = signal<IntegrationSyncLog[]>([]);
  idpResults = signal<IdpObjective[]>([]);
  idpSearch = signal('');
  syncFilter = signal<string | null>(null);
  budgetCycleId: number | null = null;
  busy = signal({ hr: false, budget: false, proj: false });
  private idpDebounce: ReturnType<typeof setTimeout> | null = null;

  ngOnInit() {
    this.api.get<Cycle[]>('/cycles').pipe(catchError(() => of([] as Cycle[]))).subscribe((cs) => this.cycles.set(Array.isArray(cs) ? cs : []));
    this.refreshLog();
    this.loadIdp('');
  }
  ngOnDestroy() {
    if (this.idpDebounce) { clearTimeout(this.idpDebounce); this.idpDebounce = null; }
  }

  refreshLog() {
    this.api.get<IntegrationSyncLog[]>('/integrations/sync-log', { integrationType: this.syncFilter() ?? undefined })
      .pipe(catchError(() => of([] as IntegrationSyncLog[])))
      .subscribe((r) => this.logs.set(Array.isArray(r) ? r : []));
  }

  onFilter(v: string | null) { this.syncFilter.set(v); this.refreshLog(); }

  onIdpSearch(v: string) {
    this.idpSearch.set(v);
    if (this.idpDebounce) clearTimeout(this.idpDebounce);
    this.idpDebounce = setTimeout(() => this.loadIdp(v), 300);
  }
  loadIdp(search: string) {
    this.api.get<IdpObjective[]>('/integrations/idp-objectives', { search })
      .pipe(catchError(() => of([] as IdpObjective[])))
      .subscribe((r) => this.idpResults.set(Array.isArray(r) ? r : []));
  }

  hrSync() {
    this.busy.update((b) => ({ ...b, hr: true }));
    this.api.post<{ message?: string }>('/integrations/hr-sync', {}).pipe(
      tap((r) => { this.toast.success('HR Sync', r?.message ?? 'Sync completed'); this.refreshLog(); }),
      catchError((e) => { this.toast.error('HR sync failed', e?.error?.message ?? e?.message); return of(null); }),
    ).subscribe(() => this.busy.update((b) => ({ ...b, hr: false })));
  }
  projectSync() {
    this.busy.update((b) => ({ ...b, proj: true }));
    this.api.post<{ message?: string }>('/integrations/project-sync', {}).pipe(
      tap((r) => { this.toast.success('Project Sync', r?.message ?? 'Sync completed'); this.refreshLog(); }),
      catchError((e) => { this.toast.error('Project sync failed', e?.error?.message ?? e?.message); return of(null); }),
    ).subscribe(() => this.busy.update((b) => ({ ...b, proj: false })));
  }
  budgetPull() {
    if (!this.budgetCycleId) return;
    this.busy.update((b) => ({ ...b, budget: true }));
    this.api.post<{ message?: string }>('/integrations/budget-pull', { cycleId: this.budgetCycleId }).pipe(
      tap((r) => { this.toast.success('Budget Pull', r?.message ?? 'Pull completed'); this.refreshLog(); }),
      catchError((e) => { this.toast.error('Budget pull failed', e?.error?.message ?? e?.message); return of(null); }),
    ).subscribe(() => this.busy.update((b) => ({ ...b, budget: false })));
  }
}
