// Insight-Performance-Hub/artifacts/perf-app/src/features/scorecards/ReviewSdbip.tsx
import { useState } from "react";
import {
  useListScorecards, useTransitionScorecard,
  useListScorecardKpis, useTransitionScorecardKpi,
  useListQuarterTargets, useListCycles, useListUsers,
} from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { useToast } from "@/core/hooks/use-toast";
import {
  CheckCircle2, XCircle, ArrowLeft, FileSearch, Eye,
  Loader2, AlertTriangle, ClipboardCheck,
} from "lucide-react";

const STATUS_COLORS: Record<string, string> = {
  Draft: "bg-gray-100 text-gray-700",
  Submitted: "bg-blue-100 text-blue-700",
  Reviewed: "bg-amber-100 text-amber-700",
  Approved: "bg-green-100 text-green-700",
};

export default function ReviewSdbip() {
  const { toast } = useToast();
  const { data: cycles } = useListCycles();
  const { data: users } = useListUsers();
  const [selectedCycleId, setSelectedCycleId] = useState<number | undefined>();
  const [selectedScorecardId, setSelectedScorecardId] = useState<number | undefined>();
  const [reviewComments, setReviewComments] = useState("");
  const [kpiComments, setKpiComments] = useState<Record<number, string>>({});
  const [showReturnDialog, setShowReturnDialog] = useState(false);
  const [returnReason, setReturnReason] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);

  const effectiveCycleId = selectedCycleId || cycles?.[0]?.id;
  const { data: allScorecards, refetch: refetchScorecards } = useListScorecards({ cycleId: effectiveCycleId });
  const kpisQuery = useListScorecardKpis(selectedScorecardId ?? 0);
  const kpis = selectedScorecardId ? kpisQuery.data : undefined;

  const scorecards = allScorecards?.filter(s => s.status === "Submitted" || s.status === "Reviewed") ?? [];
  const selectedScorecard = allScorecards?.find(s => s.id === selectedScorecardId);

  const transitionScorecard = useTransitionScorecard();
  const transitionKpi = useTransitionScorecardKpi();

  const getUserName = (id: number | null) => {
    if (!id) return "—";
    const u = users?.find(u => u.id === id);
    return u ? u.displayName : `User #${id}`;
  };

  const handleReviewKpi = async (kpiId: number, action: "review" | "return") => {
    setIsProcessing(true);
    try {
      await transitionKpi.mutateAsync({
        id: kpiId,
        data: { action, comments: kpiComments[kpiId] || "" },
      });
      toast({ title: action === "review" ? "KPI marked as Reviewed" : "KPI returned to Draft" });
      kpisQuery.refetch();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to transition KPI", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleReviewScorecard = async () => {
    if (!selectedScorecardId) return;
    setIsProcessing(true);
    try {
      await transitionScorecard.mutateAsync({
        id: selectedScorecardId,
        data: { action: "review", comments: reviewComments },
      });
      toast({ title: "SDBIP marked as Reviewed", description: "The scorecard is now ready for PMS Director approval." });
      setSelectedScorecardId(undefined);
      setReviewComments("");
      refetchScorecards();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to review scorecard", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleReturnScorecard = async () => {
    if (!selectedScorecardId) return;
    setIsProcessing(true);
    try {
      await transitionScorecard.mutateAsync({
        id: selectedScorecardId,
        data: { action: "return", comments: returnReason },
      });
      toast({ title: "SDBIP returned", description: "The scorecard has been returned to Draft for corrections." });
      setSelectedScorecardId(undefined);
      setReturnReason("");
      setShowReturnDialog(false);
      refetchScorecards();
    } catch (e: any) {
      toast({ title: "Error", description: e?.response?.data?.error || "Failed to return scorecard", variant: "destructive" });
    } finally {
      setIsProcessing(false);
    }
  };

  const submittedKpis = kpis?.filter(k => k.status === "Submitted") ?? [];
  const reviewedKpis = kpis?.filter(k => k.status === "Reviewed") ?? [];
  const allKpisReviewed = kpis && kpis.length > 0 && kpis.every(k => k.status === "Reviewed");

  if (selectedScorecardId && selectedScorecard) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => { setSelectedScorecardId(undefined); setReviewComments(""); }}>
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Queue
          </Button>
          <div className="flex-1">
            <h1 className="text-2xl font-bold text-slate-800">Review: {selectedScorecard.name}</h1>
            <p className="text-slate-500">
              Status: <Badge className={STATUS_COLORS[selectedScorecard.status]}>{selectedScorecard.status}</Badge>
              {" · "}Created by {getUserName(selectedScorecard.createdById)}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-4">
          <Card>
            <CardContent className="pt-4">
              <div className="text-sm text-slate-500">Total KPIs</div>
              <div className="text-2xl font-bold">{kpis?.length ?? 0}</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-4">
              <div className="text-sm text-slate-500">Reviewed</div>
              <div className="text-2xl font-bold text-amber-600">{reviewedKpis.length}</div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-4">
              <div className="text-sm text-slate-500">Pending Review</div>
              <div className="text-2xl font-bold text-blue-600">{submittedKpis.length}</div>
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>KPI Review</CardTitle>
            <CardDescription>Review each KPI individually, then mark the entire scorecard as reviewed.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {kpis?.map(kpi => (
                <KpiReviewCard
                  key={kpi.id}
                  kpi={kpi}
                  comment={kpiComments[kpi.id] || ""}
                  onCommentChange={(val) => setKpiComments(prev => ({ ...prev, [kpi.id]: val }))}
                  onReview={() => handleReviewKpi(kpi.id, "review")}
                  onReturn={() => handleReviewKpi(kpi.id, "return")}
                  isProcessing={isProcessing}
                  getUserName={getUserName}
                />
              ))}
              {(!kpis || kpis.length === 0) && (
                <p className="text-center text-slate-400 py-8">No KPIs found for this scorecard.</p>
              )}
            </div>
          </CardContent>
        </Card>

        {selectedScorecard.status === "Submitted" && (
          <Card className="border-amber-200 bg-amber-50/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ClipboardCheck className="w-5 h-5 text-amber-600" />
                Scorecard Review Decision
              </CardTitle>
              <CardDescription>
                {allKpisReviewed
                  ? "All KPIs have been reviewed. You may now mark the scorecard as Reviewed."
                  : `${submittedKpis.length} KPI(s) still pending review. Review all KPIs before marking the scorecard.`}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label>Review Comments (Optional)</Label>
                <Textarea
                  value={reviewComments}
                  onChange={e => setReviewComments(e.target.value)}
                  placeholder="Add any overall review comments..."
                  rows={3}
                />
              </div>
              <div className="flex gap-3">
                <Button
                  onClick={handleReviewScorecard}
                  disabled={!allKpisReviewed || isProcessing}
                  className="bg-amber-600 hover:bg-amber-700"
                >
                  {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <CheckCircle2 className="w-4 h-4 mr-2" />}
                  Mark as Reviewed
                </Button>
                <Button
                  variant="outline"
                  onClick={() => setShowReturnDialog(true)}
                  disabled={isProcessing}
                  className="border-red-300 text-red-600 hover:bg-red-50"
                >
                  <XCircle className="w-4 h-4 mr-2" /> Return to Draft
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        <Dialog open={showReturnDialog} onOpenChange={setShowReturnDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Return Scorecard to Draft</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <Label>Reason for Return *</Label>
                <Textarea
                  value={returnReason}
                  onChange={e => setReturnReason(e.target.value)}
                  placeholder="Explain what needs to be corrected..."
                  rows={4}
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowReturnDialog(false)}>Cancel</Button>
              <Button
                onClick={handleReturnScorecard}
                disabled={!returnReason.trim() || isProcessing}
                className="bg-red-600 hover:bg-red-700"
              >
                {isProcessing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <XCircle className="w-4 h-4 mr-2" />}
                Return to Draft
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800">Review SDBIP — PMS Manager</h1>
        <p className="text-slate-500 mt-1">Review submitted scorecards and their KPIs before forwarding for Director approval.</p>
      </div>

      <div className="flex items-center gap-4">
        <div className="w-64">
          <Label>Performance Cycle</Label>
          <Select value={String(effectiveCycleId ?? "")} onValueChange={v => setSelectedCycleId(Number(v))}>
            <SelectTrigger><SelectValue placeholder="Select cycle" /></SelectTrigger>
            <SelectContent>
              {cycles?.map(c => <SelectItem key={c.id} value={String(c.id)}>{c.financialYearLabel}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>

      {scorecards.length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center">
            <FileSearch className="w-12 h-12 text-slate-300 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-slate-600">No Scorecards Pending Review</h3>
            <p className="text-slate-400 mt-1">All submitted scorecards have been reviewed for this cycle.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {scorecards.map(sc => (
            <Card key={sc.id} className="hover:shadow-md transition-shadow cursor-pointer" onClick={() => setSelectedScorecardId(sc.id)}>
              <CardContent className="py-4 flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-slate-800">{sc.name}</h3>
                  <p className="text-sm text-slate-500">
                    Created by {getUserName(sc.createdById)} · {new Date(sc.createdAt).toLocaleDateString()}
                  </p>
                </div>
                <div className="flex items-center gap-3">
                  <Badge className={STATUS_COLORS[sc.status]}>{sc.status}</Badge>
                  <Button size="sm" variant="outline">
                    <Eye className="w-4 h-4 mr-1" /> Review
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function KpiReviewCard({
  kpi,
  comment,
  onCommentChange,
  onReview,
  onReturn,
  isProcessing,
  getUserName,
}: {
  kpi: any;
  comment: string;
  onCommentChange: (v: string) => void;
  onReview: () => void;
  onReturn: () => void;
  isProcessing: boolean;
  getUserName: (id: number | null) => string;
}) {
  const [expanded, setExpanded] = useState(false);
  const targetsQuery = useListQuarterTargets(expanded ? kpi.id : 0);
  const targets = expanded ? targetsQuery.data : undefined;

  return (
    <div className="border rounded-lg p-4 space-y-3">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className="font-mono text-sm text-slate-500">{kpi.kpiNumber}</span>
            <Badge className={STATUS_COLORS[kpi.status]}>{kpi.status}</Badge>
          </div>
          <p className="font-medium text-slate-800 mt-1">{kpi.description}</p>
          <div className="flex gap-6 mt-2 text-sm text-slate-500">
            <span>Weight: {kpi.weighting}%</span>
            <span>Annual Target: {kpi.annualTarget}</span>
            {kpi.baseline && <span>Baseline: {kpi.baseline}</span>}
            <span>Responsible: {getUserName(kpi.responsiblePostId)}</span>
          </div>
          {kpi.strategicObjective && (
            <p className="text-xs text-slate-400 mt-1">Strategic Objective: {kpi.strategicObjective}</p>
          )}
        </div>
        <Button variant="ghost" size="sm" onClick={() => setExpanded(!expanded)}>
          {expanded ? "Collapse" : "Expand"}
        </Button>
      </div>

      {expanded && (
        <div className="space-y-3 pt-2 border-t">
          {targets && targets.length > 0 && (
            <div className="grid grid-cols-4 gap-2">
              {[1, 2, 3, 4].map(q => {
                const t = targets.find((t: any) => t.quarter === q);
                return (
                  <div key={q} className="bg-slate-50 rounded p-2 text-sm">
                    <div className="font-medium text-slate-600">Q{q}</div>
                    <div className="text-slate-800">{t?.targetValue ?? "—"}</div>
                    {t?.budgetValue != null && <div className="text-xs text-slate-400">Budget: R{t.budgetValue.toLocaleString()}</div>}
                  </div>
                );
              })}
            </div>
          )}

          {kpi.status === "Submitted" && (
            <div className="space-y-2">
              <Textarea
                value={comment}
                onChange={e => onCommentChange(e.target.value)}
                placeholder="Review comments for this KPI..."
                rows={2}
                className="text-sm"
              />
              <div className="flex gap-2">
                <Button size="sm" onClick={onReview} disabled={isProcessing} className="bg-amber-600 hover:bg-amber-700">
                  <CheckCircle2 className="w-3 h-3 mr-1" /> Mark Reviewed
                </Button>
                <Button size="sm" variant="outline" onClick={onReturn} disabled={isProcessing} className="border-red-300 text-red-600 hover:bg-red-50">
                  <XCircle className="w-3 h-3 mr-1" /> Return
                </Button>
              </div>
            </div>
          )}

          {kpi.status === "Reviewed" && (
            <div className="flex items-center gap-2 text-sm text-amber-600">
              <CheckCircle2 className="w-4 h-4" /> Reviewed
            </div>
          )}

          {kpi.status === "Approved" && (
            <div className="flex items-center gap-2 text-sm text-green-600">
              <CheckCircle2 className="w-4 h-4" /> Approved
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/org-planning/review-sdbip.component.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { catchError, finalize, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { Cycle, Scorecard, ScorecardKpi, KpiQuarterTarget } from '@core/models/domain.model';
import { User } from '@core/models/user.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';
import { LoadingSpinnerComponent } from '@shared/components/loading-spinner/loading-spinner.component';
import { StatusBadgeComponent } from '@shared/components/status-badge/status-badge.component';
import { EmptyStateComponent } from '@shared/components/empty-state/empty-state.component';

@Component({
  selector: 'app-return-reason-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule],
  template: `
    <h2 mat-dialog-title>Return Scorecard to Draft</h2>
    <mat-dialog-content class="content">
      <mat-form-field appearance="outline">
        <mat-label>Reason for Return *</mat-label>
        <textarea matInput rows="4" [(ngModel)]="reason" placeholder="Explain what needs to be corrected..."></textarea>
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>Cancel</button>
      <button mat-flat-button color="warn" [disabled]="!reason.trim()" (click)="ref.close(reason.trim())">Return to Draft</button>
    </mat-dialog-actions>
  `,
  styles: [`.content { min-width: 460px; padding-top: 12px !important; } mat-form-field { width: 100%; }`],
})
export class ReturnReasonDialogComponent {
  reason = '';
  constructor(public ref: MatDialogRef<ReturnReasonDialogComponent, string | null>) {}
}

@Component({
  selector: 'app-review-sdbip',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule, MatSelectModule, MatDialogModule,
    PageHeaderComponent, LoadingSpinnerComponent, StatusBadgeComponent, EmptyStateComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './review-sdbip.component.html',
  styleUrls: ['./review-sdbip.component.scss'],
})
export class ReviewSdbipComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  private readonly dialog = inject(MatDialog);

  loading = signal(true);
  cycles = signal<Cycle[]>([]);
  users = signal<User[]>([]);
  selectedCycleId = signal<number | null>(null);
  effectiveCycleId = computed<number | null>(() => this.selectedCycleId() ?? this.cycles()[0]?.id ?? null);

  allScorecards = signal<Scorecard[]>([]);
  scorecards = computed(() => this.allScorecards().filter((s) => s.status === 'Submitted' || s.status === 'Reviewed'));
  selectedScorecardId = signal<number | null>(null);
  selectedScorecard = computed(() => this.allScorecards().find((s) => s.id === this.selectedScorecardId()) ?? null);

  kpis = signal<ScorecardKpi[]>([]);
  expanded = signal<Record<number, boolean>>({});
  kpiTargets = signal<Record<number, KpiQuarterTarget[]>>({});
  kpiComments: Record<number, string> = {};
  reviewComments = '';
  isProcessing = signal(false);

  submittedKpis = computed(() => this.kpis().filter((k) => k.status === 'Submitted'));
  reviewedKpis = computed(() => this.kpis().filter((k) => k.status === 'Reviewed'));
  allKpisReviewed = computed(() => {
    const list = this.kpis();
    return list.length > 0 && list.every((k) => k.status === 'Reviewed');
  });

  ngOnInit() {
    this.api.get<Cycle[]>('/cycles').pipe(
      catchError(() => of([] as Cycle[])),
      tap((c) => this.cycles.set(Array.isArray(c) ? c : [])),
    ).subscribe(() => this.loadScorecards());
    this.api.get<User[]>('/auth/users').pipe(
      catchError(() => of([] as User[])),
      tap((u) => this.users.set(Array.isArray(u) ? u : [])),
    ).subscribe();
  }

  loadScorecards() {
    const cycleId = this.effectiveCycleId();
    if (!cycleId) { this.allScorecards.set([]); this.loading.set(false); return; }
    this.loading.set(true);
    this.api.get<Scorecard[]>('/scorecards', { cycleId }).pipe(
      catchError(() => of([] as Scorecard[])),
      tap((r) => this.allScorecards.set(Array.isArray(r) ? r : [])),
      finalize(() => this.loading.set(false)),
    ).subscribe();
  }

  selectCycle(id: number) { this.selectedCycleId.set(id); this.loadScorecards(); }

  openScorecard(sc: Scorecard) {
    this.selectedScorecardId.set(sc.id);
    this.expanded.set({});
    this.kpiTargets.set({});
    this.kpiComments = {};
    this.reviewComments = '';
    this.kpis.set([]);
    this.api.get<ScorecardKpi[]>(`/scorecards/${sc.id}/kpis`).pipe(
      catchError(() => of([] as ScorecardKpi[])),
      tap((r) => this.kpis.set(Array.isArray(r) ? r : [])),
    ).subscribe();
  }

  back() {
    this.selectedScorecardId.set(null);
    this.kpis.set([]);
    this.reviewComments = '';
  }

  toggleExpand(kpi: ScorecardKpi) {
    const cur = this.expanded();
    const next = { ...cur, [kpi.id]: !cur[kpi.id] };
    this.expanded.set(next);
    if (next[kpi.id] && !this.kpiTargets()[kpi.id]) {
      this.api.get<KpiQuarterTarget[]>(`/scorecard-kpis/${kpi.id}/quarter-targets`).pipe(
        catchError(() => of([] as KpiQuarterTarget[])),
        tap((r) => this.kpiTargets.set({ ...this.kpiTargets(), [kpi.id]: Array.isArray(r) ? r : [] })),
      ).subscribe();
    }
  }

  setComment(kpiId: number, value: string) { this.kpiComments[kpiId] = value; }

  reviewKpi(kpiId: number, action: 'review' | 'return') {
    this.isProcessing.set(true);
    this.api.post(`/scorecard-kpis/${kpiId}/transition`, { action, comments: this.kpiComments[kpiId] || '' }).pipe(
      tap(() => {
        this.toast.success(action === 'review' ? 'KPI marked as Reviewed' : 'KPI returned to Draft');
        const sc = this.selectedScorecardId();
        if (sc) this.api.get<ScorecardKpi[]>(`/scorecards/${sc}/kpis`).pipe(
          catchError(() => of([] as ScorecardKpi[])),
          tap((r) => this.kpis.set(Array.isArray(r) ? r : [])),
        ).subscribe();
      }),
      catchError((e) => { this.toast.error('Error', e?.error?.message ?? 'Failed to transition KPI'); return of(null); }),
      finalize(() => this.isProcessing.set(false)),
    ).subscribe();
  }

  reviewScorecard() {
    const id = this.selectedScorecardId();
    if (!id || !this.allKpisReviewed()) return;
    this.isProcessing.set(true);
    this.api.post(`/scorecards/${id}/transition`, { action: 'review', comments: this.reviewComments }).pipe(
      tap(() => {
        this.toast.success('SDBIP marked as Reviewed', 'Ready for PMS Director approval.');
        this.back();
        this.loadScorecards();
      }),
      catchError((e) => { this.toast.error('Error', e?.error?.message ?? 'Failed to review scorecard'); return of(null); }),
      finalize(() => this.isProcessing.set(false)),
    ).subscribe();
  }

  returnScorecard() {
    const id = this.selectedScorecardId(); if (!id) return;
    this.dialog.open(ReturnReasonDialogComponent, { panelClass: 'plat-dialog' })
      .afterClosed().subscribe((reason) => {
        if (!reason) return;
        this.isProcessing.set(true);
        this.api.post(`/scorecards/${id}/transition`, { action: 'return', comments: reason }).pipe(
          tap(() => {
            this.toast.success('SDBIP returned', 'Returned to Draft for corrections.');
            this.back();
            this.loadScorecards();
          }),
          catchError((e) => { this.toast.error('Error', e?.error?.message ?? 'Failed to return scorecard'); return of(null); }),
          finalize(() => this.isProcessing.set(false)),
        ).subscribe();
      });
  }

  userName(id: number | null | undefined): string {
    if (!id) return '—';
    const u = this.users().find((x) => x.id === id);
    return u ? u.displayName : `User #${id}`;
  }

  formatDate(s: string | null | undefined): string {
    if (!s) return '';
    try { return new Date(s).toLocaleDateString(); } catch { return s; }
  }

  targetForQuarter(kpiId: number, q: number): KpiQuarterTarget | undefined {
    return this.kpiTargets()[kpiId]?.find((t) => t.quarter === q);
  }

  trackById(_: number, x: { id: number }): number { return x.id; }
}

<section class="plat-page">
  <ng-container *ngIf="selectedScorecardId() && selectedScorecard(); else queue">
    <div class="detail-head">
      <div class="left">
        <button mat-button (click)="back()"><mat-icon>arrow_back</mat-icon> Back to Queue</button>
        <div class="title-block">
          <h2>Review: {{ selectedScorecard()!.name }}</h2>
          <p>
            Created by {{ userName(selectedScorecard()!.createdById) }}
            · <app-status-badge [status]="selectedScorecard()!.status"></app-status-badge>
          </p>
        </div>
      </div>
    </div>

    <div class="stats-grid">
      <div class="plat-card stat"><div class="stat-label">Total KPIs</div><div class="stat-value">{{ kpis().length }}</div></div>
      <div class="plat-card stat"><div class="stat-label">Reviewed</div><div class="stat-value tone-amber">{{ reviewedKpis().length }}</div></div>
      <div class="plat-card stat"><div class="stat-label">Pending Review</div><div class="stat-value tone-blue">{{ submittedKpis().length }}</div></div>
    </div>

    <div class="plat-card">
      <div class="card-head">
        <h3>KPI Review</h3>
        <p>Review each KPI individually, then mark the entire scorecard as reviewed.</p>
      </div>
      <div class="kpi-list">
        <div *ngIf="kpis().length === 0" class="empty">No KPIs found for this scorecard.</div>
        <div *ngFor="let k of kpis(); trackBy: trackById" class="kpi-card">
          <div class="kpi-row">
            <div class="kpi-body">
              <div class="kpi-meta-top">
                <span class="kpi-num">{{ k.kpiNumber }}</span>
                <app-status-badge [status]="k.status"></app-status-badge>
              </div>
              <div class="kpi-desc">{{ k.description }}</div>
              <div class="kpi-meta">
                <span>Weight: {{ k.weighting }}%</span>
                <span>Annual Target: {{ k.annualTarget }}</span>
                <span *ngIf="k.baseline">Baseline: {{ k.baseline }}</span>
                <span>Responsible: {{ userName(k.responsiblePostId) }}</span>
              </div>
              <div *ngIf="k.strategicObjective" class="kpi-strategic">Strategic Objective: {{ k.strategicObjective }}</div>
            </div>
            <button mat-button (click)="toggleExpand(k)">{{ expanded()[k.id] ? 'Collapse' : 'Expand' }}</button>
          </div>

          <div *ngIf="expanded()[k.id]" class="kpi-expand">
            <div class="targets-row" *ngIf="kpiTargets()[k.id]?.length">
              <div *ngFor="let q of [1,2,3,4]" class="qcell">
                <div class="qlbl">Q{{ q }}</div>
                <div class="qval">{{ targetForQuarter(k.id, q)?.targetValue || '—' }}</div>
                <div *ngIf="targetForQuarter(k.id, q)?.budgetValue != null" class="qbudget">
                  Budget: R{{ targetForQuarter(k.id, q)!.budgetValue!.toLocaleString() }}
                </div>
              </div>
            </div>

            <ng-container *ngIf="k.status === 'Submitted'">
              <mat-form-field appearance="outline" class="comment">
                <mat-label>Review comments for this KPI</mat-label>
                <textarea matInput rows="2" [ngModel]="kpiComments[k.id] || ''" (ngModelChange)="setComment(k.id, $event)"></textarea>
              </mat-form-field>
              <div class="kpi-actions">
                <button mat-flat-button color="primary" [disabled]="isProcessing()" (click)="reviewKpi(k.id, 'review')">
                  <mat-icon>check_circle</mat-icon> Mark Reviewed
                </button>
                <button mat-stroked-button color="warn" [disabled]="isProcessing()" (click)="reviewKpi(k.id, 'return')">
                  <mat-icon>cancel</mat-icon> Return
                </button>
              </div>
            </ng-container>

            <div *ngIf="k.status === 'Reviewed'" class="status-line tone-amber">
              <mat-icon>check_circle</mat-icon> Reviewed
            </div>
            <div *ngIf="k.status === 'Approved'" class="status-line tone-green">
              <mat-icon>check_circle</mat-icon> Approved
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="plat-card decision-card amber" *ngIf="selectedScorecard()!.status === 'Submitted'">
      <div class="card-head">
        <h3><mat-icon>fact_check</mat-icon> Scorecard Review Decision</h3>
        <p>{{ allKpisReviewed()
          ? 'All KPIs have been reviewed. You may now mark the scorecard as Reviewed.'
          : (submittedKpis().length + ' KPI(s) still pending review. Review all KPIs before marking the scorecard.') }}</p>
      </div>
      <mat-form-field appearance="outline">
        <mat-label>Review Comments (Optional)</mat-label>
        <textarea matInput rows="3" [(ngModel)]="reviewComments" placeholder="Add any overall review comments..."></textarea>
      </mat-form-field>
      <div class="decision-actions">
        <button mat-flat-button color="primary" [disabled]="!allKpisReviewed() || isProcessing()" (click)="reviewScorecard()">
          <mat-icon>check_circle</mat-icon> Mark as Reviewed
        </button>
        <button mat-stroked-button color="warn" [disabled]="isProcessing()" (click)="returnScorecard()">
          <mat-icon>cancel</mat-icon> Return to Draft
        </button>
      </div>
    </div>
  </ng-container>

  <ng-template #queue>
    <app-page-header title="Review SDBIP" subtitle="PMS Manager — review submitted scorecards before forwarding for Director approval." icon="fact_check" tone="orange">
      <mat-form-field *ngIf="cycles().length > 0" appearance="outline" class="cycle-pick" subscriptSizing="dynamic">
        <mat-label>Cycle</mat-label>
        <mat-select [ngModel]="effectiveCycleId()" (ngModelChange)="selectCycle($event)">
          <mat-option *ngFor="let c of cycles(); trackBy: trackById" [value]="c.id">{{ c.financialYearLabel }}</mat-option>
        </mat-select>
      </mat-form-field>
    </app-page-header>

    <app-loading-spinner *ngIf="loading()"></app-loading-spinner>

    <ng-container *ngIf="!loading()">
      <div *ngIf="scorecards().length > 0; else noPending" class="queue-list">
        <div *ngFor="let sc of scorecards(); trackBy: trackById" class="plat-card queue-card" (click)="openScorecard(sc)">
          <div class="qc-body">
            <h3>{{ sc.name }}</h3>
            <p>Created by {{ userName(sc.createdById) }} · {{ formatDate(sc.createdAt) }}</p>
          </div>
          <div class="qc-right">
            <app-status-badge [status]="sc.status"></app-status-badge>
            <button mat-stroked-button color="primary"><mat-icon>visibility</mat-icon> Review</button>
          </div>
        </div>
      </div>
      <ng-template #noPending>
        <div class="plat-card">
          <app-empty-state icon="fact_check" title="No Scorecards Pending Review" message="All submitted scorecards have been reviewed for this cycle."></app-empty-state>
        </div>
      </ng-template>
    </ng-container>
  </ng-template>
</section>
