// Insight-Performance-Hub/artifacts/perf-app/src/pages/reports/ReportCentre.tsx
import { useState } from "react";
import type { GenerateReportInputReportType } from "@workspace/api-client-react";
import { useListReportRuns, useGenerateReport } from "@workspace/api-client-react";
import { useListCycles } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { FileText, Plus, Download, Loader2, FileSpreadsheet, File } from "lucide-react";

function getErrorMessage(e: unknown): string {
  if (e && typeof e === "object") {
    const obj = e as Record<string, unknown>;
    if (obj.response && typeof obj.response === "object") {
      const resp = obj.response as Record<string, unknown>;
      if (resp.data && typeof resp.data === "object") {
        const data = resp.data as Record<string, unknown>;
        if (typeof data.error === "string") return data.error;
      }
    }
    if (obj.message && typeof obj.message === "string") return obj.message;
  }
  return "An error occurred";
}

const STATUS_COLORS: Record<string, string> = {
  Pending: "bg-gray-100 text-gray-700",
  Generated: "bg-green-100 text-green-700",
  Failed: "bg-red-100 text-red-700",
};

const REPORT_TYPES = [
  { value: "quarterly", label: "Quarterly Report" },
  { value: "mid-year", label: "Mid-Year Report" },
  { value: "annual", label: "Annual Report" },
  { value: "institutional-evaluation", label: "Institutional Evaluation" },
];

const FORMAT_OPTIONS = [
  { value: "xlsx", label: "Excel (.xlsx)", icon: FileSpreadsheet, color: "text-green-600 hover:bg-green-50 border-green-200" },
  { value: "pdf", label: "PDF (.pdf)", icon: File, color: "text-red-600 hover:bg-red-50 border-red-200" },
  { value: "csv", label: "CSV (.csv)", icon: FileText, color: "text-blue-600 hover:bg-blue-50 border-blue-200" },
];

export default function ReportCentre() {
  const { toast } = useToast();
  const { data: cycles } = useListCycles();
  const [cycleId, setCycleId] = useState<number | undefined>();
  const [showGenerate, setShowGenerate] = useState(false);
  const [form, setForm] = useState({ reportType: "quarterly", title: "", quarter: 1, departmentId: 0 });
  const [exportingId, setExportingId] = useState<number | null>(null);
  const [exportFormat, setExportFormat] = useState<string | null>(null);

  const { data: runs, refetch } = useListReportRuns({ cycleId });
  const generateReport = useGenerateReport();

  async function handleExport(reportId: number, title: string, format: string) {
    setExportingId(reportId);
    setExportFormat(format);
    try {
      const baseUrl = import.meta.env.VITE_API_URL || "/api";
      const response = await fetch(`${baseUrl}/reports/runs/${reportId}/export?format=${format}`);
      if (!response.ok) {
        const err = await response.json().catch(() => ({ error: "Download failed" }));
        throw new Error(err.error || "Download failed");
      }
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const ext = format === "xlsx" ? "xlsx" : format === "pdf" ? "pdf" : "csv";
      a.download = `${title.replace(/[^a-zA-Z0-9_ -]/g, "_")}.${ext}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      toast({ title: `Report downloaded as ${ext.toUpperCase()}` });
    } catch (e) {
      toast({ title: getErrorMessage(e), variant: "destructive" });
    } finally {
      setExportingId(null);
      setExportFormat(null);
    }
  }

  async function handleGenerate() {
    if (!cycleId) return;
    try {
      await generateReport.mutateAsync({
        data: {
          cycleId,
          reportType: form.reportType as GenerateReportInputReportType,
          title: form.title,
          quarter: form.quarter || undefined,
          departmentId: form.departmentId || undefined,
        }
      });
      setShowGenerate(false);
      setForm({ reportType: "quarterly", title: "", quarter: 1, departmentId: 0 });
      refetch();
      toast({ title: "Report generated" });
    } catch (e) {
      toast({ title: getErrorMessage(e), variant: "destructive" });
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Report Centre</h1>
          <p className="text-sm text-slate-500 mt-1">Generate and retrieve performance reports</p>
        </div>
        <div className="flex gap-3">
          <Select value={cycleId?.toString() || ""} onValueChange={v => setCycleId(Number(v))}>
            <SelectTrigger className="w-[200px]"><SelectValue placeholder="Select Cycle" /></SelectTrigger>
            <SelectContent>{cycles?.map(c => <SelectItem key={c.id} value={c.id.toString()}>{c.financialYearLabel}</SelectItem>)}</SelectContent>
          </Select>
          {cycleId && <Button onClick={() => setShowGenerate(true)} className="bg-[#0f2b46]"><Plus className="w-4 h-4 mr-1" />Generate Report</Button>}
        </div>
      </div>

      <div className="mb-4 p-4 bg-slate-50 rounded-lg border border-slate-200">
        <h3 className="text-sm font-semibold text-slate-700 mb-2">Report colour coding</h3>
        <div className="flex gap-4 text-xs">
          <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-sm bg-[#c6efce] border border-green-300" /> Target Met</span>
          <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-sm bg-[#ffeb9c] border border-amber-300" /> Partially Met (70-99%)</span>
          <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-sm bg-[#ffc7ce] border border-red-300" /> Target Missed (&lt;70%)</span>
        </div>
      </div>

      <div className="space-y-3">
        {runs?.map(r => (
          <Card key={r.id}>
            <CardContent className="p-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center">
                  <FileText className="w-5 h-5 text-blue-600" />
                </div>
                <div>
                  <p className="font-medium text-sm">{r.title}</p>
                  <div className="flex items-center gap-2 text-xs text-slate-500">
                    <span className="capitalize">{r.reportType}</span>
                    {r.quarter && <span>• Q{r.quarter}</span>}
                    <span>• {r.generatedAt ? new Date(r.generatedAt).toLocaleDateString() : "Pending"}</span>
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Badge className={STATUS_COLORS[r.status] || "bg-gray-100"}>{r.status}</Badge>
                {r.status === "Generated" && (
                  <div className="flex gap-1.5">
                    {FORMAT_OPTIONS.map(fmt => {
                      const Icon = fmt.icon;
                      const isLoading = exportingId === r.id && exportFormat === fmt.value;
                      return (
                        <Button
                          key={fmt.value}
                          variant="outline"
                          size="sm"
                          className={`${fmt.color} gap-1.5`}
                          onClick={() => handleExport(r.id, r.title, fmt.value)}
                          disabled={exportingId === r.id}
                        >
                          {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Icon className="w-4 h-4" />}
                          {fmt.value.toUpperCase()}
                        </Button>
                      );
                    })}
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
        {runs?.length === 0 && <p className="text-center text-slate-400 py-12">No reports generated yet. Select a cycle and generate your first report.</p>}
      </div>

      <Dialog open={showGenerate} onOpenChange={setShowGenerate}>
        <DialogContent>
          <DialogHeader><DialogTitle>Generate Report</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Report Type</Label>
              <Select value={form.reportType} onValueChange={v => setForm(p => ({ ...p, reportType: v }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>{REPORT_TYPES.map(t => <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div><Label>Title</Label><Input value={form.title} onChange={e => setForm(p => ({ ...p, title: e.target.value }))} placeholder="e.g. Q1 2025/26 Performance Report" /></div>
            {form.reportType === "quarterly" && (
              <div>
                <Label>Quarter</Label>
                <Select value={form.quarter.toString()} onValueChange={v => setForm(p => ({ ...p, quarter: Number(v) }))}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>{[1,2,3,4].map(q => <SelectItem key={q} value={q.toString()}>Q{q}</SelectItem>)}</SelectContent>
                </Select>
              </div>
            )}
          </div>
          <DialogFooter><Button onClick={handleGenerate} disabled={!form.title}>Generate</Button></DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Insight-Performance-Hub/artifacts/perf-app/src/app/features/reports/report-centre.component.ts
import { ChangeDetectionStrategy, Component, Inject, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { catchError, finalize, of, tap } from 'rxjs';
import { ApiService } from '@core/services/api.service';
import { ToastService } from '@core/services/toast.service';
import { Cycle, ReportRun, ReportType } from '@core/models/domain.model';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';

const REPORT_TYPES: { value: ReportType; label: string }[] = [
  { value: 'quarterly', label: 'Quarterly Report' },
  { value: 'mid-year', label: 'Mid-Year Report' },
  { value: 'annual', label: 'Annual Report' },
  { value: 'institutional-evaluation', label: 'Institutional Evaluation' },
];

@Component({
  selector: 'app-report-generate-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
  template: `
    <h2 mat-dialog-title>Generate Report</h2>
    <form (ngSubmit)="save()" #f="ngForm">
      <mat-dialog-content class="content">
        <mat-form-field appearance="outline">
          <mat-label>Report Type</mat-label>
          <mat-select [(ngModel)]="model.reportType" name="t">
            <mat-option *ngFor="let t of types" [value]="t.value">{{ t.label }}</mat-option>
          </mat-select>
        </mat-form-field>
        <mat-form-field appearance="outline"><mat-label>Title</mat-label><input matInput [(ngModel)]="model.title" name="ti" required placeholder="e.g. Q1 2025/26 Performance Report" /></mat-form-field>
        <mat-form-field appearance="outline" *ngIf="model.reportType === 'quarterly'">
          <mat-label>Quarter</mat-label>
          <mat-select [(ngModel)]="model.quarter" name="q">
            <mat-option *ngFor="let q of [1,2,3,4]" [value]="q">Q{{ q }}</mat-option>
          </mat-select>
        </mat-form-field>
      </mat-dialog-content>
      <mat-dialog-actions align="end">
        <button mat-button type="button" mat-dialog-close>Cancel</button>
        <button mat-flat-button color="primary" type="submit" [disabled]="saving() || !model.title">{{ saving() ? 'Generating…' : 'Generate' }}</button>
      </mat-dialog-actions>
    </form>
  `,
  styles: [`.content { display:flex; flex-direction: column; gap: 4px; padding-top: 12px !important; min-width: 460px; } mat-form-field { width: 100%; }`],
})
export class ReportGenerateDialogComponent {
  types = REPORT_TYPES;
  private readonly api = inject(ApiService);
  private readonly toast = inject(ToastService);
  saving = signal(false);
  model: { reportType: ReportType; title: string; quarter: number };
  constructor(public ref: MatDialogRef<ReportGenerateDialogComponent, ReportRun | null>, @Inject(MAT_DIALOG_DATA) public data: { cycleId: number }) {
    this.model = { reportType: 'quarterly', title: '', quarter: 1 };
  }
  save() {
    this.saving.set(true);
    const payload: Record<string, unknown> = { cycleId: this.data.cycleId, reportType: this.model.reportType, title: this.model.title };
    if (this.model.reportType === 'quarterly') payload['quarter'] = this.model.quarter;
    this.api.post<ReportRun>('/reports/generate', payload).pipe(
      tap((r) => { this.toast.success('Report generated'); this.ref.close(r); }),
      catchError((e) => { this.toast.error('Generation failed', e?.error?.message ?? e?.message); return of(null); }),
      finalize(() => this.saving.set(false)),
    ).subscribe();
  }
}

@Component({
  selector: 'app-report-centre',
  standalone: true,
  imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatFormFieldModule, MatInputModule, MatSelectModule, PageHeaderComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="plat-page">
      <app-page-header title="Report Centre" subtitle="Generate and retrieve performance reports." icon="description" tone="orange">
        <mat-form-field appearance="outline" class="cycle-pick">
          <mat-label>Cycle</mat-label>
          <mat-select [ngModel]="cycleId()" (ngModelChange)="onCycle($event)">
            <mat-option *ngFor="let c of cycles()" [value]="c.id">{{ c.financialYearLabel }}</mat-option>
          </mat-select>
        </mat-form-field>
        <button mat-flat-button color="primary" (click)="openGenerate()" [disabled]="!cycleId()"><mat-icon>add</mat-icon> Generate Report</button>
      </app-page-header>

      <div class="legend">
        <strong>Report colour coding</strong>
        <span><span class="sw met"></span> Target Met</span>
        <span><span class="sw partial"></span> Partially Met (70–99%)</span>
        <span><span class="sw missed"></span> Target Missed (&lt;70%)</span>
      </div>

      <div class="runs">
        <div *ngIf="!runs().length" class="empty">No reports generated yet. Select a cycle and generate your first report.</div>
        <div class="plat-card run" *ngFor="let r of runs()">
          <div class="run__main">
            <mat-icon class="run__icon">description</mat-icon>
            <div>
              <p class="run__title">{{ r.title }}</p>
              <p class="run__meta"><span class="cap">{{ r.reportType }}</span><span *ngIf="r.quarter"> • Q{{ r.quarter }}</span> • {{ r.generatedAt ? (r.generatedAt | date:'mediumDate') : 'Pending' }}</p>
            </div>
          </div>
          <div class="run__actions">
            <span class="badge" [class]="'b-' + (r.status || '').toLowerCase()">{{ r.status }}</span>
            <ng-container *ngIf="r.status === 'Generated'">
              <button mat-stroked-button class="ex-xlsx" (click)="exportRun(r, 'xlsx')" [disabled]="exporting() === r.id">
                <mat-icon>{{ exporting() === r.id && exportFormat() === 'xlsx' ? 'hourglass_top' : 'table_chart' }}</mat-icon> XLSX
              </button>
              <button mat-stroked-button class="ex-pdf" (click)="exportRun(r, 'pdf')" [disabled]="exporting() === r.id">
                <mat-icon>{{ exporting() === r.id && exportFormat() === 'pdf' ? 'hourglass_top' : 'picture_as_pdf' }}</mat-icon> PDF
              </button>
              <button mat-stroked-button class="ex-csv" (click)="exportRun(r, 'csv')" [disabled]="exporting() === r.id">
                <mat-icon>{{ exporting() === r.id && exportFormat() === 'csv' ? 'hourglass_top' : 'description' }}</mat-icon> CSV
              </button>
            </ng-container>
          </div>
        </div>
      </div>
    </section>
  `,
  styles: [`
    .cycle-pick { width: 220px; margin-right: 8px; }
    .legend { display:flex; gap: 16px; align-items: center; padding: 12px 16px; background: #f8fafc; border: 1px solid var(--plat-border); border-radius: 12px; margin: 12px 0 16px; font-size: 12px; }
    .sw { display: inline-block; width: 10px; height: 10px; border-radius: 2px; margin-right: 6px; vertical-align: middle; }
    .sw.met { background:#c6efce; border:1px solid #86efac; }
    .sw.partial { background:#ffeb9c; border:1px solid #fcd34d; }
    .sw.missed { background:#ffc7ce; border:1px solid #fca5a5; }
    .runs { display: flex; flex-direction: column; gap: 12px; }
    .run { display:flex; justify-content: space-between; align-items: center; padding: 14px 18px; }
    .run__main { display:flex; gap: 12px; align-items: center; }
    .run__icon { width: 36px; height: 36px; padding: 6px; border-radius: 8px; background: #eff6ff; color:#2563eb; }
    .run__title { margin:0; font-weight: 600; font-size: 14px; }
    .run__meta { margin: 2px 0 0; font-size: 12px; color: #64748b; }
    .run__actions { display: flex; gap: 8px; align-items: center; }
    .badge { padding: 2px 10px; border-radius: 999px; font-size: 11px; font-weight: 600; background:#e2e8f0; color:#475569; }
    .b-generated { background:#dcfce7; color:#15803d; }
    .b-pending { background:#f1f5f9; color:#475569; }
    .b-failed { background:#fee2e2; color:#b91c1c; }
    .ex-xlsx { color:#15803d; }
    .ex-pdf { color:#b91c1c; }
    .ex-csv { color:#2563eb; }
    .cap { text-transform: capitalize; }
    .empty { padding: 48px; text-align: center; color: #94a3b8; }
  `],
})
export class ReportCentreComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly dialog = inject(MatDialog);
  private readonly toast = inject(ToastService);
  cycles = signal<Cycle[]>([]);
  cycleId = signal<number | null>(null);
  runs = signal<ReportRun[]>([]);
  exporting = signal<number | null>(null);
  exportFormat = signal<string | null>(null);
  activeCycle = computed(() => this.cycles().find((c) => c.id === this.cycleId()) ?? null);

  ngOnInit() {
    this.api.get<Cycle[]>('/cycles').pipe(catchError(() => of([] as Cycle[]))).subscribe((cs) => {
      const arr = Array.isArray(cs) ? cs : [];
      this.cycles.set(arr);
      const def = arr.find((c) => c.status === 'Open') ?? arr[0];
      if (def) { this.cycleId.set(def.id); this.loadRuns(); }
    });
  }
  onCycle(id: number) { this.cycleId.set(id); this.loadRuns(); }
  loadRuns() {
    if (!this.cycleId()) return;
    this.api.get<ReportRun[]>('/reports/runs', { cycleId: this.cycleId()! })
      .pipe(catchError(() => of([] as ReportRun[])))
      .subscribe((r) => this.runs.set(Array.isArray(r) ? r : []));
  }
  openGenerate() {
    if (!this.cycleId()) return;
    this.dialog.open(ReportGenerateDialogComponent, { data: { cycleId: this.cycleId()! }, panelClass: 'plat-dialog', autoFocus: false })
      .afterClosed().subscribe((r) => { if (r) this.loadRuns(); });
  }
  exportRun(r: ReportRun, format: 'xlsx' | 'pdf' | 'csv') {
    this.exporting.set(r.id);
    this.exportFormat.set(format);
    this.api.getBlob(`/reports/runs/${r.id}/export`, { format }).pipe(
      tap((blob) => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${r.title.replace(/[^a-zA-Z0-9_ -]/g, '_')}.${format}`;
        document.body.appendChild(a); a.click(); document.body.removeChild(a);
        URL.revokeObjectURL(url);
        this.toast.success(`Report downloaded as ${format.toUpperCase()}`);
      }),
      catchError((e) => { this.toast.error('Download failed', e?.error?.message ?? e?.message); return of(null); }),
      finalize(() => { this.exporting.set(null); this.exportFormat.set(null); }),
    ).subscribe();
  }
}
